### ISSUE TITLE
和Druid集成的时，Druid的SQL监控中没有相关sql

### ISSUE THREAD

**Issue by cxyzjp** [sharding-sphere/sharding-sphere#1002]
和Druid集成的时，Druid的“SQL监控“中没有相关sql。
谢谢解答一下

已经集成成功，在Druid的页面可以看到数据源这些信息。
已经正确分库分表，正确执行SQL。

**Comment by terrymanu** [comment]
Hello, we prefer use english to discuss issue.
For bug report, we can keep it, but for question, we will close directly.
