### ISSUE TITLE
Sharding properties should configure independent

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1004]
### Which version of Sharding-Sphere do you using?

3.0.0.M2

### Expected behavior

Sharding properties should configure independent.

### Actual behavior

Sharding properties configure with sharding rule, if use master-slave rule only, cannot load sharding properties.

**Comment by HanYL-coder** [comment]
why M2 not released yet.
I'm expecting it. Cuz there's a NullPointerException at JDBCShardingRefreshHandler.java:49 when querying a simple sql with 17 datasources(multi datasources).

**Comment by tristaZero** [comment]
Thanks for your comment, and M2 is coming soon.
If you have a problem, please submit an issue.
@HanYL-coder

**Comment by tristaZero** [comment]
To config props for MasterSlave rule, not just for Sharding rule, we need to do work as follows:

    Add modules in Sharding core.
    Support it in Sharding JDBC and Yaml.
    Support it in Spring namespace.
    Support it in Spring boots.
    Support it in Sharding Proxy.
    Support to store the props config in registry.

**Comment by HanYL-coder** [comment]
I saw the issue was fixed at M2.

@tristaZero 

https://github.com/sharding-sphere/sharding-sphere/issues/919

**Comment by terrymanu** [comment]
fixed at 3.0.0.M2
