### ISSUE TITLE
Cannot catch exception when using Sharding-JDBC route to multiple data nodes

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1010]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?

3.0.0.M1

### Expected behavior

Can catch SQLException when exception occur

### Actual behavior

Cannot catch SQLException when exception occur

### Reason analyze

Because Sharding-JDBC use multiple thread to execute SQL, if exception occur, cannot catch it on main thread.

**Comment by tristaZero** [comment]
fixed it at #1039
