### ISSUE TITLE
[io.shardingsphere.jdbc.orchestration.spring.datasource.OrchestrationShardingDataSourceFactoryBean]: Constructor threw exception; nested exception is java.lang.NullPointerException

### ISSUE THREAD

**Issue by dongweizhao** [sharding-sphere/sharding-sphere#1027]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
3.0.0.M1
### Expected behavior
Init dataSource success
### Actual behavior
 java.lang.NullPointerException
### Reason analyze
![](https://ws4.sinaimg.cn/large/006tNc79gy1ftdx9dksfaj31kw0uttk9.jpg)
![](https://ws1.sinaimg.cn/large/006tNc79gy1ftdxbg6npbj31ii0p8qaw.jpg)
### Steps to reproduce the behavior
 https://github.com/sharding-sphere/sharding-sphere-example.git
spring-namespace-mybatis-example/io.shardingsphere.example.spring.namespace.mybatis.main.orche.zookeeper.ShardingOnlyWithDatabases
1. execute ShardingOnlyWithDatabases

2. modify LOAD_CONFIG_FROM_REG_CENTER=true;
    execute ShardingOnlyWithDatabases

### Please provide the reproduce example codes (such as a github link).
https://github.com/sharding-sphere/sharding-sphere-example.git
version:3.0.0.M1

**Comment by ma-xiao-guang-64** [comment]
Thank you, it is fix in 3.0.0.M2

**Comment by tristaZero** [comment]
@dongweizhao Hi, sir.
Thanks for your issue.
I ran this example again, and i guessed whether your zk registry is ok for this example?
As the code says, when you modify LOAD_CONFIG_FROM_REG_CENTER=true, it means, your program need to load the config from your zk registry. Therefore, if there is no available config in your zk registry, you will get error information.

So, i suggest you can solve this problem by the following methods.

1. Store your configuration in zk registry configued in xml file.
2. Firstly run this example by using LOAD_CONFIG_FROM_REG_CENTER=false to make program store available config in zk registry itself, and then modify LOAD_CONFIG_FROM_REG_CENTER=true, and run again. I believe you will get the expected results.

If any problems, please contact me.

**Comment by tristaZero** [comment]
@dongweizhao Thanks for your issue, we have fixed this problem in 3.0.0.M2, and also some modules are optimized to capture excpetions.
