### ISSUE TITLE
为什么我mybatis  plugin sql拦截器无效？

### ISSUE THREAD

**Issue by god8816** [sharding-sphere/sharding-sphere#1038]
用Sharding-Sphere后发现以前的mybatis  plugin sql拦截器无效了，是不是Sharding-Sphere已经在我之前拦截了？

**Comment by ma-xiao-guang-64** [comment]
Please provide the reproduce example codes (such as a github link).

**Comment by god8816** [comment]
mybatis拦截器代码：
@Intercepts({
		@Signature(type = Executor.class, method = "query", args = {
				MappedStatement.class, Object.class, RowBounds.class,
				ResultHandler.class}),
		@Signature(type = Executor.class, method = "update", args = {
				MappedStatement.class, Object.class})})
public class PerformanceInterceptor implements Interceptor {

	private static final Logger logger = LoggerFactory.getLogger(PerformanceInterceptor.class);
	private static final DateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

	@Override
	public Object intercept(Invocation invocation) throws Throwable {
		MappedStatement mappedStatement = (MappedStatement) invocation.getArgs()[0];
		Object parameterObject = null;
		if (invocation.getArgs().length > 1) {
			parameterObject = invocation.getArgs()[1];
		}
		String statementId = mappedStatement.getId();
		BoundSql boundSql = mappedStatement.getBoundSql(parameterObject);
		Configuration configuration = mappedStatement.getConfiguration();
		String sql = getSql(boundSql, parameterObject, configuration);

		long start = System.currentTimeMillis();
		Object result = invocation.proceed();
		long end = System.currentTimeMillis();
		long timing = end - start;
		logger.info("sql耗时：" + timing + " ms" + " - id:" + statementId + " - Sql:" + sql);
		return result;
	}

**Comment by god8816** [comment]
这个代码无效，打断点不执行。

**Comment by terrymanu** [comment]
Hello, we prefer use english to discuss issue.
For bug report, we can keep it, but for question, we will close directly.
