### ISSUE TITLE
use Sharding-Sphere  discovery  mybatis plugin sql interceptor not use ？

### ISSUE THREAD

**Issue by god8816** [sharding-sphere/sharding-sphere#1042]
@Intercepts({
@Signature(type = Executor.class, method = "query", args = {
MappedStatement.class, Object.class, RowBounds.class,
ResultHandler.class}),
@Signature(type = Executor.class, method = "update", args = {
MappedStatement.class, Object.class})})
public class PerformanceInterceptor implements Interceptor {

private static final Logger logger = LoggerFactory.getLogger(PerformanceInterceptor.class);
private static final DateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

@Override
public Object intercept(Invocation invocation) throws Throwable {
	MappedStatement mappedStatement = (MappedStatement) invocation.getArgs()[0];
	Object parameterObject = null;
	if (invocation.getArgs().length > 1) {
		parameterObject = invocation.getArgs()[1];
	}
	String statementId = mappedStatement.getId();
	BoundSql boundSql = mappedStatement.getBoundSql(parameterObject);
	Configuration configuration = mappedStatement.getConfiguration();
	String sql = getSql(boundSql, parameterObject, configuration);

	long start = System.currentTimeMillis();
	Object result = invocation.proceed();
	long end = System.currentTimeMillis();
	long timing = end - start;
	logger.info("sql耗时：" + timing + " ms" + " - id:" + statementId + " - Sql:" + sql);
	return result;
}

**Comment by ma-xiao-guang-64** [comment]
mybatis interceptor before execute sql in ss, please check mybatis interceptor

**Comment by terrymanu** [comment]
To report a bug, please reference the issue template, answer all questions.

Please note: 

### For bug report, please *MUST* provide the reproduce example codes (such as a github link).

**Comment by terrymanu** [comment]
No feedback any more, just close it.
