### ISSUE TITLE
Spring auto configuration using issue

### ISSUE THREAD

**Issue by HanYL-coder** [sharding-sphere/sharding-sphere#1044]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
3.0.0.M1
### Expected behavior
get the dataSourceMap by inheriting SpringBootConfiguration class
### Actual behavior
dataSourceMap is private, cannot be got from subclasses

**Comment by terrymanu** [comment]
No feedback any more, just close it.
