### ISSUE TITLE
how to use RangeShardingAlgorithm with PreciseShardingAlgorithm

### ISSUE THREAD

**Issue by naah69** [sharding-sphere/sharding-sphere#1052]
I use sharding-jdbc-spring-boot-starter 3.0.0.M1
i can't find relevent document on the website.
i try some times

but i can't enter implementation Class of RangeShardingAlgorithm.it will enter  implementation Class of PreciseShardingAlgorithm.

please tell me how to use it,or give me a demo
this is my config and my code;

### yml

config:
      sharding:
        default-database-strategy:
          standard:
            range-algorithm-class-name: shardingsphere.demo.strategy.NaahRangeShardingAlgorithm
            precise-algorithm-class-name: shardingsphere.demo.strategy.HashCodePreciseShardingAlgorithm
            sharding-column: user_id

### RangeShardingAlgorithm

public class NaahRangeShardingAlgorithm implements RangeShardingAlgorithm {

    private final Logger logger = LoggerFactory.getLogger(NaahRangeShardingAlgorithm.class);

    public NaahRangeShardingAlgorithm() {
    }

    @Override
    public Collection<String> doSharding(Collection availableTargetNames, RangeShardingValue shardingValue) {
        logger.info("Range availableTargetNames:" + JSON.toJSONString(availableTargetNames) + ",shardingValue:" + JSON.toJSONString(shardingValue));
        return null;
    }
}

### PreciseShardingAlgorithm

public class HashCodePreciseShardingAlgorithm implements PreciseShardingAlgorithm<Long> {

    private final Logger logger = LoggerFactory.getLogger(HashCodePreciseShardingAlgorithm.class);

    @Override
    public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<Long> shardingValue) {
        logger.info("availableTargetNames:" + JSON.toJSONString(availableTargetNames) + ",preciseShardingValue:" + JSON.toJSONString(shardingValue));
        //通过hashcode取模
        int num= (shardingValue.getValue()+"").hashCode()%availableTargetNames.size();
        String[] list = availableTargetNames.toArray(new String[availableTargetNames.size()]);
        if(num<=availableTargetNames.size()){
            return list[num];
        }
        return null;
    }
}

**Comment by tuohai666** [comment]
I'll add an example for RangeShardingAlgorithm later.

**Comment by naah69** [comment]
i had solved that problem.
but i have a new problem.
 **Data sharding and Read-write splitting how to use together.**
i find few document and demo online.i will upload my demo after that i study it.
can u Add me Wechat?
WeChat:278567949

**Comment by terrymanu** [comment]
add example via https://github.com/sharding-sphere/sharding-sphere-example/pull/69
