### ISSUE TITLE
sharding-proxy cant't comprehend "`" in DDL

### ISSUE THREAD

**Issue by cxdhefei** [sharding-sphere/sharding-sphere#1054]
for example:
ddl: ALTER TABLE `order_consume_detail` CHANGE COLUMN `order_id` `order_id` varchar(32) NOT NULL;
log: Error : Cannot find table rule and default data source with logic table: '`order_consume_detail`'

**Comment by tuohai666** [comment]
Please provide the version information.
I've tested on 3.0.0.M3 and found this problem already solved.

**Comment by tuohai666** [comment]
Duplicate with #887.
