### ISSUE TITLE
Table name of no sharding is set low-case defaultly

### ISSUE THREAD

**Issue by zkzong** [sharding-sphere/sharding-sphere#1057]
### Which version of Sharding-Sphere do you using?
2.0.3

### Expected behavior
insert data correctly

### Actual behavior
can't insert data, throw exception "Table 'test' doesn't exist"

### Reason analyze
Database is case-sensitive and table name is in upper-case. a part of tables is sharing, and other part of tables is not sharding, when insert data into no sharding table, it throw exception "Table 'test' doesn't exist".
The reason is that sharding-jdbc set table name low-case defaultly.

**Comment by terrymanu** [comment]
fixed at 3.0.0.M3
