### ISSUE TITLE
The results obtained through group by are not correct

### ISSUE THREAD

**Issue by robinzhai** [sharding-sphere/sharding-sphere#1058]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
sharding-jdbc-core 2.0.3
### Expected behavior
like <https://github.com/sharding-sphere/sharding-sphere/issues/128>

item|count
a|100
b|200

### Actual behavior
but 
a | 300

### Reason analyze

SELECT
	a.item AS item,
a.item1 AS item1,
COUNT(a.id) AS total
FROM
	(
		SELECT
			id,
			item,
			item1
		FROM
			order
		WHERE
			area_id = '123'
	) a   
GROUP BY a.item,a.item1

When there are subqueries in the SQL statement, the result of group by is incorrect.

**Comment by terrymanu** [comment]
hello, please note, we don't support this SQL, just reference: http://shardingsphere.io/document/current/en/features/sharding/usage-standard/sql/
