### ISSUE TITLE
[Vote] Welcome new PMC member XiaoHu Zhang joining Sharding-Sphere

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1063]
Orange Finance arrange a full time developer @beckhampu who is responsible for APM of Sharding-Sphere for several months. His pull requests are #817,  #856 and  #958, and he is already in Sharding-Sphere's committer list.

Orange Finance have already establish a new department which name is `innovation center`, and plan to as a sponsor to support Sharding-Sphere's development continually. 

Today, we will invite XiaoHu Zhang(@pottieva) who is an director of innovation center for Orange Finance to join into Sharding-Sphere PMC. We believe that his joining will make Sharding-Sphere better and better.

All PMC members, please vote for this decision:

@haocao
@wu-sheng
@hanahmily
@PegasusS

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

**Comment by wu-sheng** [comment]
+1 

Welcome and glad we have a new partner and sponsor. Look forward our cooperations.

**Comment by haocao** [comment]
agree, yes, +1

**Comment by hanahmily** [comment]
Welcome,+1

**Comment by hanahmily** [comment]
Welcome,+1

**Comment by PegasusS** [comment]
Welcome,Tiger!  +1

**Comment by terrymanu** [comment]
All pass, welcome XiaoHu Zhang join us
