### ISSUE TITLE
文档 配置 不对

### ISSUE THREAD

**Issue by opjklu** [sharding-sphere/sharding-sphere#1065]
For English only, other languages we will close it directly.
![qq 20180729195220](https://user-images.githubusercontent.com/18340568/43366045-3ece1fd8-9369-11e8-8354-1c4f19321d15.png)

Please answer these questions before submitting your issue. Thanks!
废了老半天 才 配置好 你们的 文档 写的配置 根本 不行 老报错（用的是3.0的，springboot是2.0.3），数据库和表都是用下划线分割的
![ebteg_9c 9z2r08c4ul6j g](https://user-images.githubusercontent.com/18340568/43366109-18d4d15e-936a-11e8-9568-82e30be40078.png)

**Comment by terrymanu** [comment]
Hello, only english can use to discuss issue.
