### ISSUE TITLE
insert ... on duplicate key update has some bug

### ISSUE THREAD

**Issue by ma-xiao-guang-64** [sharding-sphere/sharding-sphere#1066]
sql like that insert into table(id, name) values (1, ?)on duplicate key update name = ?
when parameter after on duplicate key update  that has some bug

**Comment by terrymanu** [comment]
Is any relationship of this issue and #1105? @AIKiller

**Comment by ma-xiao-guang-64** [comment]
I won't to fix after careful consideration
l don't think it possible that use placeholder in update clause
usually, we use insert ... update like this
1、 insert into table (name, version) values (?, ?) on duplicate key update version = version + 1
2、1、 insert into table (name) values (?), (?) on duplicate key update version = values(name)

**Comment by victormferrara** [comment]
Hi! Just FYI it is possible to use the placeholder in the update clause but as you say the common usage is just to use the values keyword or similar.

Cheers!

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
