### ISSUE TITLE
Data sharding and Read-write splitting  throw Exception together.

### ISSUE THREAD

**Issue by naah69** [sharding-sphere/sharding-sphere#1073]
version:3.0.0.M1

YML
![image](https://user-images.githubusercontent.com/25682169/43449088-288249a0-94e2-11e8-9f74-e8a712ab99b5.png)

Exception
![image](https://user-images.githubusercontent.com/25682169/43449125-406c63f2-94e2-11e8-8798-093e389f0080.png)

Data sharding is failure when Data sharding and Read-write splitting were used together

**Comment by terrymanu** [comment]
Please provide more details for sql.show

**Comment by terrymanu** [comment]
By the way, for report a bug, we prefer you reference the issue template, and fill all required information.

**Comment by naah69** [comment]
**Which version of Sharding-Sphere do you using?**
3.0.0.M1

**Expected behavior**
Data sharding and Read-write splitting work well together.

**Actual behavior**
throw Exception that is org.springframework.jdbc.BadSqlGrammarException

**Reason analyze**
SQL：INSERT INTO t_order (order_id,user_id) VALUES (?,?) 
but t_order is logic table.
the real table is t_order_0 and t_order_1.
so data sharding may not work.

**File**
https://github.com/naah69/sharding-jdbc-3-demo/tree/master/sharding-jdbc-rw-splitting-data-sharding

this is that code.

**Comment by naah69** [comment]
i had resolved this problem.
now i will explain my problem:

**Read/Write Splitting doc:**
http://shardingsphere.io/document/current/cn/manual/sharding-jdbc/usage/read-write-splitting
![image](https://user-images.githubusercontent.com/25682169/43507325-63b30272-959f-11e8-9731-e3feaf19d018.png)
but this config should be configuration when  Read/Write Splitting was in use alone.

**SpringBoot Config doc:**
http://shardingsphere.io/document/current/cn/manual/sharding-jdbc/configuration/config-spring-boot/
![image](https://user-images.githubusercontent.com/25682169/43507681-63554cda-95a0-11e8-8710-a7dcf5601c82.png)
this is real correct config when Data sharding and Read-write splitting work together.

i will upload some demo on my github.
if u are in trouble，we can discuss something about sharding-jdbc

**Comment by tristaZero** [comment]
Thank you for your reply.
