### ISSUE TITLE
Table meta data cannot refresh after Create table operate

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1083]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?

3.0.0.M1

### Reason analyze

After DDL, `TableMetaDataLoader` will refresh table meta data by logic table name. But parse engine cannot get table name for default data source. Should change parser core logic, let it can get table name even from default data source.

**Comment by tristaZero** [comment]
After investigating, Our parser can parse out the logic table name, and when do routing, we will push all tables that do not been configured in configuration to default data source. If you do not configure default data source either, an error will appear.
