### ISSUE TITLE
After Application Running，there is nothing in zookeeper

### ISSUE THREAD

**Issue by naah69** [sharding-sphere/sharding-sphere#1086]
### Which version of Sharding-Sphere do you using?
3.0.0.M1
### Expected behavior
we can get config in zookeeper
### Actual behavior
there is nothing in zookeeper.
![image](https://user-images.githubusercontent.com/25682169/43558663-2fdba5b4-963d-11e8-9f5c-8c91f2f098d3.png)

### For bug report, please *MUST* provide the reproduce example codes (such as a github link).

https://github.com/naah69/sharding-jdbc-3-demo/tree/master/sharding-jdbc-orchestration

**Comment by tristaZero** [comment]
When the following dependencies are configured togather, the latter will be invalid. Please remove the 
former to use orchestration-spring-boot.

<dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>${shardingsphere.version}</version>
</dependency>

<dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc--starter</artifactId>
            <version>${shardingsphere.version}</version>
</dependency>
