### ISSUE TITLE
some proxy config make sharding-proxy throw Exception

### ISSUE THREAD

**Issue by naah69** [sharding-sphere/sharding-sphere#1090]
### Which version of Sharding-Sphere do you using?
3.0.0.M1
### Expected behavior
configuration sharding-proxy.
### Actual behavior
many config items thar are  in document are not available in shrading-proxy config.
i read DataSourceParameter and YamlProxyConfiguration.
i can't find these config items that make shrading-proxy throw exception.
### Reason analyze
DataSourceParameter ，YamlProxyConfiguration and don't have these fields.
document url:
http://shardingsphere.io/document/current/cn/manual/sharding-proxy/configuration/
![image](https://user-images.githubusercontent.com/25682169/43568110-5ae998be-9666-11e8-8920-32b230927b55.png)
![image](https://user-images.githubusercontent.com/25682169/43568198-8b67b98a-9666-11e8-91f5-c00467114dcd.png)
![image](https://user-images.githubusercontent.com/25682169/43569038-ed88c80a-9668-11e8-833f-3f0ff3722146.png)

### Steps to reproduce the behavior

https://github.com/naah69/sharding-jdbc-3-demo/blob/master/sharding-proxy-demo/src/main/resources/proxy-config/config-error.yaml

**Comment by terrymanu** [comment]
Please don't use 3.0.0.M2's config use to 3.0.0.M1

**Comment by naah69** [comment]
where is the 3.0.0.M1's config?
