### ISSUE TITLE
如果分片字段为varchar

### ISSUE THREAD

**Issue by baisijian** [sharding-sphere/sharding-sphere#1091]
shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_0.t_order_${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: **t_order_${order_id.hashCode() % 2}**
      keyGeneratorColumnName: order_id
  bindingTables:
    - t_order
  defaultTableStrategy:
    none:
  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator

使用插入语句
insert into t_order
(
	order_id,
	user_id,
	class_Id
) 
values
(
	"a",
	"b",
	1
)

**报错 generated key only support number**

**Comment by terrymanu** [comment]
Hello, only english can use to discuss issue.

**Comment by quicksandznzn** [comment]
解决了嘛
