### ISSUE TITLE
sql  exception

### ISSUE THREAD

**Issue by dawe001** [sharding-sphere/sharding-sphere#1101]
insert into tb_user (id, name,c_key)
    values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR},#{cKey,jdbcType=VARCHAR})
the above sqlMapper throw NullPointerException  at runTime, but  , it will be ok when takeout 'name' like this:
insert into tb_user (id, c_key)
    values (#{id,jdbcType=VARCHAR}, #{cKey,jdbcType=VARCHAR})

### Which version of Sharding-Sphere do you using?
3.0.0.M1
### Expected behavior
work OK
### Actual behavior
throw Exception
### Reason analyze
column can't use 'name' ?
### Steps to reproduce the behavior
insert into anyTable (id, name, description)
    values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR},#{description,jdbcType=VARCHAR})

**Comment by terrymanu** [comment]
Could you explain why create an issue, and close it by yourself without any reason?
