### ISSUE TITLE
transaction commit error

### ISSUE THREAD

**Issue by Lange-Li** [sharding-sphere/sharding-sphere#1114]
error info:
`Could not dispatch event: io.shardingsphere.core.transaction.listener.TransactionListener@15ee8861 to public void io.shardingsphere.core.transaction.listener.TransactionListener.listen(io.shardingsphere.core.transaction.event.TransactionEvent) throws java.sql.SQLException`

use 3.0.0.M2  version , transaction commit error
use 3.0.0.M1 version, normal transaction commit

**Comment by terrymanu** [comment]
transaction feature is for 3.1.0, in 3.0.0 is not stable, we have already remove it.
