### ISSUE TITLE
一个数据表最多支持分512张表，如过想分更多的表该怎么处理

### ISSUE THREAD

**Issue by ryandonglin** [sharding-sphere/sharding-sphere#1128]
最近在工作中用到了分库分表插件，然后我们目前将一个数据表分成了1024张，在我们的测试过程中发现一旦我们设置的sharding-jdbc的分表数量超过512就会报类似表不存在的错误，又大牛遇到过类似的问题吗？有什么更好的解决办法吗

**Comment by terrymanu** [comment]
Hello, only english can use to discuss issue.

**Comment by ryandonglin** [comment]
I've already found the real problem, the question is that we're current using technologies such as dbproxy to manage 2 different db into one address, and in my project i am using druid to connect to one of the database and therefor we can only see part of tables in that db, so any suggestion can offered to solve the problem?
