### ISSUE TITLE
table alias case sensitive

### ISSUE THREAD

**Issue by wujun8** [sharding-sphere/sharding-sphere#1141]
### Which version of Sharding-Sphere do you using?
3.0.0.M2
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
route select query to exact one table
### Actual behavior
route to all tables
### Reason analyze
Logic SQL: 
```sql
SELECT o.*
        FROM t_order O
            LEFT JOIN t_order_item i ON o.order_id=i.order_id
        WHERE o.user_id=? 
```
The alias of table t_order is uppercase, but I use lowercase in where clause, and result in sharding key not found, so route to all tables.
And the above sql runs ok directly in MySql if config `lower_case_table_names=1`, while SS always cares about the lettercase.
If we modify the code from `io/shardingsphere/core/parsing/parser/context/table/Tables.java:111`
```java
if (each.getAlias().isPresent() && each.getAlias().get().equalsIgnoreCase(alias)) {
```
but that will cause problems when `lower_case_table_names=0`, so the key is **how to get the config value** in the context, right?

### Steps to reproduce the behavior
Just prepare data distributed in tables, and run `io.shardingsphere.example.spring.namespace.mybatis.main.orche.zookeeper.ShardingOnlyWithTables#main`
### For bug report, please *MUST* provide the reproduce example codes (such as a github link).
example codes in [branch table-alias-case-sensitive](https://github.com/wujun8/sharding-sphere-example/tree/table-alias-case-sensitive)

**Comment by tuohai666** [comment]
Hi @wujun8, you are right. Could discuss and vote in #864 first? I'll fix the Case Sensitive or Case Insensitive issues together.
