### ISSUE TITLE
how to config sharding-proxy when physical table name with fixed zero

### ISSUE THREAD

**Issue by GitProBo** [sharding-sphere/sharding-sphere#1144]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
sharding-proxy-3.0.0.M2
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
use sharding-proxy for a database with a physical table name with fixed zero
shardingRule:
  tables:
    pay_cmdy: 
      actualDataNodes: pay_${0..15}.pay_cmdy_000${0..9}
      databaseStrategy: 
        inline:
          shardingColumn: payment_no
          algorithmExpression: pay_${payment_no % 16}
### Actual behavior
Exception in thread "main" io.shardingsphere.core.exception.ShardingException: Cannot get uniformed table structure for `pay_cmdy`. The different meta data of actual tables are as follows:
TableMetaData(columnMetaData=[ColumnMetaData(columnName=id, columnType=BIGINT UNSIGNED, primaryKey=true), ColumnMetaData(columnName=payment_no, columnType=VARCHAR, primaryKey=false), ColumnMetaData(columnName=cmdy_id, columnType=VARCHAR, primaryKey=false), ColumnMetaData(columnName=cmdy_name, columnType=VARCHAR, primaryKey=false), ColumnMetaData(columnName=price, columnType=INT, primaryKey=false), ColumnMetaData(columnName=quantity, columnType=VARCHAR, primaryKey=false), ColumnMetaData(columnName=discount_fee, columnType=INT, primaryKey=false), ColumnMetaData(columnName=promotion_id, columnType=VARCHAR, primaryKey=false), ColumnMetaData(columnName=create_time, columnType=TIMESTAMP, primaryKey=false), ColumnMetaData(columnName=update_time, columnType=TIMESTAMP, primaryKey=false)])
TableMetaData(columnMetaData=[]).
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader.checkUniformed(TableMetaDataLoader.java:136)
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader.load(TableMetaDataLoader.java:68)
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader.load(TableMetaDataLoader.java:63)
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataInitializer.loadShardingTables(TableMetaDataInitializer.java:71)
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataInitializer.load(TableMetaDataInitializer.java:60)
	at io.shardingsphere.proxy.config.RuleRegistry.initShardingMetaData(RuleRegistry.java:140)
	at io.shardingsphere.proxy.frontend.ShardingProxy.<init>(ShardingProxy.java:58)
	at io.shardingsphere.proxy.Bootstrap.startWithoutRegistryCenter(Bootstrap.java:106)
	at io.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:65)

**Comment by terrymanu** [comment]
Cannot get uniformed table structure for pay_cmdy. 
The exception tell you the reason.

**Comment by GitProBo** [comment]
actual table structure is like this.
mysql> show create table pay_cmdy_0000\G;
*************************** 1. row ***************************
       Table: pay_cmdy_0000
Create Table: CREATE TABLE `pay_cmdy_0000` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `payment_no` varchar(32) NOT NULL DEFAULT '' COMMENT '支付单号',
  `cmdy_id` varchar(64) NOT NULL DEFAULT '' COMMENT '商品ID',
  `cmdy_name` varchar(64) NOT NULL DEFAULT '' COMMENT '商品名称',
  `price` int(11) NOT NULL DEFAULT '0' COMMENT '金额',
  `quantity` varchar(11) NOT NULL DEFAULT '0' COMMENT '数量,可小数',
  `discount_fee` int(11) NOT NULL DEFAULT '0' COMMENT '优惠金额',
  `promotion_id` varchar(64) NOT NULL DEFAULT '' COMMENT '优惠ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_pay_cmdy_payment_no` (`payment_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='付款商品'
1 row in set (0.00 sec)

ERROR:
No query specified

and I'm sure all actualDataNodes table structures are same as it.

**Comment by terrymanu** [comment]
what is your table sharding strategy?

**Comment by GitProBo** [comment]
pay_cmdy: 
      actualDataNodes: pay_${0..15}.pay_cmdy_000${0..9}
      databaseStrategy: 
        inline:
          shardingColumn: payment_no
          algorithmExpression: pay_${payment_no % 16}
      tableStrategy: 
        inline:
          shardingColumn: payment_no
          algorithmExpression: pay_cmdy_${payment_no % 10}

**Comment by tuohai666** [comment]
Hi @GitProBo, some findings:

actualDataNodes: pay_${0..15}.pay_cmdy_000${0..9}  (3 zero)

Create Table: CREATE TABLE pay_cmdy_0000  (4 zero)

**Comment by terrymanu** [comment]
@GitProBo Why the actual tables are uniformed?

**Comment by terrymanu** [comment]
No feedback any more, just close it.
