### ISSUE TITLE
Sharding-JDBC 整合MyBatis 时新增和查询 返回的ID与实际ID不一致

### ISSUE THREAD

**Issue by sunjiabo** [sharding-sphere/sharding-sphere#1147]
Sharding-JDBC + MyBatis ，新增时返回了ID为236456576959905800，实际进入数据库表的ID为236456576959905792。
查询时使用ID236456576959905792查询，实际返回对象的ID为236456576959905800

版本Sharding-Sphere 3.0.0.M2

**Comment by sunjiabo** [comment]
补充：版本Sharding-Sphere  3.0.0.M2

**Comment by terrymanu** [comment]
Hello, only english can use to discuss issue.
