### ISSUE TITLE
why left join can not use "()"  to  hold the join condition

### ISSUE THREAD

**Issue by zhuojl** [sharding-sphere/sharding-sphere#1154]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
3.0.0.M2
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc  shareTables
### Expected behavior
no exception when use "select a.name from  a left join b on (a.id = b.a_id)"
### Actual behavior
Error querying database.  Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'EQ', actual token is 'IDENTIFIER', literals is 'b'.
### Reason analyze
parse error
### Steps to reproduce the behavior
select a.name from  a left join b on (a.id = b.a_id)

**Comment by terrymanu** [comment]
Cannot support brackets redundancy, FIY: http://shardingsphere.io/document/current/en/features/sharding/usage-standard/sql/
