### ISSUE TITLE
[Vote] upgrade JDK8 on Sharding-Sphere 3.x

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1157]
JDK8 is more popular, and JDK 7 has abandoned by oracle. 
In future, we will use service-comb-saga(https://github.com/apache/incubator-servicecomb-saga)  to to deal with BASE transaction. Saga only support JDK 8 and above version. So we planning upgrade to JDK 8 for new Sharding-JDBC and Sharding-Proxy on 3.0.0.

This vote will open in at least a week. Welcome any contributor, end user and interested people to express themselves.

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

**Comment by tuohai666** [comment]
+1

**Comment by tristaZero** [comment]
agree, yes, +1

**Comment by liudunxu** [comment]
+1

**Comment by cxdhefei** [comment]
+1

**Comment by forecasted** [comment]
+1

**Comment by wangxiuwen** [comment]
+1

**Comment by mark-wk** [comment]
+1

**Comment by duerlatter** [comment]
-1

**Comment by SteNicholas** [comment]
+1

**Comment by duerlatter** [comment]
理论上是应该+1  但事实还是蛮希望-1

**Comment by lphzxf** [comment]
+1

**Comment by cjbid** [comment]
+1

**Comment by ruanjiehui** [comment]
+1，期待使用上函数式编程的API

**Comment by txsgit** [comment]
+1

**Comment by wade92** [comment]
+1

**Comment by guo156627977** [comment]
agree, yes, +1

**Comment by firebullwang** [comment]
+1

**Comment by saaavsaaa** [comment]
agree, yes, +1

**Comment by lcx1989210** [comment]
+1

**Comment by qiankunshe** [comment]
agree, yes, +1

**Comment by xiaoyanghapi** [comment]
+1

**Comment by andismail** [comment]
+1

**Comment by LSloveYJ** [comment]
+1
+1
+1

**Comment by iqinghe** [comment]
+1

**Comment by jiguansheng5** [comment]
+1

**Comment by iqinghe** [comment]
agree, yes, +1

**Comment by 595431930** [comment]
+1

**Comment by Alanlxh** [comment]
+1

**Comment by gsfeng2015** [comment]
+1

**Comment by hyjcxy** [comment]
+1

**Comment by liqinlong** [comment]
+1

**Comment by diviner01** [comment]
+1

**Comment by arewei** [comment]
+1

**Comment by cherrylzhao** [comment]
+1

**Comment by unimme** [comment]
+1

**Comment by 0x0010** [comment]
+1

**Comment by chenhaifeng2016** [comment]
+1

**Comment by yuemanxilou** [comment]
+1

**Comment by SBTimo** [comment]
+1

**Comment by zhanjr** [comment]
agree, yes, +1
Many open source frameworks runs on a JDK higher than or equal to version 8.

**Comment by anjingdemutou** [comment]
agree, yes, +1

**Comment by kissdragon-z** [comment]
+1

**Comment by diviner01** [comment]
agree, yes, +1

**Comment by unimme** [comment]
Upgrade, anyway, I will not upgrade.

**Comment by codering** [comment]
agree, yes, +1

**Comment by unimme** [comment]
agree, yes, +1

**Comment by huangyee** [comment]
+1

**Comment by ma9** [comment]
+1

**Comment by xingkong0325** [comment]
+1

**Comment by smilezhou666** [comment]
agree, yes, +1

**Comment by gaoyaqiu** [comment]
agree, yes, +1

**Comment by xuminwlt** [comment]
agree, yes, +1

**Comment by zhaosoft1982** [comment]
+1

**Comment by readazusa** [comment]
agree, yes, +1

**Comment by chenys101** [comment]
agree, yes, +1

**Comment by wu-sheng** [comment]
Hi all PMC members(@terrymanu @haocao @hanahmily @PegasusS @pottieva )

I provided you with the following resources of the biggest Java community. Spring.  Notice that even Spring didn't dare to upgrade directly. We need to be careful with that.

> As of Spring Framework 4.0, Java 8 is supported as a first-class citizen and we’ve seen some confusion in the Spring community since then. How do we manage to support Java 8 and remain compatible with Java 6 and Java 7 after all? 

See https://spring.io/blog/2015/04/03/how-spring-achieves-compatibility-with-java-6-7-and-8 

My opinion is, if Saga needs JDK 8, the question is, in the compile stage or running stage. Even in the running stage. ShardingSphere could be compiled into two components, **ss-core**, and **ss-transaction**.

**ss-core** could stay in JDK 7 for the longer term. **ss-transaction** moved into JDK 8, considering it is the new feature to everyone, right?

Of course, this is only about Sharding-Sphere's JDBC lib part. Sharding-Sphere Proxy is free to upgrade.

**Comment by jian365066744** [comment]
+1

**Comment by wujun8** [comment]
-1
Upgrading incompatible codes and dependencies is totally a disaster for original system.

**Comment by wu-sheng** [comment]
FYI @WillemJiang https://github.com/sharding-sphere/sharding-sphere/issues/1157#issuecomment-413795884 Can you confirm the info about Saga project?

**Comment by god8816** [comment]
+1

**Comment by mwylaoma** [comment]
+1

**Comment by rainwen** [comment]
+1

**Comment by w19901h** [comment]
+1

**Comment by beckhampu** [comment]
agree, yes, +1

**Comment by limingwei** [comment]
-1

**Comment by ma-xiao-guang-64** [comment]
agree, yes, +1

**Comment by ma-xiao-guang-64** [comment]
agree, yes, +1

**Comment by liuyindong** [comment]
+1

**Comment by terrymanu** [comment]
Sharding-JDBC is a framework, upgrade means all application which use JDK7 and below versions cannot support any more. 
So, just like @wu-sheng said, we need to recognize , it is really a big revolution for Sharding-JDBC, the legacy system maybe cannot run any more.

**Comment by wu-sheng** [comment]
> Sharding-JDBC is a framework, upgrade means all application which use JDK7 and below versions cannot support any more.
So, just like @wu-sheng said, we need to recognize , it is really a big revolution for Sharding-JDBC, the legacy system maybe cannot run any more.

If PMC agreed with my proposal and it is executable, I hope to cancel this vote. Just make the new `ss-transaction` and `ss-proxy` into JDK8 without harm anyone, and keep `ss-core` in JDK 7, which will make everyone happy.

**Comment by yichenghuachuang** [comment]
+1

**Comment by yichenghuachuang** [comment]
+1

**Comment by yichenghuachuang** [comment]
+1

**Comment by yichenghuachuang** [comment]
+1

**Comment by yichenghuachuang** [comment]
+1

**Comment by yichenghuachuang** [comment]
+1

**Comment by yichenghuachuang** [comment]
+1

**Comment by yichenghuachuang** [comment]
+1

**Comment by yichenghuachuang** [comment]
+1

**Comment by WillemJiang** [comment]
@wu-sheng from the experience of Spring 4.x,

> We chose not to use any Java 7 or Java 8 language features in our own codebase in order to give you the flexibility to write your Spring 4 applications for Java 6, 7 or 8. 

 I think we can consider to separate the actor module from the saga-core and let the saga-core only use the Java7 feature.

**Comment by wu-sheng** [comment]
@terrymanu @WillemJiang  How about we close this, and discuss the jdk requirement of each component in a separated issue? This vote thread burns my mailbox.🤣🤣

**Comment by terrymanu** [comment]
@wu-sheng ok, we just cancel vote now. We just do not upgrade jdk version. for sharding-sphere side, we can consider about only upgrade sharding-transaction module.
@WillemJiang it is the best solution if saga can separate the actor module from the saga-core.

**Comment by it-noob** [comment]
+1
