### ISSUE TITLE
Read and write separation, unable to force read and write db

### ISSUE THREAD

**Issue by god8816** [sharding-sphere/sharding-sphere#1160]
#英语不好在用中文描述下：在读写分离的场景下，sharding-jdbc无法强制读写主库。
#   发现下面代码，无法读到任何数据，版本：3.0M2
@Test
    public void selectByPrimaryKeyFromSlave() throws Exception{
       HintManager hintManager = HintManager.getInstance() ;
       hintManager.setMasterRouteOnly();
       hintManager.addDatabaseShardingValue("vem_order", "machine_num", 1);
		    VemOrderExample example = new VemOrderExample();
			VemOrderExample.Criteria criteria = example.createCriteria();
		    criteria.andOfficeIdEqualTo("11");
		    //criteria.andMachineNumEqualTo(1);
		    //criteria.andCreateDatetimeEqualTo(1534237519351L);
		    List<VemOrder> xx = vemOrderMapper.selectByExample(example);	
		    System.out.println("查询结构集合：：：："+xx.size());
       hintManager.close();
    }

**Comment by terrymanu** [comment]
Hello, only english can use to discuss issue.
