### ISSUE TITLE
Cannot support sub query for join table.

### ISSUE THREAD

**Issue by imyar** [sharding-sphere/sharding-sphere#1165]
有计划支持吗？
 SELECT *
        from meter_device
        LEFT JOIN res_house on res_house.device_id=meter_device.id
        LEFT JOIN res_floor on res_floor.id=res_house.floor_id
        LEFT JOIN res_unit on res_unit.id=res_floor.unit_id
        LEFT JOIN res_building on res_building.id=res_unit.building_id
        LEFT JOIN res_project on res_project.id=res_building.project_id
        LEFT JOIN res_owner on res_owner.id=res_house.owner_id
        LEFT JOIN sys_dept on sys_dept.dept_id=res_project.station_id
        left JOIN (
        SELECT meterdata.*
        from  meter_device
        CROSS JOIN(SELECT  * from meter_data
        ORDER BY read_time desc
        limit 1) as meterdata where  meterdata.meter_code=meter_device.`code`
        ) as data1 on meter_device.`code`=data1.meter_code

**Comment by terrymanu** [comment]
Hello, only english can use to discuss issue.
