### ISSUE TITLE
Cannot support sub query for join table.

### ISSUE THREAD

**Issue by imyar** [sharding-sphere/sharding-sphere#1168]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
  <sharding-jdbc-spring-boot-starter.version>3.0.0.M2</sharding-jdbc-spring-boot-starter.version>
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
SELECT *
from meter_device
LEFT JOIN res_house on res_house.device_id=meter_device.id
LEFT JOIN res_floor on res_floor.id=res_house.floor_id
LEFT JOIN res_unit on res_unit.id=res_floor.unit_id
LEFT JOIN res_building on res_building.id=res_unit.building_id
LEFT JOIN res_project on res_project.id=res_building.project_id
LEFT JOIN res_owner on res_owner.id=res_house.owner_id
LEFT JOIN sys_dept on sys_dept.dept_id=res_project.station_id
left JOIN (
SELECT meterdata.*
from meter_device
CROSS JOIN(SELECT * from meter_data
ORDER BY read_time desc
limit 1) as meterdata where meterdata.meter_code=meter_device.code
) as data1 on meter_device.code=data1.meter_code
### Actual behavior
Cannot support sub query for join table.
### Reason analyze
hi,mister zhang,do you have plan to support sub query for join table?thanks!

**Comment by terrymanu** [comment]
No plan yet. you can check supported SQL here:
http://shardingsphere.io/document/current/en/features/sharding/usage-standard/sql/
