### ISSUE TITLE
Tokenizer code make cpu full

### ISSUE THREAD

**Issue by dchack** [sharding-sphere/sharding-sphere#1169]
``Tokenizer`` make our java application cpu full. the version is current version.
see this code in 
``com.dangdang.ddframe.rdb.sharding.parsing.lexer.analyzer.Tokenizer#scanSymbol``

```java
while (null == (symbol = Symbol.literalsOf(literals))) {
            literals = input.substring(offset, offset + --length);
        }
```
if input like this:``select * from a where a.x in(?,?,?,?,?,?,?)`` and there are n elements ``?`` in this sql.
the loop code will execute ``n!`` times and make cpu full.
please check it , thanks.

**Comment by terrymanu** [comment]
we don't maintain 1.x any more, please upgrade
