### ISSUE TITLE
批量插入时sql解析错误

### ISSUE THREAD

**Issue by dyoner1** [sharding-sphere/sharding-sphere#1170]
sql:insert into patrol_station (patrol_task_id, station_id, bd_station_code,           station_name,station_gps)         values
### Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'LEFT_PAREN', actual token is 'END', literals is ''.
批量插入时按照 insert into table (x1,x2) values (x1,x2),(x1,x2); 拼装的sql,解析时失败

**Comment by terrymanu** [comment]
Hello, only english can use to discuss issue.
