### ISSUE TITLE
Adjust path tracing of sharding-opentracing

### ISSUE THREAD

**Issue by tuohai666** [sharding-sphere/sharding-sphere#1172]
- [x] Add tracing of getConnection().
- [x] Add tracing of close().
- [x] Add tracing of parse().
- [x] Remove tracing of route().
- [x] Remove tracing of merge().
- [x] Display correctly without a WebServer.
- [x] Display jdbc url in peer tag.
- [x] Vertical dimension sort by time between threads: https://github.com/apache/incubator-skywalking/issues/1657
- [x] Update component name: https://github.com/apache/incubator-skywalking/issues/1658
- [x] Support Sharding-Proxy.
- [x] Change the event mechanism to invoke-chain.
- [x] Rename OverallExecutionEvent and move to a appropriate place.
- [x] Make feature optional for Proxy by configuration.
- [x] Aggregation for sub-threads. (Need to implement in plugin.)
- [x] Use SPI to instead of guava event bus for performance issue

**Comment by tuohai666** [comment]
Topology
![1b](https://user-images.githubusercontent.com/24643893/45272260-ddb27680-b4de-11e8-97b8-99d1a3a0433b.png)

Tracing
![1a](https://user-images.githubusercontent.com/24643893/45272271-e5721b00-b4de-11e8-91ea-7f6740a0b960.png)

Detail
![1c](https://user-images.githubusercontent.com/24643893/45272277-eb67fc00-b4de-11e8-9592-dcbb2b91e54c.png)

**Comment by tuohai666** [comment]
Display jdbc url in peer tag.
![00](https://user-images.githubusercontent.com/24643893/45343234-edab8280-b5d2-11e8-9130-365e110c5fc4.png)

![01](https://user-images.githubusercontent.com/24643893/45343239-f13f0980-b5d2-11e8-8beb-a9e368e641b3.png)

![02](https://user-images.githubusercontent.com/24643893/45343249-f56b2700-b5d2-11e8-9428-72377ea61137.png)

**Comment by terrymanu** [comment]
Guava event bus's performance is really low, I just call directly instead of event bus, the performance is fast 50%.
So I just use SPI to decouple, do not use event bus on online query.

Use guava event bus:

 *Guava event bus (spend nano)*  | *SPI (spend nano)* | *Get connection(Hikari) (spend nano)* |
| -------------------------------- | --------------------------------- | ------------------- |
| 814489                                         | 63190                                             | 345827                     |

event bus is slow than get connection!

**Comment by terrymanu** [comment]
full time spend for get 2 connection and post a event:

use guava event bus:
post evert--------: ds_0---814489
get connection---: ds_0---452882
get connection---: ds_0---345827
total-------------: ds_0---2847346

post evert-----------: ds_1---792603
get connection------: ds_1---459552
get connection------: ds_1---303029
total---------------- :ds_1---2819832


use SPI:
post evert-----------: ds_0---63190
get connection------:ds_0---618804
get connection------:ds_0---469503
total----------------:ds_0---1326277

post evert-----------:ds_1---69040
get connection------:ds_1---574488
get connection------:ds_1---562666
total-----------------:ds_1---1349838
