### ISSUE TITLE
why execute time is too long than original datasource

### ISSUE THREAD

**Issue by baisijian** [sharding-sphere/sharding-sphere#1173]
Use the same simple sql,  original Datasource execute time is about 8ms per request
but, replace the datasource to Sharding jdbc, execute time will increase to 27ms per request, i loged the executing time what I found are SS only select from one of the ten tables,  SS router time is about 2ms, and SS execute time is about 2ms , what does the other 10ms time cause???

use id hash, 10 sub tables , test sql is SELECT id, name FROM i_test where id = "1"
sharding jdbc core 2.0.3
Thank you

**Comment by terrymanu** [comment]
could you explain why you close by issue so quickly that create by yourself without any reason?

**Comment by baisijian** [comment]
the question were fixed by myself, It is not issue of SS, thank you for reply.
