### ISSUE TITLE
ShardingConnection getMetaData 会去获取连接，与jdbc标准的connection 对象行为不一致

### ISSUE THREAD

**Issue by Ah39** [sharding-sphere/sharding-sphere#1179]
<version>3.0.0.M2</version> 
ShardingConnection  getMetaData 版本还是会去获取连接，这跟java.sql.connection 的是不兼容的
 https://github.com/sharding-sphere/sharding-sphere/issues/472https://github.com/sharding-sphere/sharding-sphere/issues/472
https://github.com/sharding-sphere/sharding-sphere/issues/379

![image](https://user-images.githubusercontent.com/2367243/44575353-61b9ee00-a7be-11e8-8f7e-6e19eaa339ce.png)

**Comment by Ah39** [comment]
有可能造成getMetaData  获取的连接 不能正确释放

**Comment by terrymanu** [comment]
Hello, only english for discuss issue.
