### ISSUE TITLE
ShardingConnection getMetaData  may get Connection, is diffrent from jdbc connection getMetaData behavior

### ISSUE THREAD

**Issue by Ah39** [sharding-sphere/sharding-sphere#1180]
version 3.0.0.M2 dont fix the 472, 379 
ShardingConnection getMetaData dont work right with the jdbc coonection obj, the behavior is not same 
#472
#379

**Comment by terrymanu** [comment]
Could you follow the issue template and fill necessary information?  For my understanding, this issue has already fixed at #472.
Do you really meet the case of connection leak? how to reproduce it?

**Comment by terrymanu** [comment]
No response any more, just close it.
