### ISSUE TITLE
Get connections synchronized in MEMORY_STRICTLY mode

### ISSUE THREAD

**Issue by tuohai666** [sharding-sphere/sharding-sphere#1186]
In MEMORY_STRICTLY mode to avoid dead lock in connection pool, we must meet the condition:
**ds.maximumPoolSize >= acceptor.size * ds.table_count.**

If we get all connections needed synchronized between queries, we just need to meet the condition:
**ds.maximumPoolSize >= ds.table_count.**

According to the performance test, there's little degrade of the QPS.

**Comment by terrymanu** [comment]
fixed at 3.0.0.M3
