### ISSUE TITLE
A problem encountered in ORCHESTRATION

### ISSUE THREAD

**Issue by villainess-y** [sharding-sphere/sharding-sphere#1194]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
3.0.0.M2
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
JDBC
### Expected behavior
Is there a way in shardingsphere to change the rules or data sources that have been persisted in zookeeper, or only by overwrite = true when creating the OrchestrationConfiguration object?

**Comment by terrymanu** [comment]
modify configuration from zookeeper or etcd directly
