### ISSUE TITLE
A problem when using transaction

### ISSUE THREAD

**Issue by villainess-y** [sharding-sphere/sharding-sphere#1204]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
3.0.0.M2

### Which project do you using? Sharding-JDBC or Sharding-Proxy?
JDBC
### Expected behavior
Successfully created transaction log table
### Actual behavior
org.postgresql.util.PSQLException:
CREATE TABLE IF NOT EXISTS `transaction_log` (`id` VARCHAR(40) NOT NULL, `transaction_type` VARCHAR(30) NOT NULL, `data_source` VARCHAR(255) NOT NULL, `sql` TEXT NOT NULL, `parameters` TEXT NOT NULL, `creation_time` LONG NOT NULL, `async_delivery_try_times` INT NOT NULL DEFAULT 0, PRIMARY KEY (`id`));
### Reason analyze
 transactionManager.init().createtable();
PostgreSQL does not recognize quotes

**Comment by terrymanu** [comment]
What is the original SQL? I don't see any quotes in your SQL.

**Comment by villainess-y** [comment]
You didn't see the quotes because I forgot the markdown syntax rules to recognize the quotes

![image](https://user-images.githubusercontent.com/42766137/44824430-0feaeb00-ac38-11e8-8dd5-e8e29dc03085.png)

There is a create table statement in this function
![image](https://user-images.githubusercontent.com/42766137/44824479-5fc9b200-ac38-11e8-8956-1f547a17fc84.png)

There is the database log information
![image](https://user-images.githubusercontent.com/42766137/44824563-d9fa3680-ac38-11e8-8b4b-5a94ead59811.png)

**Comment by terrymanu** [comment]
BASE transaction will refactor in future, just reference #1190
So I just close this issue for now.
