### ISSUE TITLE
Sharding configuration is not configured locally, and sharding configuration is fully obtained from the reg center。

### ISSUE THREAD

**Issue by siusn** [sharding-sphere/sharding-sphere#1206]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?

2.0.3

### Which project do you using? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC

### Expected behavior

Sharding configuration is not configured locally, and sharding configuration is fully obtained from the reg center。

### Actual behavior

There must be an initial sharding configuration locally

**Comment by terrymanu** [comment]
duplicate with #698
