### ISSUE TITLE
when to support global  table

### ISSUE THREAD

**Issue by houzhanshanlinzhou** [sharding-sphere/sharding-sphere#1207]
什么时候支持类似mycat 的全局（global table）表，比如 一些公用的表，或者字典能够在每个库中都生成一份，目前sharding-jdbc 的实现方式是设置一个默认的database, 但我觉得用起来还是不方便，不能够直接join 获取。支持全局表内部join这个功能我觉得太重要了，但是我目前为止没有找到类似的示例。不知道是已经支持了我不会设置，还是目前没有相关的功能，麻烦亮哥看下

**Comment by terrymanu** [comment]
Hello, only english for discuss issue.
