### ISSUE TITLE
After the annotation @Transactional, the data update seems to be automatically rolled back.

### ISSUE THREAD

**Issue by shdreams** [sharding-sphere/sharding-sphere#1209]
After the annotation @Transactional, the data update seems to be automatically rolled back.

I found the table "AUTO_INCREMENT" will change after INSERT.

The version of sharding-sphere: 3.0.0.m2

Thanks!

**Comment by cherrylzhao** [comment]
same with issue #1116, will be resolve in 3.0.0.m3
