### ISSUE TITLE
the transaction has a serious bug

### ISSUE THREAD

**Issue by houzhanshanlinzhou** [sharding-sphere/sharding-sphere#1224]
if the primary key is duplicate，I find the default transaction can commit and has no error in 

    <dependency>
      <groupId>io.shardingsphere</groupId>
      <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
      <version>3.0.0.M2</version>
    </dependency>

it is not right. but in the 
<dependency>
      <groupId>io.shardingjdbc</groupId>
      <artifactId>sharding-jdbc-core-spring-boot-starter</artifactId>
      <version>2.0.3</version>
 </dependency>

the sharding-jdbc can throw exception  and can rollback, the transcation is right.
please check it .

**Comment by cherrylzhao** [comment]
same with #1116, will be resolved in 3.0.0.m3
