### ISSUE TITLE
do not support distinct

### ISSUE THREAD

**Issue by yangzhou322** [sharding-sphere/sharding-sphere#1231]
some tables dont want sharding and used distinct in the sql，but it didnt works
log errors "Not supported token 'DISTINCT'"
how to resolve the problem

**Comment by terrymanu** [comment]
We have no plan to support that now.
http://shardingsphere.io/document/current/en/features/sharding/usage-standard/sql/

**Comment by yangzhou322** [comment]
那些不想分的表也不能使用DISTINCT，彻底凉了

**Comment by terrymanu** [comment]
Hello, only english for discuss issue.

**Comment by xj198806** [comment]
why table PreciseShardingAlgorithm can not use distinct , why can not decided by users
