### ISSUE TITLE
cannot find table rule and defualt 为了简化配置 ,默认所有的表都加入配置规则 By default, all tables are added to configuration rules. 

### ISSUE THREAD

**Issue by gongandkai** [sharding-sphere/sharding-sphere#1235]
###Which version of Sharding-Sphere do you using?

3.0.0.M2

###Which project do you using? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC  

###Expected behavior

By default, all tables are added to configuration rules. 为了简化配置 ,默认所有的表都加入配置规则

###Actual behavior

need set defaultDataSource  不加配置会提示 cannot find table rule and defualt ...  当然配置默认数据源 也是可以的，但是如果没有默认是否可以支持

**Comment by terrymanu** [comment]
Hello, only english for discuss issue.
