### ISSUE TITLE
Spring @Transaction

### ISSUE THREAD

**Issue by yangzhou322** [sharding-sphere/sharding-sphere#1236]
when  add @Transaction on a method,i get an error 
TransactionListener.listen NullPointerException

when delete the annotation,it worked

why? and how to solve the problem

**Comment by terrymanu** [comment]
duplicated with #1116.
This is the ninth duplicated issue on this problem. Cloud you check issue list before you submit a new issue?

**Comment by yangzhou322** [comment]
OK, tks
