### ISSUE TITLE
Support local transaction on Sharding-Proxy

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1238]

**Comment by cherrylzhao** [comment]
currently sharding-proxy have integrated with XA, and our local transaction is quite same with XA.
both of them need to hold the routed sharing connection untill commit command is triggered.
and performance improvement for local transaction is limit, so we decide to close this issue.

**Comment by cherrylzhao** [comment]
consider about refactor sharing-proxy, making local transaction connection binding with specified channel, in order to get all associate connections in commit phase.

**Comment by cherrylzhao** [comment]
* [ ] refactor backendConnection
 * [ ] refactor proxy transaction model
