### ISSUE TITLE
New TCL parse engine

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1239]

**Comment by codefairy08** [comment]
- [ ] 
      Develop mysql  TCL grammar
- [ ] 
      Develop postgre  TCL grammar    
- [ ] 
      Develop sqlserver  TCL grammar  
- [ ] 
      Develop oracle  TCL grammar  

- [ ] 
      Add TCL statement visitor

**Comment by codefairy08** [comment]
- [ ] 
      Develop mysql TCL grammar
- [ ] 
     Develop postgre TCL grammar
- [ ] 
     Develop sqlserver TCL grammar
- [ ] 
     Develop oracle TCL grammar
- [ ] 
    Add TCL statement visitor

**Comment by codefairy08** [comment]
- 

- [ ] 
   Develop TCL grammar

- [ ] 

  Add TCL statement visitor

**Comment by codefairy08** [comment]
- [ ] Develop TCL grammar

**Comment by codefairy08** [comment]
- [ ] Develop TCL grammar
      
- [ ] Add TCL statement visitor

**Comment by terrymanu** [comment]
finished at 3.0.1

**Comment by codefairy08** [comment]
grammar file complete
