### ISSUE TITLE
regular expression of MySQLDataSourceMetaData   not match hyphen （-）

### ISSUE THREAD

**Issue by tr276913271** [sharding-sphere/sharding-sphere#1241]
io.shardingsphere.core.metadata.datasource.dialect.MySQLDataSourceMetaData  
line: 51

### Which version of Sharding-Sphere do you using?
version: m3
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
url:jdbc:mysql://xxxxxxx:3307/a-b?useUnicode=true
Expected  match ：a-b
### Actual behavior
only match : a

m2 is ok

**Comment by terrymanu** [comment]
fixed at 3.0.0.M4

**Comment by terrymanu** [comment]
Database name should support `-`
