### ISSUE TITLE
Sharding-Sphere sharding rule

### ISSUE THREAD

**Issue by joey168** [sharding-sphere/sharding-sphere#1242]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

Before submit a new issue, please check existed issue first, to make sure your issue is not a duplicated one.

### Which version of Sharding-Sphere do you using?
3.0.0M3
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
there are two data sources ds-2017 and ds-2018 use year sharding database
very data sources use month sharding tabale table1..12
using create_date field in table sharding rule
query 2017-08-01 to 2018-09-01 data

Sharding-Sphere-SQL.log
select * from ds-2017.table1..12 where create_date between ? and ?
select * from ds-2018.table1..12 where create_date between ? and ?
way not
select * from ds-2017.table8..12 where create_date between ? and ?
select * from ds-2018.table1..09 where create_date between ? and ?

It's my sharding rule problem?

if database sharding rule and table sharding rule can unified processing, use the same doBetweenSharding() method then can return the specified database corresponds to the specified table
like ds-2017 contain table8..table12  ds-2018 contain table1..09
Map<String, List<String>> result = [{ds2017, [table8,table9....,table12]}, {ds2018, [table1.....,table9]}]

please help answer this question thank you!

**Comment by terrymanu** [comment]
Sorry, I cannot understand what are you saying?

Cloud you organize your language again?

**Comment by terrymanu** [comment]
Some hint:
1. what' mean of unified processing?
2. I cannot understand ho do you config it, maybe you can have a look on example first

**Comment by joey168** [comment]
the use of cross year queries will involve full table query, although it does not affect query results in the end, but it consumes many meaningless query
1.like query 2017-08-01 to 2018-09-01 data
2.database sharding rule return ds-2017 and ds-2018
3.table sharding rule return table1 to table12

actual query statement
select * from ds-2017.table1 where create_date between 2017-08-01 and 2018-09-01
....
select * from ds-2017.table12 where create_date between 2017-08-01 and 2018-09-01

select * from ds-2018.table1 where create_date between 2017-08-01 and 2018-09-01
....
select * from ds-2018.table12 where create_date between 2017-08-01 and 2018-09-01

should return
select * from ds-2017.table8 where create_date between 2017-08-01 and 2018-09-01
....
select * from ds-2017.table12 where create_date between 2017-08-01 and 2018-09-01

select * from ds-2018.table1 where create_date between 2017-08-01 and 2018-09-01
....
select * from ds-2018.table9 where create_date between 2017-08-01 and 2018-09-01

can an algorithm be added to control the corresponding relationship between the data source and the table at the same time?

like return:
public String doSharding(Collection<String> collection, PreciseShardingValue<Date> preciseShardingValue) {
        Map<String, List> result = [{ds2017, [table8....,table12]}, {ds2018, [table1.....,table9]}]
        return result;
}

I don't know if I have made myself clear, thank you!

**Comment by terrymanu** [comment]
The sharding algorithm is written by yourself, you can control it return correct actual tables as you want.

**Comment by joey168** [comment]
thank you for the answer!
my RangeShardingAlgorithm config It's effective
you can provide database sharding by year and table sharding by month algorithm demo?
thank you very much!

**Comment by joey168** [comment]
the problem is cross year query are not normal,cross year the tables of all data sources will be returned uniformly.

**Comment by terrymanu** [comment]
Could you provide your sharding config?

**Comment by terrymanu** [comment]
What is the content of `com.dayi35.core.spot.common.sharding.algorithm.SingleKeyDatabaseDateRangeShardingAlgorithm`?

**Comment by joey168** [comment]
thank you for the answer!

databalse algorithm:

@Override
    public Collection<String> doSharding(Collection<String> collection, RangeShardingValue<Date> rangeShardingValue) {
        Collection<String> result = new LinkedHashSet<>(collection.size());
        DateFormat sdf = new SimpleDateFormat(datePattern);
        Range<Date> ranges = rangeShardingValue.getValueRange();
        Date startTime = ranges.lowerEndpoint();
        Date endTime = ranges.upperEndpoint();

        while (startTime.getTime() <= endTime.getTime()) {
            //判断是否为当前年份，如果为当前年份则返回默认数据源
            if(new DateTime().getYear() == new DateTime(startTime).getYear()) {
                result.add(defaultDateSource);
            } else {
                result.add(namePrefix + separator + sdf.format(startTime));
            }
            //加上一年后重新设置起始时间
            startTime = new DateTime(startTime).plusYears(1).monthOfYear().withMinimumValue().dayOfMonth().withMinimumValue().secondOfDay().withMinimumValue().toDate();
        }

        if(CollectionUtils.isEmpty(result)) {
            throw new UnsupportedOperationException();
        }

        return result;
    }

table algorithm:
@Override
    public Collection<String> doSharding(Collection<String> collection, RangeShardingValue<Date> rangeShardingValue) {
        Collection<String> result = new LinkedHashSet<>(collection.size());
        Range<Date> ranges = rangeShardingValue.getValueRange();
        Date startTime = ranges.lowerEndpoint();
        Date endTime = ranges.upperEndpoint();

        while (startTime.getTime() <= endTime.getTime()) {
            result.add(rangeShardingValue.getLogicTableName() + separator + new DateTime(startTime).toString(datePattern));
            //加上一个月后重新设置起始时间
            startTime = new DateTime(startTime).plusMonths(1).dayOfMonth().withMinimumValue().secondOfDay().withMinimumValue().toDate();
        }

        if(CollectionUtils.isEmpty(result)) {
            throw new UnsupportedOperationException();
        }

        return result;
    }

**Comment by terrymanu** [comment]
you sharding algorithm is pretty strange, what' mean of:

```java
startTime = new DateTime(startTime).plusMonths(1).dayOfMonth().withMinimumValue().secondOfDay().withMinimumValue().toDate();
```

you can try to debug what is your input param of rangeShardingValue, and why they return the result of table name that your don't needed.

The useless actual table names are returning by yourself via table algorithm.

**Comment by joey168** [comment]
rangeShardingValue is: begin date is 2017-08-01 end date is 2018-09-01
because my table is divided by month, so my loop determines the name of the table that needs to be returned, Is there any problem with my place?
thank you very much!

**Comment by terrymanu** [comment]
Research why `create_date between 2017-08-01 and 2018-09-01` return `table12` and `table1`?

**Comment by terrymanu** [comment]
OK, I finally understand your point.

It does not support this feature when your use same column to sharding datasources and tables.

Because sharding algorithm of databases and tables are unrelated. If you want let table sharding result related data source sharding result, we have to change the API of sharding algorithm, merge table sharding algorithm and data source sharding algorithm as one, and return data node list. 

It is hard to understand for end users, so we still use simple one to make config easy, but maybe cause more useless database query.

**Comment by joey168** [comment]
thank you for the answer！：）
