### ISSUE TITLE
inline  express  t_report_$->{create_time.format('yyyyMM')} work well  on INSERT sql, but always  return  null on SELECT  sql 

### ISSUE THREAD

**Issue by youbeiwuhuan** [sharding-sphere/sharding-sphere#1244]
inline  express  t_report_$->{create_time.format('yyyyMM')} work well  on INSERT sql, but always  return  null on SELECT  sql .

### Which version of Sharding-Sphere do you using?
sharding-jdbc  3.0.0.M1
### Expected behavior
my config is 
sharding.jdbc.config.sharding.tables.t_report.key-generator-column-name=id
sharding.jdbc.config.sharding.tables.t_report.dynamic=true
sharding.jdbc.config.sharding.tables.t_report.table-strategy.complex.sharding-columns=create_time
sharding.jdbc.config.sharding.tables.t_report.table-strategy.complex.algorithm-expression=t_report$->{create_time.format('yyyyMM')}

I want to  insert  record to table  t_report201809,and it work well.
but when I   execute    sql    
select * from t_report where  create_time = ?  
it always throw exception  whatever the parameter is .
 com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'sharding_jdbc.t_report' doesn't exist

**Comment by terrymanu** [comment]
Cloud you provide reproduce codes on github and send the link here?

**Comment by terrymanu** [comment]
No response anymore, just close it.
