### ISSUE TITLE
Unable to find property 'shardingRule' on class: io.shardingjdbc.core.yaml.masterslave.YamlMasterSlaveConfiguration

### ISSUE THREAD

**Issue by cherrishccl** [sharding-sphere/sharding-sphere#1245]
Unable to find property 'shardingRule' on class: io.shardingjdbc.core.yaml.masterslave.YamlMasterSlaveConfiguration

**Comment by cherrishccl** [comment]
The reason of that is the version not matched

**Comment by terrymanu** [comment]
So, can you close the issue?
