### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by cherrishccl** [sharding-sphere/sharding-sphere#1247]
I have some questions about the configurations,can someone give me the answers,please.
My Project: Spring-boot2.0.4, JPA, MySql
1. In this configuration "sharding.jdbc.datasource.names=ds0,ds1", Both of the names are **real** database-names, are them?
2. When I set the names as this "sharding.jdbc.datasource.names=ds_0,ds_1",  It shows me some errors: "Configuration property name 'sharding.jdbc.datasource.ds_0' is not valid", also give me some advice：”Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter“， I did this, It showed mysql error:"check the manual that corresponds to your MySQL server version for the right syntax to use near '-0.my_test_1 mytest0_ where test0_.fid=1'".
3. Can I name the database with characters "_" like this: "test_db0" when use sharding-jdbc?

**Comment by terrymanu** [comment]
All of those questions you can try it first.
Practice is the best experience.

**Comment by terrymanu** [comment]
If the answer is enough, cloud you close this issue?

**Comment by cherrishccl** [comment]
yes

**Comment by jaychang9** [comment]
How to resolve the question 2 ?
