### ISSUE TITLE
sharding condition exist not in SQL

### ISSUE THREAD

**Issue by haroldjiang** [sharding-sphere/sharding-sphere#1251]
when use hint route In some special scenario that sharding condition exist at outside logic, not in SQL.
dose sharding-jdbc or sharding-proxy will add the sharding key into the sql as a where condition or just route to the destinate database without add the sharding key into the sql as a  where condition?

**Comment by terrymanu** [comment]
For hint, it will skip parser engine, so don't add  sharding key with condition.

**Comment by haroldjiang** [comment]
we have a singular system need to transport to multi-tenant saas by combine some tenant's schema into one . but all of sqls have no tenantid within it.even though we can use sharding-proxy to do the database route,after sql have been sent to the specific destinate table of  database schema,it will return all tenant's data in that  table(we are using mysql)

**Comment by terrymanu** [comment]
you mean all tenants maybe save in the same table, and no tenant_id store in tables?

**Comment by haroldjiang** [comment]
yes，all tenants maybe save in the same table, and no tenant_id store in tables，has no tenant_id field in  query SQL.

**Comment by haroldjiang** [comment]
yes,all tenants  data save in the same table,no tenant_id store in tables and has no tenant_id field in your query SQL.

**Comment by haroldjiang** [comment]
for now,all tenants have their own database schema and tables with same table name.
no tenant_id store in tables and has no tenant_id field in your query SQL.

**Comment by terrymanu** [comment]
I need to confirm: 
What is your question? 
Does hint support your scenario enough? 
If not, what is your expectation?

**Comment by terrymanu** [comment]
No response more than 7 days, just close it.
