### ISSUE TITLE
ShardingDataSource  method “renew” is delete ,What method is used instead?

### ISSUE THREAD

**Issue by zhanyao** [sharding-sphere/sharding-sphere#1260]
### Which version of Sharding-Sphere do you using?
3.0.0.M3
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

**Comment by terrymanu** [comment]
`ShardingDataSource` is not a public API, the public API is only at api package. 
So we may change internal codes anytime.
