### ISSUE TITLE
M3版本最基本的sql无法执行

### ISSUE THREAD

**Issue by chrisHao** [sharding-sphere/sharding-sphere#1262]
select appid from wx_public_account.wx_public_account_service limit 1  

异常：
private void appendRest(final SQLBuilder sqlBuilder, final int count, final List<SQLToken> sqlTokens, final int beginPosition) {
        int endPosition = sqlTokens.size() - 1 == count ? originalSQL.length() : sqlTokens.get(count + 1).getBeginPosition();
        sqlBuilder.appendLiterals(originalSQL.substring(beginPosition, endPosition));
    }

这里数组越界了
最基本的功能无法保证发什么版本

**Comment by terrymanu** [comment]
Hello, only english for discuss issue.

**Comment by terrymanu** [comment]
Hello, we prefer discuss friendly. 
I don't think question `Did you test before commited ?` is friend enough.

But I still paste the document here: http://shardingsphere.io/document/current/en/features/sharding/usage-standard/sql/ 

please read them before submit issue, thank you
