### ISSUE TITLE
How to implement multi-tenancy?

### ISSUE THREAD

**Issue by gatspy** [sharding-sphere/sharding-sphere#1267]
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
`Sharding-JDBC`

### Expected behavior
in  `saas` project, each tenant uses a separate database.
How to use `sharding-jdbc` to manage data sources, or other solutions?
Technology stack now in use:
```
spring boot
spring cloud(config, gateway..)
consul
```

**Comment by terrymanu** [comment]
If you want use sharding-sphere to implement multi-tenancy, there are lots of way to do. 
But how to implement a saas is a big topic, and it out of range of sharding-sphere.
