### ISSUE TITLE
parameter count error

### ISSUE THREAD

**Issue by monkeylite** [sharding-sphere/sharding-sphere#1271]
Parameter count error as Bold below:

version:3.0.0.M3

22:19:02.655 [INFO] Sharding-Sphere-SQL [71] - SQLStatement: InsertStatement(super=DMLStatement(super=AbstractSQLStatement(type=DML, tables=Tables(tables=[Table(name=t_balance, alias=Optional.absent())]), conditions=Conditions(orCondition=OrCondition(andConditions=[AndCondition(conditions=[Condition(column=Column(name=user_id, tableName=t_balance), operator=EQUAL, positionValueMap={}, positionIndexMap={0=0})])])), sqlTokens=[TableToken(beginPosition=12, skippedSchemaNameLength=0, originalLiterals=t_balance), io.shardingsphere.core.parsing.parser.token.InsertValuesToken@7a96d60e], parametersIndex=4)), columns=[Column(name=user_id, tableName=t_balance), Column(name=currency, tableName=t_balance), Column(name=available, tableName=t_balance), Column(name=ordering, tableName=t_balance)], generatedKeyConditions=[], insertValues=InsertValues(insertValues=**[InsertValue(type=VALUES, expression=(?, ?, ?, ?), parametersCount=4)]**), columnsListLastPosition=60, generateKeyColumnIndex=-1, insertValuesListLastPosition=80)

22:19:02.655 [INFO] Sharding-Sphere-SQL [71] - Actual SQL: node0 ::: INSERT INTO t_balance(user_id, currency, available, ordering) VALUES**(?, ?, ?, ?)** ON DUPLICATE KEY UPDATE available = **available + ?**, ordering = **ordering + ?** ::: [[198110, USD, 11, -12]]

**Comment by terrymanu** [comment]
duplicate with #1066
