### ISSUE TITLE
sharding.jdbc.datasource.names only support datasource names separated by comma

### ISSUE THREAD

**Issue by feelwing1314** [sharding-sphere/sharding-sphere#1285]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

No.

### Describe the feature you would like.

hope the sharding.jdbc.datasource.names in application.properties can support expression like ds,ds_${0..3}。
but， the SpringBootConfiguration show me that only support datasource names separated by comma. if tens of names， the conf is unfriendly at all.

**Comment by wangyu1221** [comment]
Hope to support formmated names like ds_00,ds_01,...,ds_15, rather than ds_0,ds_1,...,ds_15

**Comment by boycai** [comment]
I also encountered this problem. How can I solve it?

**Comment by terrymanu** [comment]
@boycai hi, we will release this feature at 3.1.0.M1

**Comment by terrymanu** [comment]
@boycai sorry, not for 3.1.0.M1, it should be include at 3.1.0

**Comment by terrymanu** [comment]
duplicate with #1686
