### ISSUE TITLE
How to deal that One of Slaves is down?

### ISSUE THREAD

**Issue by wuyuleiliu** [sharding-sphere/sharding-sphere#1287]
One of Slaves is down,then that the service query the slave is error.how to deal it?

Who knows some solution？

**Comment by terrymanu** [comment]
you can disable the crashed slave data source via reg center

**Comment by wuyuleiliu** [comment]
That's one way，but it need to combine with other service(maybe need written by myself ) to disable the crashed slave data source automatically.
I find that it can use nginx to implement load balancing of slave data sources,what do you think?It works?

**Comment by terrymanu** [comment]
Sharding-Sphere is provide solution for database, it can be a component of distribute env, and you can use other project to collaborate together. But talk whole solution is out of range for Sharding-Sphere.
So I just close this issue.

**Comment by tony1991** [comment]
@wuyuleiliu could you tell me how to deal it finally?

**Comment by wuyuleiliu** [comment]
@tony1991 That's not what it deal with it,you can find some information about it and terrymanu also said.
You should consider it as a whole,and the database itself has its own cluster,That's guaranteed not to crash.
