### ISSUE TITLE
[main-SendThread(127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)

### ISSUE THREAD

**Issue by XWY2018** [sharding-sphere/sharding-sphere#1292]
[INFO ] 16:02:19.632 [main] o.a.c.f.imps.CuratorFrameworkImpl - Starting
[INFO ] 16:02:19.649 [main] org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
[INFO ] 16:02:19.650 [main] org.apache.zookeeper.ZooKeeper - Client environment:host.name=XUWEN
[INFO ] 16:02:19.650 [main] org.apache.zookeeper.ZooKeeper - Client environment:**java.version=1.8.0_131**
[INFO ] 16:02:19.651 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Oracle Corporation
[INFO ] 16:02:19.654 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.home=C:\Program Files\Java\jdk1.8.0_131\jre
[INFO ] 16:02:19.656 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=..;..\conf;..\lib\atomikos-util-4.0.4.jar;...
[INFO ] 16:02:19.657 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=C:\Program Files\Java\jdk1.8.0_131\bin;C:\Program Files\Java\jre1.8.0_131\bin;...
[INFO ] 16:02:19.658 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=d:\Temp\
[INFO ] 16:02:19.658 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
[INFO ] 16:02:19.659 [main] org.apache.zookeeper.ZooKeeper - Client environment:os.name=**Windows 10**
[INFO ] 16:02:19.659 [main] org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
[INFO ] 16:02:19.660 [main] org.apache.zookeeper.ZooKeeper - Client environment:os.version=10.0
[INFO ] 16:02:19.663 [main] org.apache.zookeeper.ZooKeeper - Client environment:user.name=Administrator
[INFO ] 16:02:19.663 [main] org.apache.zookeeper.ZooKeeper - Client environment:user.home=C:\Users\Administrator
[INFO ] 16:02:19.664 [main] org.apache.zookeeper.ZooKeeper - Client environment:user.dir=D:\0Work\Sharding\**sharding-sphere-dev-3.1.0**\sharding-sphere-dev-3.1.0\sharding-proxy\target\classes\bin
[INFO ] 16:02:19.665 [main] org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=localhost:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@69b2283a
[INFO ] 16:02:20.216 [main-SendThread(0:0:0:0:0:0:0:1:2181)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server 0:0:0:0:0:0:0:1/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ] 16:02:21.224 [main-SendThread(0:0:0:0:0:0:0:1:2181)] org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
[INFO ] 16:02:21.327 [main-SendThread(127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ] 16:02:22.329 [main-SendThread(127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar:3.4.6-1569965]

java.version=1.8.0_131
Windows 10
sharding-proxy of sharding-sphere-dev-3.1.0 
error：org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

**Comment by terrymanu** [comment]
What is you proposal to submit this issue? the log is for zookeeper, I don't think it has any relationship with Sharding-Sphere.
By the way, the branch sharding-sphere-dev-3.1.0 is still in dev mode, we do not accept any bug on this branch
