### ISSUE TITLE
Sql-Server exception : The URL of JDBC is not supported. 

### ISSUE THREAD

**Issue by mzmzo** [sharding-sphere/sharding-sphere#1307]
spring-boot 1.5.6.RELEASE
sharding-3.0.0.M3
sqlServer 2012
sqljdbc4 4.0

when I use sharding-3.0.0.M1，everything works fine
my configuration is like this sharding.jdbc.datasource.ds_0.url=jdbc:sqlserver://dev.database.chinacloudapi.cn;database=sharding;loginTimeout=30;sendStringParametersAsUnicode=false

but when I upgrade to M3, the connection fails.
report this error : The URL of JDBC is not supported.

**Comment by tristaZero** [comment]
Hi, @mzmzo . Why don't you use this one ?
sharding.jdbc.datasource.ds_0.url=jdbc:sqlserver://dev.database.chinacloudapi.cn;`databaseName`=sharding;

Please refer to 
https://docs.microsoft.com/en-us/sql/connect/jdbc/connection-url-sample?view=sql-server-2017
