### ISSUE TITLE
How to write expression of formatted datasource id?

### ISSUE THREAD

**Issue by wangyu1221** [sharding-sphere/sharding-sphere#1313]
My datasource are named from 'ds0000' to 'ds0015', is there only one way for xml like this? 
Or any other batter suggestions?

`<sharding:sharding-rule data-source-names="ds000$->{0..9},ds00$->{10..15}">`
`actual-data-nodes="ds000$->{0..9}.user,ds00$->{10..15}.user"`

**Comment by terrymanu** [comment]
duplicate with #1285
