### ISSUE TITLE
Use PreciseShardingAlgorithm and spring-data-jpa update error

### ISSUE THREAD

**Issue by mzmzo** [sharding-sphere/sharding-sphere#1315]
## Modifying an existing data but added a new one
spring-boot 1.5.6.RELEASE
sharding-3.0.0.M4
sqlServer 2012
sqljdbc4 4.0

I customized the algorithm implementation from PreciseShardingAlgorithm.
then, when I am ready to modify an existing data, I found that it added a new piece of data.
everything is fine before I customized the algorithm.

## About a bug that was previously closed
Now I use mysql test, because [#1307](https://github.com/sharding-sphere/sharding-sphere/issues/1307) does not solve the sqlServer connection problem
because the url that method SQLServerDataSourceMetaData gets like this
jdbc:sqlserver://dev.database.chinacloudapi.cn:1433;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustServerCertificate=false;sendStringParametersAsUnicode=false;selectMethod=direct;responseBuffering=adaptive;packetSize=8000;multiSubnetFailover=false;loginTimeout=30;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=sharding;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite;
it doesn't match

This is my github address [question](https://github.com/mzmzo/sharding-example)

**Comment by tristaZero** [comment]
@mzmzo Thanks for your issue, we fix it in [#1336](https://github.com/sharding-sphere/sharding-sphere/pull/1336). Please use 3.0.0.M5
