### ISSUE TITLE
orchestration configuration question

### ISSUE THREAD

**Issue by tblueprint** [sharding-sphere/sharding-sphere#1319]
If I don't rely on orchestration, the application starts to report an error, and the log shows Cannot evaluate embedded database driver class for database type NONE. So I rely on orchestration, but I reported another error, the log shows Missing the type of datasource configuration in orchestration configuration.

So how should I configure it?

**Comment by tristaZero** [comment]
@tblueprint Hi, this problem has been fixed, the issue is [#1311](https://github.com/sharding-sphere/sharding-sphere/pull/1311/files).
Please use the latest version of sharding-sphere-example to run.
