### ISSUE TITLE
sharding-jdbc多线程问题

### ISSUE THREAD

**Issue by kuhn-he** [sharding-sphere/sharding-sphere#1333]
sharding-jdbc是否支持多线程查询？如果支持在哪里开启？

sharding.jdbc.config.sharding.props.executor.size
以上配置项貌似没有作用，效率没有提升

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
For English only, other languages will not accept.
