### ISSUE TITLE
sharding-jdbc is supported multiple thread？

### ISSUE THREAD

**Issue by kuhn-he** [sharding-sphere/sharding-sphere#1334]
sharding-jdbc is supported multiple thread？how can I enabled?

'sharding.jdbc.config.sharding.props.executor.size' is not effect. can you help me?

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by kuhn-he** [comment]
multiple threads means one request multiple datasource connections or one connection multiple work threads for execute SQL ? thks

**Comment by terrymanu** [comment]
you may read document first:
http://shardingsphere.io/document/current/cn/features/sharding/principle/execute/
