### ISSUE TITLE
新版本继承boot后报错ORA-01424: 转义符之后字符缺失或非法

### ISSUE THREAD

**Issue by qsdavid** [sharding-sphere/sharding-sphere#1344]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

使用版本：3.0.0.M4
使用项目： sharding-jdbc-core
spring boot 框架下，启动后，数据源start comlete后，长时间卡住后报错，ora-1424，之前使用dangdang下的1.5.4老版本没啥问题，切换新版本配置模式后就无法启动了，未分库,分表策略如下：
result.setLogicTable("cust_custinfo");
result.setActualDataNodes("testorder.cust_custinfo_${0..4}");
希望有大神可以解答一下有没有碰到相同问题的

**Comment by terrymanu** [comment]
For English only, other languages will not accept.
