### ISSUE TITLE
Do you have any documentation about sharding-orchestration?

### ISSUE THREAD

**Issue by weichaocst** [sharding-sphere/sharding-sphere#1346]
I am very puzzled about sharding-orchestration now. I have not found any documents on GitHub.
Can you provide a document about sharding-orchestration on GitHub?
You've been working very hard.

**Comment by tristaZero** [comment]
@weichaocst Hi, please refer to the orchestration chapter on our official website [orchestrattion](http://shardingsphere.io/document/current/cn/features/orchestration/orchestration/).

**Comment by terrymanu** [comment]
Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).
