### ISSUE TITLE
性能和单库差距很大，该如何配置呢

### ISSUE THREAD

**Issue by helloqhx** [sharding-sphere/sharding-sphere#1352]
实验所用的机器：4台8核16G的阿里云机器。
mysql版本：8.0.12
配置：3台作为mysql的服务器，一台是客户端，使用了sharding-jdbc。每台机器就一个数据库，也就是只分库，不分表。

测试插入性能：单台吞吐可以达到1w以上，但是使用了sharding-jdbc，三台合起来只有6k，而且延迟也很大。测试时，使用了8个线程一起插入，并且共享同一个datasource
下面是我的代码片段：
ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration(); TableRuleConfiguration tableRuleConfig = new TableRuleConfiguration(); tableRuleConfig.setLogicTable(TABLE_NAME);

shardingRuleConfig.getTableRuleConfigs().add(tableRuleConfig); shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig( new InlineShardingStrategyConfiguration(HASH_KEY, "ds_${" + HASH_KEY + " % " + index + "}"));

ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, new HashMap<>(), new Properties());

不知道，是不是我配置有问题？请指教

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
