### ISSUE TITLE
SQL parsing error

### ISSUE THREAD

**Issue by EthanKk** [sharding-sphere/sharding-sphere#1354]
A SQL like this will trigger a parsing exception throwed。
SQL：
      SELECT * from TableName E where ColumnName1 = 1 and ColumnName2 = (SELECT max(ColumnName2) from TableName E2 where E2.ColumnName1 = 1)

Exception：
      io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'MAX', literals is 'max'.

**Comment by terrymanu** [comment]
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/cn/features/sharding/usage-standard/sql/).
