### ISSUE TITLE
Add the init() and destroy() to the XA Transaction Manager SPI

### ISSUE THREAD

**Issue by zhfeng** [sharding-sphere/sharding-sphere#1357]
## Feature Request
It is very import to be able to recovery the XA transaction when the TM crash and restart again. There is a good article to explain this [Narayana periodic recovery of XA transactions](http://jbossts.blogspot.com/2018/01/narayana-periodic-recovery-of-xa.html)

So it could be useful if we can provide the registration method to add the XAResource to the recovery system which would be used during the recovering to get the connection with the databases. And this could be done in the wrapDataSource() and we need to the following methods to help us.

The init() method could be used to do something needs initialization, just such like start the recovery service

The destroy() method could be used to release the resource and stop the service thread which could be helpful when doing the graceful shutdown. 

### Is your feature request related to a problem?
Not yet.

### Describe the feature you would like.
I propose to add in https://github.com/sharding-sphere/sharding-sphere/blob/dev/sharding-transaction/src/main/java/io/shardingsphere/transaction/manager/xa/XATransactionManager.java 

```
void init();
void destroy();
```

**Comment by cherrylzhao** [comment]
hi, it seems that your linked article can't be access.
I wandered that where should we invoke this register method, in sharding-sphere side or inside the transaction manager.

**Comment by zhfeng** [comment]
I think this is invoked by the sharding-sphere when initialize the TM and we could just start a recovery manager process running in the background. And the sharding-sphere need to pass all the XAResource for the database, these are used to get the in-doubt transactions in the database during the recovery scanning.

**Comment by cherrylzhao** [comment]
I'll change the spi definition in dev-3.1.0, please wait for a moment.

**Comment by zhfeng** [comment]
I close this issue since the changes have been merged. NOTE, it has only introduce the destroy() method in the SPI as the init() should be invoked in the construct of the implementation classes. Anyway, we still need to find the hook of the shutdown process to invoked the destroy().

Thanks for the helping !
