### ISSUE TITLE
add git message

### ISSUE THREAD

**Issue by taojintianxia** [sharding-sphere/sharding-sphere#1359]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
no

### Describe the feature you would like.
please add git message in your commit(e.g https://github.com/joelparkerhenderson/git_commit_message), this makes the commit log more clear since behavior separate into specific ACTIONS. 

Summary keywords : 
Add = Create a capability e.g. feature, test, dependency.
Drop = Delete a capability e.g. feature, test, dependency.
Fix = Fix an issue e.g. bug, typo, accident, misstatement.
Bump = Increase the version of something e.g. a dependency.
Make = Change the build process, or tools, or infrastructure.
Start = Begin doing something; e.g. enable a toggle, feature flag, etc.
Stop = End doing something; e.g. disable a toggle, feature flag, etc.
Refactor = A change that MUST be just refactoring.
Reformat = A change that MUST be just formatting, e.g. change spaces.
Rearrange = A change that MUST be just arranging, e.g. change layout.
Redraw = A change that MUST be just visual, e.g. change a graphic, image, icon, etc.
Reword = A change that MUST be just textual, e.g. change a comment, label, doc, etc.
Optimize = A change that MUST be just about performance, e.g. speed up code.
Document = A change that MUST be only in the documentation, e.g. help files.

**Comment by terrymanu** [comment]
can you submit a pull request？

**Comment by taojintianxia** [comment]
### that's not code related, it's just a kind of standard, let's get straight with following example :
#### this is the latest git log from ss :
```
refactor rewrite
@terrymanu
terrymanu committed 5 days ago
 
move MasterSlaveSQLRewriteEngine to sharding-core
@terrymanu
terrymanu committed 5 days ago
 
add comparable for SQLToken
@terrymanu
terrymanu committed 5 days ago
 
java doc 
@tristaZero
tristaZero committed 5 days ago
 
add author
@tristaZero
tristaZero committed 5 days ago
```
#### let's add some keywords to make it in different specific type :
```
Refactor: refactor rewrite
@terrymanu
terrymanu committed 5 days ago
 
Refactor: move MasterSlaveSQLRewriteEngine to sharding-core
@terrymanu
terrymanu committed 5 days ago
 
Add: add comparable for SQLToken
@terrymanu
terrymanu committed 5 days ago
 
Document: java doc 
@tristaZero
tristaZero committed 5 days ago
 
Reword: add author
@tristaZero
tristaZero committed 5 days ago
```
#### with git template : 
```
Improved the documentation of ss chapter xxx

# See links to relevant web pages, issue trackers, blog articles, etc.
See: https://example.com/
See: [Example Page](https://example.com/)

# List all co-authors, so version control systems can connect teams.
Co-authored-by: Name <trista@example.com>

# Why is this change happening, e.g. goals, use cases, stories, etc.?
Why: why u do that

# How is this change happening, e.g. implementations, algorithms, etc.?
How: how you do that

# Tags suitable for searching, such as hashtags, keywords, etc.
Tags: xxx
```

**Comment by taojintianxia** [comment]
check this  : https://github.com/joelparkerhenderson/git_commit_message

**Comment by terrymanu** [comment]
just follow https://github.com/sharding-sphere/sharding-sphere/blob/dev/.github/ISSUE_TEMPLATE/bug-report.md, and may try to submit a pull request
