### ISSUE TITLE
[Vote] Donate Sharding-Sphere to Apache Software Foundation

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1361]
After several days discussion with some Apache members, the draft is almost ready: [https://github.com/sharding-sphere/sharding-sphere-doc/blob/master/Proposal.md](https://github.com/sharding-sphere/sharding-sphere-doc/blob/master/Proposal.md), please vote for donating the Sharding-Sphere to Apache Software Foundation.

The vote is for All Initial Committers:

- @terrymanu 
- @haocao 
- @wu-sheng 
- @hanahmily 
- @tuohai666 
- @tristaZero 
- @cherrylzhao 
- @yue530tom 
- @ma-xiao-guang-64 
- @beckhampu 
- @PegasusS 
-  @pottieva 

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

**Comment by terrymanu** [comment]
+1

**Comment by cherrylzhao** [comment]
+1

**Comment by ma-xiao-guang-64** [comment]
+1

**Comment by tristaZero** [comment]
+1

**Comment by wu-sheng** [comment]
It is glad that we are ready to move. Look like I will be a spirit mentor again, like at Zipkin @adriancole :p

Of course, my own +1

**Comment by beckhampu** [comment]
+1

**Comment by haocao** [comment]
+1

**Comment by tuohai666** [comment]
+1

**Comment by yue530tom** [comment]
+1

**Comment by terrymanu** [comment]
@wu-sheng You are the prototype author for sharding-jdbc

**Comment by pottieva** [comment]
＋1

**Comment by PegasusS** [comment]
+1






在 2018-10-23 09:39:40，"Perry.Zhang" <notifications@github.com> 写道：


＋1

**Comment by mackwan84** [comment]
+1

**Comment by terrymanu** [comment]
Vote passed for PMC and initial committers.

**Comment by terrymanu** [comment]
Proposal for ASF: https://wiki.apache.org/incubator/ShardingSphereProposal

**Comment by terrymanu** [comment]
IPMC discuss mail list: https://lists.apache.org/thread.html/9eaddb1b3a071663a6b0a086f01b38513c6f237c711ce97826c200fd@%3Cgeneral.incubator.apache.org%3E

**Comment by terrymanu** [comment]
With 7 +1 binding votes, 7 +1 non-binding votes and NO +/-0
or -1 votes, this VOTE passes. 

Bellow is a voting tally:

Binding
  Craig Russell
  Justin Mclean
  Willem Jiang
  Matt Sicker
  Dave Fisher
  Benjamin Hindman
  Roman Shaposhnik

Non-binding
   Sheng Wu
   Xin Wang
   Von Gosling
   Bruno Mahé
   Zhang Liang
   XIAORUI Wang
   Raja Sundaram Ganesan
