### ISSUE TITLE
Access Denied for Sharding-Proxy 3.0.0

### ISSUE THREAD

**Issue by mackwan84** [sharding-sphere/sharding-sphere#1370]
### Which version of Sharding-Sphere did you use?
3.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
Connect to the the sharding database with the configured username and password
### Actual behavior
Access Denied
### Example codes for reproduce this issue (such as a github link).
authentication:
  username: dbadmin
  password: 123456

props:
  proxy.transaction.enabled: true
  sql.show: true

**Comment by terrymanu** [comment]
I cannot reproduce. please read document, run example and try to understand it.

<img width="658" alt="wechatimg3051" src="https://user-images.githubusercontent.com/5516298/47369982-5da34180-d717-11e8-99c8-d6bbfbe235b5.png">
![wechatimg3052](https://user-images.githubusercontent.com/5516298/47369997-64ca4f80-d717-11e8-8250-10ba850fd278.png)

**Comment by mackwan84** [comment]
Is it possible an issue in windows environment?
