### ISSUE TITLE
Mysql aurora version not supported

### ISSUE THREAD

**Issue by caixinning** [sharding-sphere/sharding-sphere#1373]
## Bug Report
jdbcUrl = jdbc:mysql:aurora://host:3306/..
Then throws exception: "The URL of JDBC is not supported. Please refer to this pattern: jdbc:mysql://([\w\-\.]+):?([0-9]*)/([\w\-]+);?\S* "

See: https://github.com/sharding-sphere/sharding-sphere/blob/dev/sharding-core/src/main/java/io/shardingsphere/core/metadata/datasource/dialect/MySQLDataSourceMetaData.java#L44

**Comment by zhfeng** [comment]
Interesting. I just search for the mysql jdbc format [1] and it looks like can not support the aurora protocol currently ? is it from the amazon aurora [2] ?

Anyway, the pattern mentioned in the MySQLDataSourceMetaData.java should be updated to add the protocol 
```
    private final Pattern pattern = Pattern.compile("jdbc:mysql://([\\w\\-\\.]+):?([0-9]*)/([\\w\\-]+);?\\S*", Pattern.CASE_INSENSITIVE);
```

[1] https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-url-format.html
[2] https://aws.amazon.com/cn/rds/aurora/

**Comment by terrymanu** [comment]
I wonder if use amazon aurora, do we really need to shard data by ourself anymore?

**Comment by tristaZero** [comment]
@caixinning @zhfeng Hi, thanks for your reference url, protocal patttern is added in  #1377 .

**Comment by caixinning** [comment]
@tristaZero Very efficient！
