### ISSUE TITLE
YAML configuration & orchestration persist adjustment

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1375]
The YAML configuration and registry persist content for Sharding-JDBC and Sharding-Proxy is inconsistent now. We need to adjustment and make them consistent.

- [x] YAML adjustment For Sharding-JDBC
  - [x] Move `props` and `configmap` to top level (same level with shardingRule)
- [x] Registry Center adjustment for Sharding-JDBC
  - [x] Instead `sharding` and `masterslave` nodes to default schema name `sharding_db`
  - [x] Move `datasource` node inside `sharding_db` node
  - [x] Move `props` and `configmap` node out of `sharding_db` node
  - [x] Move `datasource` and `rule` node out of `schema\sharding_db` node
- [x] Registry Center adjustment for Sharding-Proxy
  - [x] Instead `proxy` node to sharding schema name
  - [x] Split `datasource` and `rule` nodes for every config-xxx.yaml
  - [x] Remove `sharding_db: !!io.shardingsphere.core.yaml.YamlRuleConfiguration` node, make `shardingRule` or `masterSlaveRule` as root node in `rule` node
  - [x] Split `server` node to `props`, `configmap` and `authentication` node
  - [x] Move `datasource` and `rule` node out of `schema\${schema_name}` node
- [x] Unify implementation
  - [x] Unify JDBC & proxy orchestration for `ConfigurationService`
  - [x] Unify JDBC & proxy orchestration for `ListenerManager`
  - [x] Remove `YamlRuleConfiguration`

The new tasks are as follows:

 - [x] Remove DataSourceParameter from orchestration module.
 - [x] Make sharding and masterSlave stored consistently in orchestration.
 - [x] Make jdbc and proxy stored consistently in orchestration.
 - [x] Delete YamlRuleConfiguration.
 - [x] Delete ProxyDisabledStateEventBusEvent.
 - [x] Fix the bug that authentication configuration is not watched.
 - [x] Fix the bug that when read configuration from registry, orchestrationFacade can not be initialized well.
 - [x] Fix the bug that when update one certain schema, proxy will clear all schemas.
 - [x] Revoke the API of meta for shardingSchema
 - [x] Disable master database can not be permiteed.
 - [x] ConfigMap can be used in proxy.
 - [x] Move DatasourceMap to AbstractDataSourceAdapter.
 - [x] Consider whether it is possiable to move getConnection() and close() to its father class.
 - [x] Split configurationListener.
 - [x] Check the number of sockets for registry.
 - [x] Group some properties into SharidingProperty.
 - [x] Modify Logic schema name and create shardingSchema and masterSlaveSchema.
 - [ ] config and state root package split to service, event, node, listener packages
 - [ ] ListenerFactory rename to OrhcestrationListenerManager
 - [ ] ListenerManager rename to OrhcestrationListener
 - [ ] pull up common components for LogicSchema

**Comment by tristaZero** [comment]
The all tasks are as follows:

 - [ ] Remove DataSourceParameter from orchestration module.
 - [ ] Make sharding and masterSlave stored consistently in orchestration.
 - [ ] Make jdbc and proxy stored consistently in orchestration.
 - [ ] Delete YamlRuleConfiguration.
 - [ ] Delete ProxyDisabledStateEventBusEvent.
 - [ ] Fix the bug that authentication configuration is not watched.
 - [ ] Fix the bug that when read configuration from registry, orchestrationFacade can not be initialized well.
 - [ ] Fix the bug that when update one certain schema, proxy will clear all schemas.
 - [ ] Revoke the API of meta for shardingSchema
 - [ ] Disable master database can not be permiteed.
 - [ ] ConfigMap can be used in proxy.
 - [ ] Modify api for RuleConfiguration(?).
 - [ ] Make configMap and configuration watched togather(?).
 - [ ] Move DatasourceMap to AbstractDataSourceAdapter.
 - [ ] Consider whether it is possiable to move getConnection() and close() to its father class.
 - [ ] Split configurationListener.
 - [ ] Check the number of sockets for registry.
 - [ ] Group some properties into SharidingProperty.
 - [ ] Modify Logic schema name and create shardingSchema and masterSlaveSchema.
 - [ ] Only create new dataSources for modified dataSources.
