### ISSUE TITLE
sharding-jdbc Cannot support sub query for join table

### ISSUE THREAD

**Issue by lenxeon** [sharding-sphere/sharding-sphere#1376]
sharding-jdbc Cannot support sub query for join table? i remember it seems works good at old version.

**Comment by terrymanu** [comment]
Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).
