### ISSUE TITLE
How to forbid full table scanning

### ISSUE THREAD

**Issue by stonegos** [sharding-sphere/sharding-sphere#1378]
## Question
If we have not a sharding key, sharding-jdbc will execute the sql with all the tables. How to forbid these sqls? If we have the option configuration ?

**Comment by terrymanu** [comment]
If forbid full table scanning when don't have a shardig key, what is your expected for query result?

**Comment by stonegos** [comment]
> If forbid full table scanning when don't have a shardig key, what is your expected for query result?

throw an exception or let developer choise how to do it

**Comment by terrymanu** [comment]
I don't think this is a good design. 

I suggest you can use tracing system to analyze your SQL, example: SkyWalking.

In future, we will support SQL of explain, it also can help you analyze your SQL
