### ISSUE TITLE
sharding-jdbc支持多个数据库同时配置读写分离么

### ISSUE THREAD

**Issue by ittimeline** [sharding-sphere/sharding-sphere#1379]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
