### ISSUE TITLE
Sharding-jdbc supports multiple databases to configure read and write separation at the same time?

### ISSUE THREAD

**Issue by ittimeline** [sharding-sphere/sharding-sphere#1381]
Sharding-jdbc supports multiple databases to configure read and write separation at the same time?

**Comment by terrymanu** [comment]
yes, you can use sharding and master-slave mix

**Comment by terrymanu** [comment]
FIY: http://shardingsphere.io/document/current/en/manual/sharding-jdbc/configuration/

**Comment by ittimeline** [comment]
DataSource tuhuOAMasterDruidDataSource(){
        DruidDataSource druidDataSource=new DruidDataSource();
        tuhuOAMasterDruidDataSourceProperties.config(druidDataSource);
        return druidDataSource;
    }

    DataSource tuhuOASlave0DruidDataSource(){
        DruidDataSource druidDataSource=new DruidDataSource();
        tuhuOASlave0DruidDataSourceProperties.config(druidDataSource);
        return druidDataSource;
    }


    DataSource gungnirMasterDruidDataSource(){
        DruidDataSource druidDataSource=new DruidDataSource();
        gungnirMasterDruidDataSourceProperties.config(druidDataSource);
        return druidDataSource;
    }

    DataSource gungnirSlave0DruidDataSource(){
        DruidDataSource druidDataSource=new DruidDataSource();
        gungnirMasterDruidDataSourceProperties.config(druidDataSource);
        return druidDataSource;
    }


    Map<String, DataSource> createDataSourceMap( ) {
        Map<String, DataSource> result = new HashMap<>(2);
        result.put("ds_tuhu_oa_master", tuhuOAMasterDruidDataSource());
        result.put("ds_gungnir_master",gungnirMasterDruidDataSource());

        result.put("ds_tuhu_oa_slave0", tuhuOASlave0DruidDataSource());
        result.put("ds_gungnir_slave0",gungnirSlave0DruidDataSource());
        return result;
    }
