### ISSUE TITLE
Could not dispatch event: io.shardingsphere.core.transaction.listener.TransactionListener@ec50f54 to public void io.shardingsphere.core.transaction.listener.TransactionListener.listen(io.shardingsphere.core.transaction.event.TransactionEvent) throws java.sql.SQLException

### ISSUE THREAD

**Issue by thompsonGuo** [sharding-sphere/sharding-sphere#1386]
从3.0.0.M1升级到3.0.0.M2后，发现spring中的事务失效，debug进去发现
`    @Subscribe
    @AllowConcurrentEvents
    public void listen(final TransactionEvent transactionEvent) throws SQLException {
        TransactionManager transactionManager = TransactionContextHolder.get().getTransactionManager();
        switch (transactionEvent.getTclType()) {
            case BEGIN:
                transactionManager.begin(transactionEvent);
                break;
            case COMMIT:
                transactionManager.commit(transactionEvent);
                break;
            case ROLLBACK:
                transactionManager.rollback(transactionEvent);
                break;
            default:
        }
    }`
中的transactionManager是个null

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
