### ISSUE TITLE
clear MasterVisited after transaction commit or rollback

### ISSUE THREAD

**Issue by stayfool** [sharding-sphere/sharding-sphere#1387]
## Clear MasterVisited after transaction commit or rollback

If a thread handle some sql not DQL, then this thread marked as MasterVisited, this mark continue to connection closed. After that, all action on this thread route to master. 

I think clear MasterVisited after transaction commit or rollback maybe more reasonable, this make a thread have a chance reroute to slave.

**Comment by terrymanu** [comment]
That is a good suggestion, if clear `MasterVisited ` after transaction finish, maybe next call will get dirty data, it cannot guarantee.
For thread scope, it can guarantee the user can get correct data submit by theirselves.

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
