### ISSUE TITLE
获取不到分片字段,并把当前库下的所有分表都插入了数据

### ISSUE THREAD

**Issue by xulongZY** [sharding-sphere/sharding-sphere#1390]
已经设置分片字段,但是insert的时候是没有给这个字段赋值,比如已经设置分片字段,但是insert的时候是没有给这个字段赋值,比如 我给一个表里的createtime字段赋值,在insert的时候插入成功却没有给这个字段赋值,而且由于只是分表字段,就把所有的表都插入了这条数据

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
