### ISSUE TITLE
how to use multi update with sharding-jdbc

### ISSUE THREAD

**Issue by Swifree** [sharding-sphere/sharding-sphere#1392]
I use mybatis sql like this:
    <foreach collection="list" item="item" separator=";">
        update trade_contract_order
        set
        gmt_modified = now(3)
        where user_id=#{item.userId} and id = #{item.id}
    </foreach>

also I add "allowMultiQueries=true” in jdbc url;
but it seems like that only first sql works.
How do I solve this?

**Comment by terrymanu** [comment]
Not support now
