### ISSUE TITLE
The use of HintShardingAlgorithm

### ISSUE THREAD

**Issue by goooong** [sharding-sphere/sharding-sphere#1393]
## Question

Can you give me a complete Java sample code.

**Comment by leehom** [comment]
I had implemented an one , i found it just as Tenant implemention，i want to know others implementtion too

**Comment by terrymanu** [comment]
the document maybe can help you
http://shardingsphere.io/document/current/en/manual/sharding-jdbc/usage/hint/

**Comment by goooong** [comment]
Thank you for answering my question,Here's my code:

public static DataSource getShardingDataSource(List<DataSourceProperties> dataSourcePropertiesList) throws SQLException {
        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        //shardingRuleConfig.getTableRuleConfigs().add(DebtTableRuleConfiguration.getPlanHintTableRuleConfiguration());
        shardingRuleConfig.getTableRuleConfigs().add(DebtTableRuleConfiguration.getPlanTableRuleConfiguration());
        shardingRuleConfig.getTableRuleConfigs().add(DebtTableRuleConfiguration.getTermTableRuleConfiguration());
        shardingRuleConfig.getTableRuleConfigs().add(DebtTableRuleConfiguration.getEventTableRuleConfiguration());
        Map<String, DataSource> dataSourceMap = DruidDataSourceBuider.build(dataSourcePropertiesList);
        Map<String, Object> configMap = new HashMap<>(0);
        Properties props = new Properties();
        props.put("sql.show", true);
        return ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, configMap, props);
    }

The comment line 3 is working well, it can't be properly sliced without comment, and it can't force sharding.

**Comment by goooong** [comment]
> the document maybe can help you
> http://shardingsphere.io/document/current/en/manual/sharding-jdbc/usage/hint/

Thank you for answering my question,Here's my code:

public static DataSource getShardingDataSource(List dataSourcePropertiesList) throws SQLException {
ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
//shardingRuleConfig.getTableRuleConfigs().add(DebtTableRuleConfiguration.getPlanHintTableRuleConfiguration());
shardingRuleConfig.getTableRuleConfigs().add(DebtTableRuleConfiguration.getPlanTableRuleConfiguration());
shardingRuleConfig.getTableRuleConfigs().add(DebtTableRuleConfiguration.getTermTableRuleConfiguration());
Map<String, DataSource> dataSourceMap = DruidDataSourceBuider.build(dataSourcePropertiesList);
Map<String, Object> configMap = new HashMap<>(0);
Properties props = new Properties();
props.put("sql.show", true);
return ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, configMap, props);
}

The comment line 3 is working well, it can't be properly sliced without comment, and it can't force sharding.

**Comment by terrymanu** [comment]
I can't get your point. Did you mean but if you don't comment the 3rd line, it works well; if comment the 3rd line, it can't work , is it?

**Comment by goooong** [comment]
> I can't get your point. Did you mean if you don't comment the 3rd line, it works well; but if comment the 3rd line, it can't work , is it?

Yes, line 3 is HintShardingAlgorithm.

**Comment by terrymanu** [comment]
I don't understand, if don't comment code is correct, why do you comment it?

**Comment by goooong** [comment]
> I don't understand, if don't comment code is correct, why do you comment it?

sorry，I'm not good at English.Can I use Chinese?

对于同一个表：
只配置ComplexShardingStrategyConfiguration规则能够正确路由到对应的库跟表，
只配置HintShardingStrategyConfiguration规则能够正确路由到对应的库跟表，
如果同时配置ComplexShardingStrategyConfiguration、HintShardingStrategyConfiguration规则，如：
shardingRuleConfig.getTableRuleConfigs().add(HintShardingStrategyConfiguration);
shardingRuleConfig.getTableRuleConfigs().add(ComplexShardingStrategyConfiguration);
则通过HintManager指定库表的查询方式能够正确路由到对应的库跟表，
通过带分片键的查询方式不能够正确路由到对应的库跟表，而是笛卡尔积查询。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
