### ISSUE TITLE
建议读写分离功能负载均衡策略支持权重设置

### ISSUE THREAD

**Issue by imloki** [sharding-sphere/sharding-sphere#1397]
目前sharding jdbc的读写分离功能已经支持轮询和随机两种负载均衡策略，但是实践过程中，读写分离功能不可避免的存在主从库延迟的问题，期望能够支持权重配置读操作落在主从库上的比例，以便达到业务灰度上线或者快速回滚的目的，也能支持调整读操作对多数据库的压力。

**Comment by imloki** [comment]
Dubbo框架内有这样的权重算法，只要扩展或者直接修改原来的负载均衡策略即可，可对外暴露设置权重的方法，用于业务自行集成配置中心，达到线上动态调整权重的目的。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
