### ISSUE TITLE
Instancing ShardingAlgorithm with supprting of spring

### ISSUE THREAD

**Issue by leehom** [sharding-sphere/sharding-sphere#1399]
Instancing ShardingAlgorithm with supprting of spring, that ShardingAlgorithm intances can inject with its dependencies that had init too

**Comment by terrymanu** [comment]
What is your proposal? submit a bug or ask a question?

**Comment by leehom** [comment]
new feature

**Comment by leehom** [comment]
Maybe，I could say it refactor other than new feature, now ShardingAlgorithm is instanced by Class.forName, so it‘s dependenciey，for example，some app service , can't to be init(or not easyly)，in fact，ShardingAlgorithm in most time，need to access db for some data or other services

**Comment by leehom** [comment]
oh，I see，within 3.0.0 plus versions, ShardingAlgorithm is an instance, **class.forName** occurs in v2.0.3 minus，maybe，i could update to newer versions as soon as possibly

**Comment by terrymanu** [comment]
ok, please try new version
