### ISSUE TITLE
Read-Write Splitting multi-master Support

### ISSUE THREAD

**Issue by huckhuang** [sharding-sphere/sharding-sphere#1407]
## Feature Request

Read-Write Splitting supports multi-master data source.

### Is your feature request related to a problem?

No.

### Describe the feature you would like.

`masterSlaveRule` only support single master data source now, using `masterDataSourceName`.

I am using Sharding Proxy, and expect the Read-Write Splitting could support multi-master data source, using `masterDataSourceNames`.

**Comment by terrymanu** [comment]
We will do it on 4.x by Multiple Data Replication.
Please ref our roadmap.
So I just close it for now.
