### ISSUE TITLE
mysql workbench cannot connect in 3.0.0

### ISSUE THREAD

**Issue by pfroad** [sharding-sphere/sharding-sphere#1415]
I config username and password and can connect in mysql wordbench in **3.0.0.M2**.

But i cannot connect in **3.0.0**, return is
_"Failed to Connect to MySQL at 127.0.0.1:3307 with user root
Unknown database '`sharding_db`'"_

**Comment by terrymanu** [comment]
Please show your config yaml

**Comment by pfroad** [comment]
> your
server.yaml
authentication:
  username: root
  password: root

props:
  max.connections.size.per.query: 1
  acceptor.size: 12  # The default value is available processors count * 2.
  executor.size: 16  # Infinite by default.
  proxy.transaction.enabled: false
  proxy.opentracing.enabled: false
  sql.show: false

**Comment by pfroad** [comment]
> Please show your config yaml

server.yaml
authentication:
username: root
password: root

props:
max.connections.size.per.query: 1
acceptor.size: 12 # The default value is available processors count * 2.
executor.size: 16 # Infinite by default.
proxy.transaction.enabled: false
proxy.opentracing.enabled: false
sql.show: false

**Comment by terrymanu** [comment]
beside server yaml, you should have config yaml

**Comment by pfroad** [comment]
> beside server yaml, you should have config yaml

##################      ##################
# Here you can configure the rules for the proxy.
# This example is configuration of sharding rule.
#
# If you want to use sharding, please refer to this file;
# if you want to use master-slave, please refer to the config-master_slave.yaml.
#
######################################################################################################

schemaName: sharding_db

dataSources:
  ds_master_0:
    url: jdbc:mysql://192.168.99.101:3306/db1?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: cat
    password: 123456
    autoCommit: true
    maximumPoolSize: 64
    idleTimeout: 60000
    maxLifetime: 1800000
    connectionTimeout: 30000
  ds_master_0_slave_0:
    url: jdbc:mysql://192.168.99.101:3307/db1?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: cat
    password: 123456
    autoCommit: true
    maximumPoolSize: 64
    idleTimeout: 60000
    maxLifetime: 1800000
    connectionTimeout: 30000
  ds_master_1:
    url: jdbc:mysql://192.168.99.101:3306/db2?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: cat
    password: 123456
    autoCommit: true
    maximumPoolSize: 64
    idleTimeout: 60000
    maxLifetime: 1800000
    connectionTimeout: 30000
  ds_master_1_slave_0:
    url: jdbc:mysql://192.168.99.101:3307/db2?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: cat
    password: 123456
    autoCommit: true
    maximumPoolSize: 64
    idleTimeout: 60000
    maxLifetime: 1800000
    connectionTimeout: 30000
  ds_master_2:
    url: jdbc:mysql://192.168.99.101:3306/db3?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: cat
    password: 123456
    autoCommit: true
    maximumPoolSize: 64
    idleTimeout: 60000
    maxLifetime: 1800000
    connectionTimeout: 30000
  ds_master_2_slave_0:
    url: jdbc:mysql://192.168.99.101:3307/db3?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: cat
    password: 123456
    autoCommit: true
    maximumPoolSize: 64
    idleTimeout: 60000
    maxLifetime: 1800000
    connectionTimeout: 30000

shardingRule:
  tables:
    sbtest1:
      actualDataNodes: ds_${0..1}.sbtest${0..4}
      tableStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: sbtest${id % 5}

  defaultDatabaseStrategy:
    inline:
      shardingColumn: id
      algorithmExpression: ds_${id % 2}

  defaultTableStrategy:
    inline:
      shardingColumn: id
      algorithmExpression: sbtest${id % 5}
  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator

  masterSlaveRules:
    ds_0:
      masterDataSourceName: ds_master_0
      slaveDataSourceNames:
        - ds_master_0_slave_0
      loadBalanceAlgorithmType: ROUND_ROBIN
      configMap:
        master-slave-key0: master-slave-value0
    ds_1:
      masterDataSourceName: ds_master_1
      slaveDataSourceNames:
        - ds_master_1_slave_0
      loadBalanceAlgorithmType: ROUND_ROBIN
      configMap:
        master-slave-key0: master-slave-value0
    ds_2:
      masterDataSourceName: ds_master_2
      slaveDataSourceNames:
        - ds_master_2_slave_0
      loadBalanceAlgorithmType: ROUND_ROBIN
      configMap:
        master-slave-key0: master-slave-value0

**Comment by pfroad** [comment]
> It looks like your config file is correct.
> 
> Cloud you describe how does this exception occur and what is the stack trace of exception?

protected void auth(final ChannelHandlerContext context, final ByteBuf message) {
        try (MySQLPacketPayload payload = new MySQLPacketPayload(message)) {
            HandshakeResponse41Packet response41 = new HandshakeResponse41Packet(payload);
            if (authenticationHandler.login(response41.getUsername(), response41.getAuthResponse())) {
                if (!Strings.isNullOrEmpty(response41.getDatabase()) && !GlobalRegistry.getInstance().schemaExists(response41.getDatabase())) {
                    context.writeAndFlush(new ErrPacket(response41.getSequenceId() + 1, ServerErrorCode.ER_BAD_DB_ERROR, response41.getDatabase()));
                    return;
                }
                setCurrentSchema(response41.getDatabase());
                context.writeAndFlush(new OKPacket(response41.getSequenceId() + 1));
            } else {
                // TODO localhost should replace to real ip address
                context.writeAndFlush(new ErrPacket(response41.getSequenceId() + 1,
                        ServerErrorCode.ER_ACCESS_DENIED_ERROR, response41.getUsername(), "localhost", 0 == response41.getAuthResponse().length ? "NO" : "YES"));
            }
        }
    }
i debug the sharding-proxy, the line `context.writeAndFlush(new OKPacket(response41.getSequenceId() + 1));` has been executed, but i still get that error and no other exceptions return.

**Comment by terrymanu** [comment]
any more details?

**Comment by terrymanu** [comment]
I cannot reproduce, this error message maybe not throw on this part of code.
So maybe you need try to find some hint for reproduce it

**Comment by terrymanu** [comment]
Hi, any update on this issue?

**Comment by pfroad** [comment]
> Hi, any update on this issue?

My Mysql workbench version is 6.2 in ubuntu, it cannot connect, and i use **Nativate for mysql** is ok. I guess branch 3.0.0 is not incompatible with this mysql workbench.

**Comment by terrymanu** [comment]
ok, i will try to reproduce it
