### ISSUE TITLE
By mocking orachestration registry to optimize spring orchestration tests.

### ISSUE THREAD

**Issue by tristaZero** [sharding-sphere/sharding-sphere#1426]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

**By mocking orachestration registry to optimize spring orchestration tests**
I Will use spi method to create registry for spring orchestration tests, therefore we can delete those artifact:
```
<dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-orchestration-reg-zookeeper-curator</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
</dependency>
```

**Comment by terrymanu** [comment]
finished
