### ISSUE TITLE
every time when connection closes ，HintManager closes too.

### ISSUE THREAD

**Issue by maruixiang** [sharding-sphere/sharding-sphere#1455]
I use mybatis, each sql will open a connection and  close  a connection ( return to pool) when finished.
When the connection closes , the HintManagerHolder also clears. 
 see io.shardingsphere.core.jdbc.adapter.AbstractConnectionAdapter 
 ... ..
    @Override
    public final void close() throws SQLException {
        closed = true;
        HintManagerHolder.clear();

So after inserting , before each select , a HintManage  must be created.  such as:

insert     
HintManage 
 select 1
HintManage 
 select 2
HintManage 
 select 3

Is there any way to create HintManage  only one time, not three times?

**Comment by maruixiang** [comment]
I suggest -> 
 // add a new method 
 public static HintManager getInstance(boolean autoClose) {
        HintManager result = new HintManager(autoClose);
        HintManagerHolder.setHintManager(result);
        return result;
    }

  AbstractConnectionAdapter.close judge 
  if autoClose   HintManagerHolder.clear();
  ......

**Comment by terrymanu** [comment]
I think this issue is same with #1387, cloud we discuss there?
