### ISSUE TITLE
roadmap of Sharding-Sidecar

### ISSUE THREAD

**Issue by loxp** [sharding-sphere/sharding-sphere#1462]
Is there any detailed roadmap of Sharding-Sidecar?

**Comment by terrymanu** [comment]
# Sharding-Sphere on K8s Integration

## Current Solutions:

1. Helm Chart

The simplest and most direct way to combine with K8s is to directly deploy a sharding-proxy with helm chart;
Like:

`helm install sharding-proxy`

There are two ways to distribute helm charts of sharding-proxy, the first one of which is to provide a repo by the user himself through `helm repo add sharding-sphere https://example.com/sharding-sphere-charts/stable/`; 
the second one is to submit chart to [helm official](https://github.com/helm/charts) to maintain it, and in this way, users can directly use  the command line `helm search sharding-sphere`.

The specific deployment also has many other options:

1.1 daemonset, each node runs a proxy, all the business must visit the database through proxy, as native proxy is especially better to visit mysql (native k8s is not available currently, relevant bp exists but is not completed yet). The service finding problem is concerned here, on how to visit these proxies. First, it is unable to visit proxy without knowing the node IP. Second, it is also unable to visit through 127.0.0.1, which can only be used within a network namespace. So we can only generate a service for daemonset, and all the business can only access the database through VIP or DNS of that service.

1.2 deployment, each user can use helm install to run a proxy according to their needs, and all their own business can only access the database through that, mainly through VIP or DNS; or they can install a deployment to scale out according to the load (better way). 

2. Long-Term Solution

This solution is tightly combined with k8s, and needs to develop the relevant controller, with a relatively long term. In addition, currently based on jvm, proxy has a relatively high cost. If it is taken as sidecar, each pod needs to consider the resource occupation situation of proxy besides its business. One good way is golang version proxy, which lightens proxy and makes it sidecar.
This way needs to make some adjustments to the structure of sharding-sphere, but does not clash with the first method. It is recommended to achieve that in steps: deploy helm chart first; then work on operators according to the feedback or develop some controllers to realize.

**Comment by loxp** [comment]
ok, thanks a lot.
