### ISSUE TITLE
使用 select (a+b) as sum from test 报告找不到表的错误

### ISSUE THREAD

**Issue by cheerlxd** [sharding-sphere/sharding-sphere#1472]
版本：3.0.0M3
配置情况：
sharding:sharding-rule data-source-name="config_db,order_db1,order_db2"

问题描述：
在 Tokenizer.java这个类里面
方法 scanidentifier() 扫描关键字

当sql是 select orderid, (a+b) as sum from order 这种的就无法处理  加号
所以 SelectStatement中 items就会不对

结果会导致表映射到其他库（貌似默认就是第一个库，然后按照默认策略，就映射到了config_db.order表）

在 MySQLSelectParser的 parseInternal重现

希望能够尽快支持下

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
