### ISSUE TITLE
mybatis batch update exception eg: update sql1;update sql2

### ISSUE THREAD

**Issue by 80631004** [sharding-sphere/sharding-sphere#1477]
## Bug Report

use shardingjdbc batch update, eg:update sql1;update sql2  throws exception, how can solve this problem?

### Which version of Sharding-Sphere did you use?
3.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
support batch update sql
### Actual behavior
throw exception:
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'apos_order_2.pos_salesh' doesn't exist
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'apos_order_2.pos_salesh' doesn't exist
	at

**Comment by 80631004** [comment]
11-15 07:11:46.134 INFO  [Sharding-Sphere-SQL] - Actual SQL: apos_order_2 ::: update pos_salesh_2 set salesmancode2=null,salesmancode1=null,shardingdb='2_2',roundamt=0.0,custgradeid=null,cashiercode='1001',payamt=45.0,voidsalesby=null,salesmanname2=null,salesmanname1=null,createdby='1e63529ef8f54f3ebf66cdbd5b8f8094',returnsalesid=null,custgradecode=null,postype='M',changeamt=0.0,costamt=40.2,posid='01',salesdate='2018-11-14',custid=null,custbalance=0.0,cashierid='1e63529ef8f54f3ebf66cdbd5b8f8094',ttldiscbyid=null,voidsalestime=null,custgradename=null,status='1',ttldiscamt=0.0,birthday=null,ttldiscbyname=null,serialnum='181114010195',ttlpointvalue=0.0,salesmonth='2018-11',retailamt=45.0,salesamt=45.0,remark='',salestime='2018-11-14 22:14:49',voidsalesid=null,salestype='S',salesmanid2=null,salesmanid1=null,ttldiscbycode=null,vipdiscamt=0.0,salesno='S181114221449010197',custcode=null,salesyear='2018',salesqty=1.0,beforettlpoint=0.0,autosalesremind=0,discountamt=0.0,custphone=null,voidsalesno=null,fullmarkdownno=null,isupload=0,fullmarkdownamt=0.0,createdtime='2018-11-14 22:14:49',cashiername='管理员',returnsalesno=null,fullmarkdownname=null,isdelete=0,custname=null where  ShardingDB='2_2' and id='b9bf5613c42e4a9381908ee789df40b3';update pos_salesh set salesmancode2=null,salesmancode1=null,shardingdb='2_2',roundamt=0.0,custgradeid=null,cashiercode='1001',payamt=45.0,voidsalesby=null,salesmanname2=null,salesmanname1=null,createdby='1e63529ef8f54f3ebf66cdbd5b8f8094',returnsalesid=null,custgradecode=null,postype='M',changeamt=0.0,costamt=40.2,posid='01',salesdate='2018-11-14',custid=null,custbalance=0.0,cashierid='1e63529ef8f54f3ebf66cdbd5b8f8094',ttldiscbyid=null,voidsalestime=null,custgradename=null,status='1',ttldiscamt=0.0,birthday=null,ttldiscbyname=null,serialnum='181114010195',ttlpointvalue=0.0,salesmonth='2018-11',retailamt=45.0,salesamt=45.0,remark='',salestime='2018-11-14 22:14:49',voidsalesid=null,salestype='S',salesmanid2=null,salesmanid1=null,ttldiscbycode=null,vipdiscamt=0.0,salesno='S181114221449010198',custcode=null,salesyear='2018',salesqty=1.0,beforettlpoint=0.0,autosalesremind=0,discountamt=0.0,custphone=null,voidsalesno=null,fullmarkdownno=null,isupload=0,fullmarkdownamt=0.0,createdtime='2018-11-14 22:14:49',cashiername='管理员',returnsalesno=null,fullmarkdownname=null,isdelete=0,custname=null where  ShardingDB='2_2' and id='b9bf5613c42e4a9381908ee789df40b8';


seems form second update sql2,it is not sharding

**Comment by terrymanu** [comment]
ShardingSphere don't support multiple SQL in one JDBC statement
