### ISSUE TITLE
如果配置了读写分离，是否可以指定主库或者从库查询？如果不能，怎么解决主从不同步的问题?

### ISSUE THREAD

**Issue by fangdong116** [sharding-sphere/sharding-sphere#1478]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
For English only, other languages will not accept.
