### ISSUE TITLE
It's not sharding when execute sql

### ISSUE THREAD

**Issue by cheerlxd** [sharding-sphere/sharding-sphere#1481]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

### Which version of Sharding-Jdbc do you using?
3.0.0M3

### My configs
use spring namespace, such as
<sharding:table-rule 
logic-table="order" 
actual-data-nodes="database.order_$->{1..31}" 
database-strategy-ref="myStrategy"  />

### Steps to reproduce the behavior 
execute sql ：
`select time,order from order where (time='20181115')` 
it will get data from database.order_15 (my data in here), in fact work well.

when i change actual-data-nodes to `database.order_$->{1..3}` and change stragery make  0-9 to 1, 10-19 to 2 , rest to 3.
execute sql against, it's not data, and i create breakpoint on algorithm, found it not enter and query node 1 to 3.

on debug mode, i found variable  `tableShardingValues` is empty when execute on method `StandareRoutingEngine.routeTables`  , but i do `insert into order values ('20181111','iphone')` will enter my breakpoint.

I hope to get your advice, thanks

**Comment by tuohai666** [comment]
Please show your **Strategy** before and after completely.

**Comment by tuohai666** [comment]
BTW, I suggest you try 3.0.0 first, for 3.0.0.M3 will not be supported any longer.
Any way, let me see your Strategy code.

**Comment by cheerlxd** [comment]
> Please show your **Strategy** before and after completely.

thanks your advice, it's same result on 3.0.0, the Strategy code before and after like

`
public final class TimeShardingAlgorithm implements ComplexKeysShardingAlgorithm {
        
       /** the old Strategy  */
	@Override
	public Collection<String> doSharding(Collection<String> availableTargetNames,
			Collection<ShardingValue> shardingValues) {
		List<String> timeValues = AlgorithmUtil.getShardingValue(shardingValues, "time");
		List<String> shardingSuffix = new ArrayList<>();
		// like 20180101
		for (String time : timeValues) {
			Integer day = Integer.parseInt(time.substring(6));
			String suffix = day.toString();
			for (String targetName : availableTargetNames) {
				if (targetName.endsWith("_" + suffix)) {
					shardingSuffix.add(targetName);
				}
			}
		}
		return shardingSuffix;
	}

        /**   the new Strategy    */
	@Override
	public Collection<String> doSharding(Collection<String> availableTargetNames,
			Collection<ShardingValue> shardingValues) {
		List<String> timeValues = AlgorithmUtil.getShardingValue(shardingValues, "time");
		List<String> shardingSuffix = new ArrayList<>();
		// like 20180101
		for (String time : timeValues) {
			Integer day = Integer.parseInt(time.substring(6));
			// may get  1 2 3 4
			day = day / 10 + 1; 
                        // convert to 1 2 3
			day = day > 3 ? 3 : day;
			String suffix = day.toString();
			for (String targetName : availableTargetNames) {
				if (targetName.endsWith("_" + suffix)) {
					shardingSuffix.add(targetName);
				}
			}
		}
		return shardingSuffix;
	}
}
`

**Comment by tuohai666** [comment]
1. Is AlgorithmUtil.getShardingValue() your private code?
2. Have you change any code, config or sql besides Stratege? Please check very carefully before you replay. Variable tableShardingValues would return same value before and after if codes, config, sql are all same.
3. I suggest you switch to old stratege, watch tableShardingValues and find out if it can run correctly.

**Comment by tuohai666** [comment]
4. Can you show me the config file completely, you may hide ip address, etc.

**Comment by cheerlxd** [comment]
> 1. Can you show me the config file completely, you may hide ip address, etc.

thanks your advice

I create a new simple project on weekend, and try different strategy on query, results consistent with expectations

https://github.com/cheerlxd/sharding-jdbc-demo
