### ISSUE TITLE
Switch transaction type in ShardingSphere with annotation

### ISSUE THREAD

**Issue by KomachiSion** [sharding-sphere/sharding-sphere#1482]
### Is your feature request related to a problem?

#986 #1363 

### Describe the feature you would like.

Currently, Sharding-JDBC switches different types of transactions through TransactionTypeHolder.set method before starting a transaction.
If users use spring-annotated transaction, the switching requires to call the API to set the transaction type before calling the annotated method like this
```
public void changeTransactionTypeBeforeExecute() {
    TransactionTypeHolder.set(TransactionType.xxx);
    insertData();
}

@Transactional
public void insertData() {
    ......
}
```
It's seem very inconvenient.
So, I think we can define a new annotation named ShardingTransactional, which extends spring Transactional annotation just like SpringBootApplication annotation. And setting transaction type in AOP interceptor.
Finally, users use this annotation instead of original spring annotation like that
```
@ShardingTransactional(type="xxx", timeout = 10000, rollbackFor = RuntimeException.class)
public void insertData() {
    ......
}
```
It looks better.
And when users use Sharding-Proxy, this annotation can also be used to control the type of the current transaction like that
```
@ShardingTransactional(type="xxx", environment="PROXY", rollbackFor = RuntimeException.class)
public void insertData() {
    ......
}
```
### Design implementation for the feature

We plan to use Spring AOP to implement the feature.
ShardingSphere will create a pointcut for `@ShardingTransactional`, and weave the interceptor executed before Spring Transactional interceptor.
In the ShardingTransactional interceptor, ShardingSphere will perform different switching behaviors based on the `type` attribute and the `environment` attribute in the annotation.

- environment=JDBC: The interceptor will call `TransactionTypeHolder` to set Transactional type as `type` attribute value.
- environment=PROXY: The interceptor will send switch message to Sharding-Proxy.

Finally, the process of the annotated transaction would be:
`ShardingTransactionalIntercetor --> SpringTransactionIntercetor.beginTransaction --> BusinessMethod --> SpringTransactionIntercetor.endTransaction --> ShardingTransactionalIntercetor (optional)`

The TODO list:
- [x] Switch transaction type in Sharding-JDBC with annotation.
- [x] Switch transaction type in Sharding-Proxy with annotation.
- [x] Documents

**Comment by cherrylzhao** [comment]
it is wonderful! consider about add a `environment` property to distinguish Jdbc and proxy
maybe we can modify transaction type through `SET transaction='XX'` in proxy.
