### ISSUE TITLE
algorithmExpression 分表字段如何使用varchar类型 

### ISSUE THREAD

**Issue by quicksandznzn** [sharding-sphere/sharding-sphere#1490]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
For English only, other languages will not accept.

**Comment by quicksandznzn** [comment]
fuck you bitch
