### ISSUE TITLE
ShardingDataSource   Initialized data sources can not be master-slave data sources.

### ISSUE THREAD

**Issue by yiwugou** [sharding-sphere/sharding-sphere#1493]
version:3.0.0
`
java.lang.IllegalArgumentException: Initialized data sources can not be master-slave data sources.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at io.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.checkDataSourceType(ShardingDataSource.java:77)
`
[这个链接](http://shardingsphere.io/document/current/cn/manual/sharding-jdbc/configuration/config-spring-namespace/) 里面的读写分离+数据分片 中的实例配置, ShardingDataSource 的子ds可以为MasterSlaveDataSource,可代码中却有这样的检查 是不是bug

![tim 20181119171201](https://user-images.githubusercontent.com/28729808/48697517-c51db580-ec1f-11e8-9cbe-0abedc07a5a2.png)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
