### ISSUE TITLE
about joint queries （SUM and COUNT）

### ISSUE THREAD

**Issue by zhangdanyun** [sharding-sphere/sharding-sphere#1498]
C：split table （sharding）
A，B：common table
problem：（There should be more than one result ，but Only，if count() replace group_concat() this ok，why？ sum() That's the same）
SELECT
        count(d.deviceGuid) deviceGuids，
        d.guid
        FROM
        C p,
        (
        SELECT
        nbhd.*,
        adv_device.guid deviceGuid
        FROM(
        SELECT * FROM A 
            ) AS nbhd
            INNER JOIN B ON nbhd.guid = B.nghdGuid
        ) AS d
        WHERE
        d.deviceGuid = p.deviceGuid and
        p.frequencyState = 0
        GROUP BY
        d.guid

**Comment by terrymanu** [comment]
duplicated with #1376
