### ISSUE TITLE
sql contains case when conditions, cannot find the correct shardingvalue

### ISSUE THREAD

**Issue by leishb** [sharding-sphere/sharding-sphere#1501]
sql:
update account set balance=balance+? pre_amount = CASE WHEN last_posting_date < ? THEN amount WHEN last_posting_date = ? THEN pre_amount ELSE pre_amount + ? END  where  user_id=?

**Comment by terrymanu** [comment]
Do not support case when now, please read document to find some information first

**Comment by leishb** [comment]
之前我们使用的是低版本1.4.1是可以的，升级到3.0.0之后不能使用了。是去掉这个功能了吗？

**Comment by leishb** [comment]
> Do not support case when now, please read document to find some information first

之前我们使用的是低版本1.4.1是可以的，升级到3.0.0之后不能使用了。是去掉这个功能了吗？
