### ISSUE TITLE
您好，单库分表事务不起作用，请协助帮忙看下是什么原因

### ISSUE THREAD

**Issue by 1610200527** [sharding-sphere/sharding-sphere#1502]
您好，我用的是sharding-jdbc-3.3.0，druid,mybatis 这个是我的数据库JAVA配置：
Service层用的Spring注解@Transactional，我debug的时候，发现压根没Creating new transaction。
以下是我的配置：
@MapperScan(basePackages = "xx.xx.xx.dao.main" , sqlSessionTemplateRef = "mainSqlSessionTemplate")
public class MainDataSourceConfig {

    @Bean(name="mainDataSource")
    @ConfigurationProperties(prefix = "spring.datasource")
    public DruidDataSource setDataSource() {
        return new DruidDataSource();
    }

    @Bean(name = "mainTransactionManager")
    @Primary
    public PlatformTransactionManager setTransactionManager(@Qualifier("mainDataSource") DataSource dataSource) {
        DataSourceTransactionManager dataSourceTransactionManager = new DataSourceTransactionManager(this.buildDataSource(dataSource));
        return dataSourceTransactionManager;
    }

    @Bean(name = "mainSqlSessionFactory")
    public SqlSessionFactory setSqlSessionFactory(@Qualifier("mainDataSource") DataSource dataSource) throws Exception {
        SqlSessionFactoryBean bean = new SqlSessionFactoryBean();
        bean.setDataSource(this.buildDataSource(dataSource));
        try{
            bean.setMapperLocations(new PathMatchingResourcePatternResolver().getResources("classpath:mybatis/mapper/main/*.xml"));
            ResourcePatternResolver resolver =new PathMatchingResourcePatternResolver();
        }catch (Exception ex){
            LoggerHelper.error(this.getClass(),ex.getMessage(),ex);
        }
        return bean.getObject();
    }

    @Bean(name = "mainSqlSessionTemplate")
    public SqlSessionTemplate setSqlSessionTemplate(@Qualifier("mainSqlSessionFactory") SqlSessionFactory sqlSessionFactory) throws Exception {
        return new SqlSessionTemplate(sqlSessionFactory);
    }

    public DataSource buildDataSource(@Qualifier("mainDataSource") DataSource druidDataSource) {
        DataSource dataSource = null;
        try{
            Map<String, DataSource> dataSourceMap = new HashMap<>(1);
            dataSourceMap.put("default", druidDataSource);

            ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
            shardingRuleConfig.getTableRuleConfigs().add(getVehicleInfoTableRuleConfiguration());
            shardingRuleConfig.getTableRuleConfigs().add(getVehilcePhotoTableRuleConfiguration());
            shardingRuleConfig.getBindingTableGroups().add("xx_info,xx_photo");
            shardingRuleConfig.setDefaultDataSourceName("default");
            shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig(new NoneShardingStrategyConfiguration());

            Properties properties = new Properties();
            properties.setProperty("sql.show","true");

            return ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, new ConcurrentHashMap(), properties);

        }catch (Exception ex){
            Log.error(MainDataSourceConfig.class, "创建数据库链接失败！", ex);
        }
        return dataSource;
    }

    TableRuleConfiguration getVehicleInfoTableRuleConfiguration() {
        TableRuleConfiguration result = new TableRuleConfiguration();
        result.setLogicTable("xx_info");
        result.setActualDataNodes("default.xx_info_${0..4}");
        result.setKeyGenerator(new DefaultKeyGenerator());
        result.setTableShardingStrategyConfig(new StandardShardingStrategyConfiguration("unified_number", new ModuleTableShardingAlgorithm()));
        result.setKeyGeneratorColumnName("id");
        return result;
    }

    TableRuleConfiguration getVehilcePhotoTableRuleConfiguration() {
        TableRuleConfiguration result = new TableRuleConfiguration();
        result.setLogicTable("xx_photo");
        result.setActualDataNodes("default.xx_photo_${0..4}");
        result.setTableShardingStrategyConfig(new StandardShardingStrategyConfiguration("unified_number", new ModuleTableShardingAlgorithm()));
        result.setKeyGenerator(new DefaultKeyGenerator());
        result.setKeyGeneratorColumnName("photo_id");
        return result;
    }
}

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by 1610200527** [comment]
崇洋媚外，搞JJ个英文啊，不回答拉倒，换mycat，傻屌！
