### ISSUE TITLE
Doesn't `SELECT MAX(id) FROM user` work ?

### ISSUE THREAD

**Issue by baijifeilong** [sharding-sphere/sharding-sphere#1515]
## Doesn't `SELECT MAX(id) FROM user` work ?

My SELECT query does not have any sharding key in conditon. I want to get the max id of all users from shading tables in sharding databases. But it seems not work. It throwed an exception `java.sql.SQLSyntaxErrorException: Table 'ds0.user' doesn't exist"`. So what's the reason.

I am using ShardingJDBC 3.0

**Comment by terrymanu** [comment]
We have test case for this case.
So I think this issue is caused by other reason, please try to find it and maybe submit a new issue
