### ISSUE TITLE
使用mybatis collection 级联查询 不走分库分表？

### ISSUE THREAD

**Issue by 80631004** [sharding-sphere/sharding-sphere#1526]
使用mybatis collection 级联查询 不走分库分表，如下片段语法，请确认是否为BUG，或后续是否支持这种写法，谢谢
<collection property="posStockflowdetailList" ofType="com.aibao.pos.stockflow.model.dto.PosStockflowdetailVO" column="{stockFlowId=id,storeId=nextFlowStoreId,storeSysCode=storeSysCode}" select="com.aibao.pos.stockflow.mapper.PosStockflowdetailMapper.findDetailVoListBystockFlowId" >
</collection> 

使用版本：sharding jdbc 3.0

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
