### ISSUE TITLE
insert 无法生成分布式主键

### ISSUE THREAD

**Issue by zj974185723** [sharding-sphere/sharding-sphere#1528]
系统环境:
shardingsphere 版本3.0.0
mybatis版本3.2.8
mapper3版本3.3.6
问题:
通过配置generate-key-column-name 不能生成主键
原因:
InsertColumnsClauseParser的parseWithColumn方法中将generateKeyColumnIndex从-1设置为了0导致后续不能分布式主键，insert语句中存在主键字段，可能跟mapper3集成的关系。
下个版本能否解决一下这个问题。

**Comment by 1610200527** [comment]
你insert的时候，把主键都干掉呢，配置默认的generate-key-column-name，亲测，可用，但你得写成一个服务，否则会出现重复，今天刚踩到坑，呵呵了！

**Comment by zj974185723** [comment]
> 你insert的时候，把主键都干掉呢，配置默认的generate-key-column-name，亲测，可用，但你得写成一个服务，否则会出现重复，今天刚踩到坑，呵呵了！

没有xml文件，都是动态生成放在缓存里面，难受啊

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
