### ISSUE TITLE
The result of `getBytes` is wrong.

### ISSUE THREAD

**Issue by dozer47528** [sharding-sphere/sharding-sphere#1533]
### Which version of Sharding-Sphere did you use?

3.0.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-Proxy

### Expected behavior

The result of bytes should be:
[88, -99, -9, 80, 65, -64, 65, -70, -83, -98, 49, 15, -115, -103, 13, 116]

### Actual behavior

The result change every time:
[91, 66, 64, 49, 50, 57, 52, 99, 50, 51, 52]
[91, 66, 64, 55, 50, 101, 49, 56, 57, 100, 54]
[91, 66, 64, 52, 54, 55, 54, 98, 48, 53, 56]
[91, 66, 64, 51, 48, 52, 51, 98, 49, 99, 99]
[91, 66, 64, 49, 97, 99, 102, 97, 99, 53, 56]

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```sql
CREATE TABLE `binary_test` (
  `id` binary(16) NOT NULL
) ENGINE=InnoDB;

insert into binary_test (id) value (0x589df75041c041baad9e310f8d990d74);
```

### Example codes for reproduce this issue (such as a github link).

```java
        Connection connection = ds.getConnection();
        PreparedStatement ps = connection.prepareStatement("SELECT * FROM binary_test");
        ps.execute();
        ResultSet rs = ps.getResultSet();
        rs.next();
        byte[] result = rs.getBytes("id");
        System.out.println(Arrays.toString(result));
```

**Comment by dozer47528** [comment]
I tested it in python, which has the same issue.

```python
db = MySQLdb.connect("127.0.0.1", "root", "", "test")
cursor = db.cursor()
cursor.execute("SELECT * FROM binary_test")
data = cursor.fetchone()
print data
db.close()
```
### Expected behavior
`('X\x9d\xf7PA\xc0A\xba\xad\x9e1\x0f\x8d\x99\rt',)`

### Actual behavior
`('[B@b16d465',)`

**Comment by dozer47528** [comment]
I found one problem related to this issue, please fix it.

https://github.com/sharding-sphere/sharding-sphere/pull/1535

The MySQL type was wrong, our ORM framework will convert the type based on the MySQL type.

**Comment by dozer47528** [comment]
For our MySQL use case, we will store UUID to `BINARY(16)`
So that's a huge issue for us.

**Comment by tuohai666** [comment]
@dozer47528 I see you closed your pr. If it have passed the test, why close?

**Comment by dozer47528** [comment]
@tuohai666 After investigating the source code, I found this pull request cannot fix this issue.
In my opinion, Sharding-Proxy shouldn't try to convert JDBC type to MySQL type. They are not a one-to-one mapping. Sharding-Proxy should keep the origin MySQL type from origin database.

**Comment by tuohai666** [comment]
I don't quite understand. How SP keep the origin MySQL type from database? 
SP now performs like this:
1. Receive the SQL from MySQL-client;
2. Execute the SQL by Connector/J.
3. Connector/J gets data and MySQL-types from databases, meanwhile converts the types to JDBC-types.
4. Proxy gets data and JDBC-types, meanwhile converts the JDBC-types to MySQL-types. So that the MySQL-client can accept the MySQL-types.

MySQL-client can never accept the JDBC-types.

So, i think your pr is not so wrong, just need to modify the data encoding together with specified types you have done before.

**Comment by tuohai666** [comment]
@dozer47528, fixed by https://github.com/sharding-sphere/sharding-sphere/pull/1588, 
include types: binary, varbinary, blob, tinyblob, mediumblob, longblob
