### ISSUE TITLE
springboot集成sharding-jdbc 强制hint的example

### ISSUE THREAD

**Issue by yangpancode** [sharding-sphere/sharding-sphere#1534]
请问有springboot集成sharding-jdbc 强制hint的example，我用spring-boot-nodep-mybatis-example进行改造如下，报如下错误：
The error occurred while setting parameters
### Cause: io.shardingsphere.core.exception.ShardingConfigurationException: Cannot find table rule and default data source with logic table: 't_order'

配置如下：
`sharding.jdbc.datasource.names=ds_0,ds_1

sharding.jdbc.datasource.ds_0.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.ds_0.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds_0.url=jdbc:mysql://10.1.109.125:3306/demo_ds_0
sharding.jdbc.datasource.ds_0.username=root
sharding.jdbc.datasource.ds_0.password=123456

sharding.jdbc.datasource.ds_1.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.ds_1.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds_1.url=jdbc:mysql://10.1.109.125:3306/demo_ds_1
sharding.jdbc.datasource.ds_1.username=root
sharding.jdbc.datasource.ds_1.password=123456

sharding.jdbc.config.sharding.database-strategy.hint.sharding-column.algorithm_class_name=io.shardingsphere.example.spring.boot.mybatis.nodep.MyHintShardingAlgorithm
`
我的场景是每个库是数据结构都是一样的，我只想根据系统类似于枚举开进行分库，比如传入一个固定的参数，指定到某个库。不需要配置每个表的路由规则。
请问这种要如何处理，非常感谢！

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by machunlin** [comment]
> s will not accep

有这个必要非得要中文吗，装逼
