### ISSUE TITLE
Unknown exception: Illegal input, unterminated ''' (value string do not support escape character \ )

### ISSUE THREAD

**Issue by joooohnli** [sharding-sphere/sharding-sphere#1536]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere did you use?
3.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
value string supports escape character \
### Actual behavior
value string do not support escape character \
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```
mysql> select * from test where name='\'';
ERROR 3054 (HY000): Unknown exception: Illegal input, unterminated '''.
```
```
mysql> insert into test(name) values ('\'');
ERROR 3054 (HY000): Unknown exception: Illegal input, unterminated '''.
```

**Comment by codefairy08** [comment]
thank you for your issue! it will be fixed next release.

**Comment by joooohnli** [comment]
INSERT & UPDATE statements still failed, while SELECT works well now.



```
mysql> insert into test(name) values ('\'');
ERROR 3054 (HY000): Unknown exception: Illegal input, unterminated '''.
mysql> update test set name='\'' where id=1;
ERROR 3054 (HY000): Unknown exception: Illegal input, unterminated '''.
```

version: 3.1.0.M1

@terrymanu @codefairy08
