### ISSUE TITLE
Does the sharding support LOAD DATA INFILE on mysql?

### ISSUE THREAD

**Issue by cheerlxd** [sharding-sphere/sharding-sphere#1538]
I didn't find information about the title, so hope someone can reply the issue, thanks

**Comment by terrymanu** [comment]
Not yet，proxy don't have mysql local file, so we don't want support this feature now

**Comment by cheerlxd** [comment]
> Not yet，proxy don't have mysql local file, so we don't want support this feature now

thank you very much
