### ISSUE TITLE
PostgreSQL DAL and psql meta-commands

### ISSUE THREAD

**Issue by loxp** [sharding-sphere/sharding-sphere#1541]
## Question

DAL statement in PostgreSQL is quite different from MySQL. in MySQL, we can use show grammar to to 
 get the database information.

- show tables;
- show databases;

but PostgreSQL does not have similar grammars. It use the general SELECT for database administration, like this:

- SELECT * FROM pg_catalog.pg_tables WHERE schemaname != 'pg_catalog' AND schemaname !=  information_schema';
- SELECT datname FROM pg_database;

If we use psql meta-commands, the SQL is more complicated. 
```
\d

SELECT n.nspname as "Schema",
  c.relname as "Name",
  CASE c.relkind WHEN 'r' THEN 'table' WHEN 'v' THEN 'view' WHEN 'm' THEN 'materialized view' WHEN 'i' THEN 'index' WHEN 'S' THEN 'sequence' WHEN 's' THEN 'special' WHEN 'f' THEN 'foreign table' WHEN 'p' THEN 'table' END as "Type",
  pg_catalog.pg_get_userbyid(c.relowner) as "Owner"
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('r','p','v','m','S','f','')
      AND n.nspname <> 'pg_catalog'
      AND n.nspname <> 'information_schema'
      AND n.nspname !~ '^pg_toast'
  AND pg_catalog.pg_table_is_visible(c.oid)
ORDER BY 1,2;
```

```
\l

SELECT d.datname as "Name",
       pg_catalog.pg_get_userbyid(d.datdba) as "Owner",
       pg_catalog.pg_encoding_to_char(d.encoding) as "Encoding",
       d.datcollate as "Collate",
       d.datctype as "Ctype",
       pg_catalog.array_to_string(d.datacl, E'\n') AS "Access privileges"
FROM pg_catalog.pg_database d
ORDER BY 1;
```

My question is, how to implement PostgreSQL parser to support DAL statment and psql meta-commands? implement DQL parser first?

**Comment by tuohai666** [comment]
You don't need to implement PostgreSQL parser to support DAL.
When you input \d on PostgreSQL's command client, the client will translate this abbreviation to a SELECT statement.
So, PostgreSQL server will never get statement like \d, \l.

**Comment by loxp** [comment]
ok, thanks.
