### ISSUE TITLE
Call for the logo of ShardingSphere（征集ShardingSphere的logo）

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1547]
1. The former logo is an “S” consisted of two curved lines up and down. Current thought of the logo renewal is: retain the “S” element while add the meaning of “Sphere.” Referring to ecosphere, “sphere” also contains the meaning of ball, so we can see how to combine both of the two meanings. In brief, the product implication should be “S” (sharding) + sphere (ecosphere).
2. The font of ShardingSphere should be improved to be a more noticeable kind.
3. Two colors should be provided: transparent background color white, fit to put in black or blue background; and a color fit to put on white background, better to be orange, indicating to be related with database.
4. Two layouts should be provided: one for square picture, with the font below the logo; the other for long picture, with the font on the right of the logo.
5. As a result, considering color + layout, there will be 4 kinds of combinations for logo.
6. Not strange when put together with other Apache logos.

中文翻译：
1. 原logo是由上下两个曲线组成的S。目前对logo更新想法是，保留S的元素，再加上Sphere的寓意。sphere是生态圈，直译是球的意思，可以看看如何结合。产品寓意应该是S（分片）+ 球（生态圈）。
2. ShardingSphere字体需要美化为高辨识度的字体。
3. 需要提供两种颜色：一个是透明背景的白色，合适放在黑色或蓝色的背景中；另一个是适合放在白色的背景下的，最好是橙色，表示与数据库相关。
4. 需要提供两种样式：一个是字在logo的下方，适用于方图；另一个是字在logo的右方，适用于长图。
5. 因此，颜色 + 样式，是一共4个logo的组合。
6. 与其他apche的logo放在一起的时候没有违和感

**Comment by bigLeon** [comment]
![image](https://user-images.githubusercontent.com/3086895/49352309-49793980-f6f2-11e8-8aba-aa1e70355246.png)
![image](https://user-images.githubusercontent.com/3086895/49352442-e045f600-f6f2-11e8-95d6-3735a90b4b38.png)

1.chinese elemet   Tai Ji :It represents Chinese philosophy.
2.Sphere is the meaning of circle:
3.S meaning of sharding sphere

**Comment by Quiter2013** [comment]
![image](https://user-images.githubusercontent.com/4453124/49357942-d977ad00-f70b-11e8-9c14-a78e7fc36eef.png)
![image](https://user-images.githubusercontent.com/4453124/49357979-f7451200-f70b-11e8-83d0-e9127ec9a9eb.png)
![image](https://user-images.githubusercontent.com/4453124/49357995-02983d80-f70c-11e8-8b53-0725747ae379.png)

**Comment by woshibigsail** [comment]
![ss-logo](https://user-images.githubusercontent.com/18590663/49361343-c6b6a580-f716-11e8-8576-612ebc4bc337.gif)

**Comment by wuwansen** [comment]
![logo_ 1](https://user-images.githubusercontent.com/45579740/49412623-0aa5bb00-f7a8-11e8-9d73-8870da45c4f4.png)

**Comment by jessica-ccc** [comment]
![logo-shardingsphere](https://user-images.githubusercontent.com/45580025/49412654-2c9f3d80-f7a8-11e8-8ca7-c3a20e0400cf.jpg)

**Comment by jessica-ccc** [comment]
![logo-sphere-01](https://user-images.githubusercontent.com/45580025/49413029-8eac7280-f7a9-11e8-9a13-7196f45a92b4.jpg)

**Comment by tcmtang** [comment]
![image](https://user-images.githubusercontent.com/20944952/49417666-a68bf280-f7b9-11e8-9cd0-42e3842d1d7c.png)
![image](https://user-images.githubusercontent.com/20944952/49417675-b1468780-f7b9-11e8-9765-c162b2621d75.png)
![18801543548706_ pic](https://user-images.githubusercontent.com/20944952/49417730-ef43ab80-f7b9-11e8-9a54-0f5fd8450c3b.jpg)

尝试做的几个一并传上来

**Comment by jessica-ccc** [comment]
![logo-2-07](https://user-images.githubusercontent.com/45580025/49432981-dfdd5600-f7eb-11e8-8b65-5992c2f516ec.jpg)

**Comment by wuwansen** [comment]
![6](https://user-images.githubusercontent.com/45579740/49433226-74e04f00-f7ec-11e8-89a1-bc3c209e9e5a.png)

**Comment by wuwansen** [comment]
![logo-03](https://user-images.githubusercontent.com/45579740/49505923-b8ec5600-f8b7-11e8-9fff-3b3a93e7e1e4.png)

**Comment by wuwansen** [comment]
![logo-04](https://user-images.githubusercontent.com/45579740/49574460-72f8c600-f97b-11e8-921c-7447082279e6.png)

**Comment by wuwansen** [comment]
![logo-04](https://user-images.githubusercontent.com/45579740/49574565-af2c2680-f97b-11e8-8c35-d8523fe6173a.png)

**Comment by jessica-ccc** [comment]
![logo-3](https://user-images.githubusercontent.com/45580025/49631770-40f46c00-fa2e-11e8-964d-4e4476f2b9d0.jpg)

**Comment by terrymanu** [comment]
Thank you for all the logo designed. I think this one is really good. We want choose this one.

Thank you everybody.

![image](https://user-images.githubusercontent.com/5516298/50088003-b9cca280-023c-11e9-8881-84f1e773d569.png)
