### ISSUE TITLE
错误路由

### ISSUE THREAD

**Issue by slnc87** [sharding-sphere/sharding-sphere#1552]
### Which version of Sharding-Sphere did you use?
3.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
UPDATE user_collect
		 SET `d_content_name` = CASE `d_content_id`  
							WHEN ? THEN ?
							WHEN ? THEN ?
						END,
			`d_cpid` = CASE `d_content_id`
							WHEN ? THEN ?
							WHEN ? THEN ?
						END,
			`d_src` = CASE `d_content_id`
							WHEN ? THEN ?
							WHEN ? THEN ?
						END,
			`d_platform` = CASE `d_content_id`
							WHEN ? THEN ?
							WHEN ? THEN ?
						END,
			`d_service_type` = CASE `d_content_id`
							WHEN ? THEN ?
							WHEN ? THEN ?
						END 
		WHERE `d_login_name` = ? and `d_content_id` in
		 (?,?) ::: [[ceshi1, 测试1, ceshi2, 测试2, ceshi1, 测试1, ceshi2, 测试2, ceshi1, xingye, ceshi2, xingye, ceshi1, 2, ceshi2, 2, ceshi1, 测试2, ceshi2, 测试2, HGZS10, ceshi1, ceshi2]]

### Actual behavior
分表字段：d_login_name，对应值为：HGZS10，但在DMLStatement中使用WhereClauseParser，判定sql参数postionIndexMap时为0位开始。帮取到真实shardingValues值为ceshi1。造成表路由错误。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by slnc87** [comment]
> ### Which version of Sharding-Sphere did you use?
> 3.0.0
> 
> ### Which project did you use? Sharding-JDBC or Sharding-Proxy?
> Sharding-JDBC
> 
> ### Expected behavior
> 17:58:26.596 INFO io.shardingsphere.core.util.SQLLogger 71 log - SQLStatement: DMLStatement(super=AbstractSQLStatement(type=DML, tables=Tables(tables=[Table(name=user_collect, alias=Optional.absent())]), conditions=Conditions(orCondition=OrCondition(andConditions=[AndCondition(conditions=[Condition(column=Column(name=d_login_name, tableName=user_collect), operator=EQUAL, positionValueMap={}, positionIndexMap={0=0})])])), sqlTokens=[TableToken(skippedSchemaNameLength=0, originalLiterals=user_collect)], parametersIndex=3))
> 17:58:26.598 INFO io.shardingsphere.core.util.SQLLogger 71 log - Actual SQL: ui_ds_6 ::: UPDATE user_collect
> SET `d_content_name` = CASE `d_content_id`
> 
> ```
> 			WHEN ? THEN ?
> 		
> 			WHEN ? THEN ?
> 		
> 		END,
> 		`d_cpid` = CASE `d_content_id`
> 		
> 			WHEN ? THEN ?
> 		
> 			WHEN ? THEN ?
> 		
> 		END,
> 		`d_src` = CASE `d_content_id`
> 		
> 			WHEN ? THEN ?
> 		
> 			WHEN ? THEN ?
> 		
> 		END,
> 		`d_platform` = CASE `d_content_id`
> 		
> 			WHEN ? THEN ?
> 		
> 			WHEN ? THEN ?
> 		
> 		END,
> 		`d_service_type` = CASE `d_content_id`
> 		
> 			WHEN ? THEN ?
> 		
> 			WHEN ? THEN ?
> 		
> 		END 
> 	WHERE `d_login_name` = ? and `d_content_id` in
> 	 (  
> 		?
> 	 , 
> 		?
> 	 ) ::: [[ceshi1, 测试1, ceshi2, 测试2, ceshi1, 测试1, ceshi2, 测试2, ceshi1, xingye, ceshi2, xingye, ceshi1, 2, ceshi2, 2, ceshi1, 测试2, ceshi2, 测试2, HGZS10@ITVP, ceshi1, ceshi2]]
> ```
> Tue Dec 04 17:58:26 CST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
> 17:58:28.259 DEBUG org.apache.ibatis.logging.jdbc.BaseJdbcLogger 159 debug - <== Updates: 0
> 
> ### Actual behavior
> io.shardingsphere.core.parsing.parser.context.condition.Condition
> /**
> * Get condition values.
> *
> * @param parameters parameters
> * @return condition values
> */
> public List<Comparable> getConditionValues(final List parameters) {
> List<Comparable> result = new LinkedList<>(positionValueMap.values()); for (Entry entry : positionIndexMap.entrySet()) { Object parameter = parameters.get(entry.getValue()); if (!(parameter instanceof Comparable)) {
> throw new ShardingException("Parameter `%s` should extends Comparable for sharding value.", parameter);
> }
> if (entry.getKey() < result.size()) {
> result.add(entry.getKey(), (Comparable) parameter); } else { result.add((Comparable) parameter);
> }
> }
> return result;
> }
> In this Case:Object parameter = parameters.get(entry.getValue()); entry.getValue() is 0 but parameters's length is 23,So ShardingConditions will get the wrong route value。
> 
> ### Reason analyze (If you can)
> ### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
