### ISSUE TITLE
I am now test use the sharding-proxy ,but i cann't use "explain" command to see the Implementation plan

### ISSUE THREAD

**Issue by lvai125** [sharding-sphere/sharding-sphere#1557]
I am now test use the sharding-proxy ,but i cann't use "explain" command to see the Implementation plan

**Comment by lvai125** [comment]
proxy is not support "explain" command???????

**Comment by terrymanu** [comment]
We have no plan to implement `explain` command now.
Can you consider about provide a pull request to implement this?

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
