### ISSUE TITLE
Consider about make KeyGenerator Interface to support return String value

### ISSUE THREAD

**Issue by JpressProjects** [sharding-sphere/sharding-sphere#1558]
this is code in sharding-sphere：

```java
public interface KeyGenerator {
    Number generateKey();
}
```

KeyGenerator is only support  `Number` datatype in database， but we need other datatype in applications.

**Comment by tristaZero** [comment]
@JpressProjects  Hi, can you give me more detail about this issue? What are you going to do when you get other datatype of generatedKey？

**Comment by JpressProjects** [comment]
@tristaZero hi,  i use `VARCHAR` datatype in my application  and custom ShardingStrategyConfiguration for databases and tables with sharding-jdbc 2.x，but now, i have no solution to update sharding-jdbc 2.x to sharding-sphere 3.x

**Comment by tristaZero** [comment]
@JpressProjects Thanks for your reply, now we are going to make this interface to be,
```
public interface KeyGenerator {
    Comparable<?> generateKey();
}
```
Do you think that will be better ?

**Comment by JpressProjects** [comment]
@tristaZero thank u very much, i hava no any comment.
