### ISSUE TITLE
Sometimes shardingValue have been removed in hintShardingAlgorithm

### ISSUE THREAD

**Issue by yangpancode** [sharding-sphere/sharding-sphere#1560]
Sometimes shardingValue have been removed in hintShardingAlgorithm？
```
HintManager hintManager = HintManager.getInstance();
hintManager.setDatabaseShardingValue(ShardingActivitiConstant.ALL_DATASOURCES);
List<Order> orderList = orderService.getOrderList(); 
```
same code，some times the value of the shardingValue variable as follow.
`ListShardingValue(logicTableName=DB_TABLE_NAME, columnName=DB_COLUMN_NAME, values=[all])`
but sometimes, the value of the shardingValue variable as follow.
`ListShardingValue(logicTableName=DB_TABLE_NAME, columnName=DB_COLUMN_NAME, values=[])`
**Is shardingValue value limited?** 
```
@SuppressWarnings("unchecked")
    private static ShardingValue getShardingValue(final String logicTable, final Collection<Comparable<?>> values) {
        Preconditions.checkArgument(null != values && !values.isEmpty());
        return new ListShardingValue(logicTable, DB_COLUMN_NAME, values);
    }
```
ps: I use this version
```
<dependency>
	<groupId>io.shardingsphere</groupId>
	<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
	<version>3.0.0</version>
</dependency>

```
I find this class. 
HintManagerHolder.Class:
```
 private static final Multimap<String, Comparable<?>> DATABASE_SHARDING_VALUES = HashMultimap.create();
    
private static final Multimap<String, Comparable<?>> TABLE_SHARDING_VALUES = HashMultimap.create();
```
not threadlocal params, I think this may be problem!

**Comment by tristaZero** [comment]
@yangpancode Hi, sir thanks for your issue, we have fixed this problem in our next version on December 20th.

@terrymanu Please set the label of this issue to fixed or solved.

**Comment by terrymanu** [comment]
duplicate with #1467
