### ISSUE TITLE
Missing the data source name: 'ds0.5'

### ISSUE THREAD

**Issue by jie04baichi** [sharding-sphere/sharding-sphere#1563]
### Cause: java.lang.IllegalStateException: Missing the data source name: 'ds0.5'] with root cause

rules：sharding.jdbc.config.sharding.tables.user_info.database-strategy.inline.algorithm-expression=ds$->{user_id % 4 / 2}

**Comment by terrymanu** [comment]
config issue, please try to understand config rule, make sure sharding algorithm result can match data source name
