### ISSUE TITLE
I used the yaml configuration provided by the official website, but it was an exception when I started building the datasource

### ISSUE THREAD

**Issue by fanyaoxuan** [sharding-sphere/sharding-sphere#1570]
I used the yaml configuration provided by the official website, but it was an exception when I started building the datasource

exception:
![image](https://user-images.githubusercontent.com/22194156/49513388-c27fb900-f8cb-11e8-93fb-efefc8d8c75c.png)

ymal-config:
![image](https://user-images.githubusercontent.com/22194156/49513410-d9261000-f8cb-11e8-874b-8c0cccf4f04f.png)

version: 3.0.0
![image](https://user-images.githubusercontent.com/22194156/49513514-31f5a880-f8cc-11e8-96a8-7b87c920ec45.png)

**Comment by terrymanu** [comment]
Your yaml format is error, please see example or document and try to verify it
