### ISSUE TITLE
Initialization of TableMetaData takes too much time 

### ISSUE THREAD

**Issue by dunianbing** [sharding-sphere/sharding-sphere#1575]
### Which version of Sharding-Sphere did you use?
3.0.0.M3

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
The construction of ShardingDataSource costs less than 10 sec.
### Actual behavior
Base on Oracle, it costs 23 seconds to initialize an object of ShardingDataSource when the count of tables in default datasource is 167.

### Reason analyze (If you can)
During the initialization process, the ShardingMetaData will be construcated, in which the TableMetaData of all tables comming from default-datasource would be loaded. As there are 167 tables in my default datasource, the times of database access would be 167*3. Meanwhile  the database access is in turn, which is very time-consuming.

The key code is as follows:
* io.shardingsphere.core.metadata.table.executor.TableMetaDataInitializer
```
public Map<String, TableMetaData> load(final ShardingRule shardingRule) {
        Map<String, TableMetaData> result = new HashMap<>();
        try {
            result.putAll(loadShardingTables(shardingRule));
            result.putAll(loadDefaultTables(shardingRule)); // the entry 
        } catch (final SQLException ex) {
            throw new ShardingException(ex);
        }
        return result;
    }
```
* io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader

1. The method isTableExist() costs one database access
2. The method getColumnMetaDataList() costs two database access. One is getPrimaryKeys and the other is getColumns.
```
private Collection<TableMetaData> load(final String dataSourceName, final String catalog, final Collection<DataNode> dataNodes) throws SQLException {
        Collection<TableMetaData> result = new LinkedList<>();
        try (Connection connection = connectionManager.getConnection(dataSourceName)) {
            for (DataNode each : dataNodes) {
                result.add(new TableMetaData(
                        isTableExist(connection, catalog, each.getTableName()) ? getColumnMetaDataList(connection, catalog, each.getTableName()) : Collections.<ColumnMetaData>emptyList()));
            }
        }
        return result;
    }
```
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Just find an Oracle database such as db1 and create 100+ tables. It appears when initializing a ShardingDatasource.
> sharding.jdbc.config.sharding.default-data-source-name=db1

Could you explain the reason of loading the TableMetaData of default datasource? Is it necessary？
Looking forward for your reply. Thanks a lot!
### Example codes for reproduce this issue (such as a github link).
I will write a sample on github  if you need.

**Comment by terrymanu** [comment]
duplicate with #1131

**Comment by terrymanu** [comment]
duplicate with #1131

**Comment by terrymanu** [comment]
duplicated with #1131

**Comment by terrymanu** [comment]
duplicated with #1131
