### ISSUE TITLE
Subqueries are not supported in the in clause

### ISSUE THREAD

**Issue by fanyaoxuan** [sharding-sphere/sharding-sphere#1578]
![image](https://user-images.githubusercontent.com/22194156/49579064-44ccb380-f986-11e8-9c82-1fc5981290bc.png)

exception : 
![image](https://user-images.githubusercontent.com/22194156/49579116-5ca43780-f986-11e8-8384-1629eb982521.png)

**Comment by terrymanu** [comment]
Please read document first

**Comment by terrymanu** [comment]
http://shardingsphere.io/document/current/en/features/sharding/usage-standard/sql/
