### ISSUE TITLE
sql has been routed to the target db, but also pagination revision

### ISSUE THREAD

**Issue by posuixukong76** [sharding-sphere/sharding-sphere#1581]
## Bug Report

for example db1  db2，table order

sql has been routed to the target db2,  limit 15,15.but also pagination revision,sql rewrite as limit 0,30

### Which version of Sharding-Sphere did you use?
3.0.0 / 3.0.0.M4

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
use sharding-jdbc

### Expected behavior
select * from order where storeId=5 and (barcode is not null or barcode !='') limit 15,15
### Actual behavior
select * from order where storeId=5 and (barcode is not null or barcode !='') limit 0,30
### Reason analyze (If you can)
ParsingSQLRouter->method route->isSingleRouting=false->this.processLimit->limit->rewrite

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
sql:
select * from order where storeId=5 and (barcode is not null or barcode !='') limit 15,15
select * from order where storeId=5 and (firstcode in (1,2,3) or secondcode in (1,2,3) or thirdcode in(1,2,3)) limit 15,15

config:
sharding.jdbc.config.sharding.tables.order.database-strategy.standard.sharding-column: storeId

**Comment by lycying** [comment]
> This is because unexpected duplicated RoutingResult cause isSingleRouting=false.
> If isSingleRouting=false, the rewriting procedure will be triggered.
> To solve this problem, we need to get the correct isSingleRouting value.

+1

**Comment by tuohai666** [comment]
After investigation, this will not happen in 3.0.1.SNAPSHOT.
But another problem appeared. Please refer to https://github.com/sharding-sphere/sharding-sphere/issues/1643
All will be fixed in next release. Thanks.

**Comment by posuixukong76** [comment]
> This is because unexpected duplicated RoutingResult cause isSingleRouting=false.
> If isSingleRouting=false, the rewriting procedure will be triggered.
> To solve this problem, we need to get the correct isSingleRouting value.



> After investigation, this will not happen in 3.0.1.SNAPSHOT.
> But another problem appeared. Please refer to #1643
> All will be fixed in next release. Thanks.

thanks for your help~
