### ISSUE TITLE
The total number is wrong

### ISSUE THREAD

**Issue by advertIco** [sharding-sphere/sharding-sphere#1590]
### Which version of Sharding-Sphere did you use?
 3.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
SQL1：
SELECT rps.bus_id, sum(rps.count) FROM rps GROUP BY rps.bus_id
SQL2：
SELECT COUNT(1) FROM ( 
SELECT rps.bus_id, sum(rps.count) FROM rps GROUP BY rps.bus_id 
) TOTAL

Expected behavior 
SQL1 result：16 
SQL2 result： 16
### Actual behavior
SQL1 result：16 
SQL2 result： 20

**Comment by terrymanu** [comment]
Cannot support subsquery
