### ISSUE TITLE
分库分表查询结果出现脏数据，请帮忙验证一下

### ISSUE THREAD

**Issue by jie04baichi** [sharding-sphere/sharding-sphere#1592]
## Bug Report
场景：2个库，分表两个表
昨日我做了一个测试，我开启4个线程，每个线程分别插入100万条数据，大约执行1个小时半插入完毕，检查数据，入库的数据没有任何问题，id也没有重复，但在查询的时候出现问题，请看代码，
![image](https://user-images.githubusercontent.com/3363025/49777005-91730e80-fd39-11e8-84af-4c7e58602d83.png)
查询password 0得记录，总共12条，这个是因为我测试的时候启动了三次，所以有会12条记录，id是没有重复的，请看数据库记录：
数据库0：user_info_0
![image](https://user-images.githubusercontent.com/3363025/49777060-cda66f00-fd39-11e8-9ed5-cc562175d72c.png)
user_info_1:
![image](https://user-images.githubusercontent.com/3363025/49777078-d7c86d80-fd39-11e8-900f-409ddabe0866.png)
数据库1：user_info_0
![image](https://user-images.githubusercontent.com/3363025/49777090-e44cc600-fd39-11e8-9d67-cc46719a859b.png)
user_info_1
![image](https://user-images.githubusercontent.com/3363025/49777101-ed3d9780-fd39-11e8-879e-2b7bf07d7a95.png)

刚好12条记录，所以再次强调入库数据没有问题，现在请看查询结果：
![image](https://user-images.githubusercontent.com/3363025/49777154-34c42380-fd3a-11e8-97d2-993e0561e3fd.png)
结果却出现user_id是重复的，使用的是mybatis框架，请尽快抽时间答复，谢谢。

**Comment by jie04baichi** [comment]
分库键是user_id，但是用时间查询，sql语句打印出来，分别查了四个表，sql语句也没有问题。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by jie04baichi** [comment]
且下面四条数据出现的user_id：279023793651843070，这个id在数据库是不存在的记录。
