### ISSUE TITLE
How to load configuration from config center without restarting Sharding Proxy?

### ISSUE THREAD

**Issue by joooohnli** [sharding-sphere/sharding-sphere#1595]
## Question

Is there a way to load configuration from config center dynamically?

## For example: 
After adding a schema on config center, I hope the Sharding Rroxy could refresh and load configuration automatically or semi-automatic(by sending a command manually), that is, Then I can see that new schema by `show databases;`

How to achieve it, thx.

**Comment by tuohai666** [comment]
The feature you request will be availble in next release(maybe 3.1.0).
Not only adding but also deleting, please refer to https://github.com/sharding-sphere/sharding-sphere/issues/1664

You can try it by building dev branch yourself.
Just add new db under schema folder:
![image](https://user-images.githubusercontent.com/24643893/50399597-8600f800-07bb-11e9-8b49-23e5df9bcacb.png)
And get what you want:
![image](https://user-images.githubusercontent.com/24643893/50399611-9f09a900-07bb-11e9-93a9-7835b74de97c.png)
