### ISSUE TITLE
Suggest to optimize the DefaultKeyGenerator.generateKey()

### ISSUE THREAD

**Issue by feelwing1314** [sharding-sphere/sharding-sphere#1596]
## Feature Request

1. when lastTime <= currentMillis, throw new IllegalStateException is too violent.  suggest that, when moving backwards less than 5ms，sleep and wait。greater than 5ms throw new IllegalStateException。
2. when lastTime is a new time, the sequence always be 0. if the QPS is low，Most distributed id will be end with 0，if the distributed id is the sharding column，This will lead to the data to lean。suggest that ，when lastTime is a new time ，the sequence is a random number between in [0, 64).

**Comment by terrymanu** [comment]
The second point is really good, I just create new issue to process it dependent.

**Comment by terrymanu** [comment]
for 1st suggestion, I just add a static method setMaxTolerateTimeDifferenceMilliseconds() at 
DefaultKeyGenerator, user can adjust their expected threshold if they like, default value is zero.
