### ISSUE TITLE
Custom strategy

### ISSUE THREAD

**Issue by ralleman** [sharding-sphere/sharding-sphere#1607]
Hi. Could you tell me or point to some example or documentation that will help me write a custom sharding strategy please? In my case, I want to hold all sharding information in a table. Sharding won't be done purely on a modulus of customer id, rather specific customers may occupy whole shards, while other shards may be occupied by several customers. The rules are slightly complex but will be easy to code up once I see how the sharding distribution works in sharding-jdbc. Thanks.

**Comment by terrymanu** [comment]
https://github.com/sharding-sphere/sharding-sphere-example

**Comment by ralleman** [comment]
Thanks @terrymanu. Could you give me a specific example that I can work from? I can't find anything looking through the examples that matches the requirements.

**Comment by terrymanu** [comment]
Sharding strategy is written by java developers, you can dev them as you want. Please try to understand how to written Sharding strategy first, or use inline expression for simple situation mayby better.

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by ralleman** [comment]
Hi Terry. Given it's Christmas, I won't get to look at this until the new year I think.  I'll let you know if I work it out.
