### ISSUE TITLE
xa transactions seting

### ISSUE THREAD

**Issue by jie04baichi** [sharding-sphere/sharding-sphere#1608]
## Question

Our current sharding.jdbc.datasource is logically the same data source, such as (sub-database ds-0, ds-1), which itself supports transaction rollback between sub-libraries? If want to use xa transactions, must to have two sets of logical data sources?

**Comment by cherrylzhao** [comment]
hi，we can adapter normal physical datasource to xa transactional datasource witin sharding datasource，so there is no need to change your original setting. also we can provide @sharding transactional and api to switch transaction type as you like. these feature will add in document later

**Comment by cherrylzhao** [comment]
hi，we can adapter normal physical datasource to xa transactional datasource witin sharding datasource，so there is no need to change your original setting. also we can provide @sharding transactional and api to switch transaction type as you like. these feature will add in document later

**Comment by jie04baichi** [comment]
I am puzzled that sharding-jdbc 3.0.0 version now supports cross-database transactions, why need this xa transaction?

**Comment by jie04baichi** [comment]
> hi，we can adapter normal physical datasource to xa transactional datasource witin sharding datasource，so there is no need to change your original setting. also we can provide @sharding transactional and api to switch transaction type as you like. these feature will add in document later

I am puzzled that sharding-jdbc 3.0.0 version now supports cross-database transactions, why need this xa transaction?*

**Comment by jie04baichi** [comment]
ok，thanks！
