### ISSUE TITLE
Solve data lean problem when using DefaultKeyGenerator with low TPS

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1617]
DefaultKeyGenerator is using snowflake.

when current timestamp is a new time, the sequence always be zero. 
if TPS is low, most distributed sequence will be end with even, if the distributed sequence is sharding column will lead to the data lean. 
Suggest when current timestamp is a new time, the sequence is a random number between in [0, 64).

ref #1596

**Comment by terrymanu** [comment]
use vibrate instead of random sequence offset

**Comment by zxnzsz** [comment]
springmvc和hibernate框架需要jar报是什么？我启动tomcat报org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://shardingsphere.apache.org/schema/shardingsphere/masterslave]异常，麻烦解答下

**Comment by gchhy** [comment]
shadring-jdbc发现一个问题，java8以上版本，3.1.0版本查询时候，会报空指针异常，跟进源码发现实际问题是java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext，应该是jdk版本问题，希望能 兼容上，而且在解析语句的时候直接trycatch，导致问题无法直接暴露，是否能优化 。  private final ParsingRuleRegistry parsingRuleRegistry = ParsingRuleRegistry.getInstance();这个方法在init的时候异常

**Comment by chenwuwen** [comment]
我使用了4.1.1版本的sharding ,springboot的版本2.3.2.RELEASE。找不到DefaultKeyGenerator 这个类
