### ISSUE TITLE
Add the configuration of broadcast routing striction

### ISSUE THREAD

**Issue by leehom** [sharding-sphere/sharding-sphere#1626]
## Feature Request

In most time, broadcast routing is an exception，maybe missing  or wrong sharding rule, but broadcast routing can make data confused，and can't be recoveried，so adding the switch of if allowing is valuable

**Comment by terrymanu** [comment]
If the error cause is from user, ShardingSphere cannot do any more.
The most correct thing that ShardingSphere to do, it understand user's configuration and to it  correctly.
