### ISSUE TITLE
分库分表，如果用户表要根据表里的 userid 来分，订单表要根据表里的 orderid 来分，这个需求怎么写呢。

### ISSUE THREAD

**Issue by chinaTLJ** [sharding-sphere/sharding-sphere#1628]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by chinaTLJ** [comment]
If the user table is to be divided according to the 'userid' in the table, and the order table is to be divided according to the 'orderid' in the table, how do we write this requirement?

**Comment by terrymanu** [comment]
Hi, could you create a new issue by english?
