### ISSUE TITLE
在原有spring的事务模板里混用shardingDatasource和普通druidDataSource导致事务无法正常回滚

### ISSUE THREAD

**Issue by log4leo** [sharding-sphere/sharding-sphere#1640]
## 在原有spring的事务模板里混用shardingDatasource和普通druidDataSource导致事务无法正常回滚

看了下代码，shardingDatasource里用cachedConnections变量缓存了connections，这就导致了原来在同一个事务里使用了shardingDatasource的DAO和使用了普通druidDataSource的DAO执行时用的connection不一样，导致事务无法正常回滚，只能回滚其中一个

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
