### ISSUE TITLE
I meet a problem when boot the sharding-proxy-3.0.0 on centos7

### ISSUE THREAD

**Issue by a932846905** [sharding-sphere/sharding-sphere#1645]
## Question
I meet a problem when boot the sharding-proxy-3.0.0 on centos7，the boot logs on logs/stdout.log show：
[INFO ] 21:10:13.504 [main-SendThread(192.168.199.17:2181)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.199.17/192.168.199.17:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO ] 21:10:13.592 [main-SendThread(192.168.199.17:2181)] org.apache.zookeeper.ClientCnxn - Socket connection established to 192.168.199.17/192.168.199.17:2181, initiating session
[INFO ] 21:10:13.629 [main-SendThread(192.168.199.17:2181)] org.apache.zookeeper.ClientCnxn - Session establishment complete on server 192.168.199.17/192.168.199.17:2181, sessionid = 0x100000266760000, negotiated timeout = 40000
[INFO ] 21:10:13.642 [main-EventThread] o.a.c.f.state.ConnectionStateManager - State change: CONNECTED
[WARN ] 21:10:14.658 [main] c.a.jdbc.AbstractDataSourceBean - AtomikosDataSoureBean 'ds0': testQuery set - pool may be slower / you might want to consider setting maxLifetime instead...
[WARN ] 21:10:14.658 [main] c.a.jdbc.AbstractDataSourceBean - AtomikosDataSoureBean 'ds0': poolSize equals default - this may cause performance problems!
[WARN ] 21:10:14.667 [Sharding-Sphere-0] c.a.jdbc.AbstractDataSourceBean - AtomikosDataSoureBean 'ds1': testQuery set - pool may be slower / you might want to consider setting maxLifetime instead...
[WARN ] 21:10:14.667 [Sharding-Sphere-0] c.a.jdbc.AbstractDataSourceBean - AtomikosDataSoureBean 'ds1': poolSize equals default - this may cause performance problems!
[WARN ] 21:10:14.678 [Sharding-Sphere-1] c.a.jdbc.AbstractDataSourceBean - AtomikosDataSoureBean 'ds2': testQuery set - pool may be slower / you might want to consider setting maxLifetime instead...
[WARN ] 21:10:14.678 [Sharding-Sphere-1] c.a.jdbc.AbstractDataSourceBean - AtomikosDataSoureBean 'ds2': poolSize equals default - this may cause performance problems!
[INFO ] 21:10:15.121 [Sharding-Sphere-0] c.a.d.xa.XATransactionalResource - ds1: refreshed XAResource
[INFO ] 21:10:15.379 [Sharding-Sphere-1] c.a.d.xa.XATransactionalResource - ds2: refreshed XAResource
[INFO ] 21:10:15.629 [main] c.a.d.xa.XATransactionalResource - ds0: refreshed XAResource
[INFO ] 21:10:16.170 [Curator-Framework-0] o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
[INFO ] 21:10:16.181 [main-EventThread] org.apache.zookeeper.ClientCnxn - EventThread shut down
[INFO ] 21:10:16.181 [main] org.apache.zookeeper.ZooKeeper - Session: 0x100000266760000 closed
Exception in thread "main" java.lang.NullPointerException: Can not find opentracing tracer implementation class via system property `io.shardingsphere.opentracing.tracer.class`
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:250)
        at io.shardingsphere.opentracing.ShardingTracer.init(ShardingTracer.java:43)
        at io.shardingsphere.shardingproxy.Bootstrap.initOpenTracing(Bootstrap.java:111)
        at io.shardingsphere.shardingproxy.Bootstrap.startWithRegistryCenter(Bootstrap.java:96)
        at io.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:67)

how can i slove the problem ?

**Comment by a932846905** [comment]
######################################################################################################
# 
# If you want to configure orchestration, authorization and proxy properties, please refer to this file.
# 
######################################################################################################

orchestration:
  name: orchestration_ds
  overwrite: true
  registry:
    serverLists: 192.168.199.17:2181,192.168.199.18:2181,192.168.199.19:2181
    namespace: orchestration
authentication:
  username: root
  password: a6672196
props:
  proxy.transaction.enabled: true
  proxy.opentracing.enabled: true
  sql.show: true

**Comment by a932846905** [comment]
how to set the system property io.shardingsphere.opentracing.tracer.class ?

**Comment by tuohai666** [comment]
If you set proxy.opentracing.enabled: true, you must also set vm options blow:
Dio.shardingsphere.opentracing.tracer.class=org.apache.skywalking.apm.toolkit.opentracing.SkywalkingTracer 
And copy SkywalkingTracer to the lib directory.
Please refer to http://shardingsphere.io/document/current/en/features/orchestration/apm/

You can simply solve this problem by setting proxy.opentracing.enabled: false

**Comment by tuohai666** [comment]
Please put this question in a new ISSUE.
