### ISSUE TITLE
a  problem about master-salve data sync

### ISSUE THREAD

**Issue by a932846905** [sharding-sphere/sharding-sphere#1648]
## Question
i have run sharding-proxy 3.0.0 ok ,but i find a  problem about master-salve：when i insert data into sharding-proxy by using mysql command line, thats works ok, but i just find data in master database, slave database is empty, and i input the command "select * from " on command line, just return "Empty set"

this is my config-XXX.yaml:
schemaName: ylf
dataSources:
ds0:
url: jdbc:mysql://192.168.199.36:3306/ylf
username: root
password: XXXXXX
autoCommit: true
connectionTimeout: 30000
idleTimeout: 60000
maxLifetime: 1800000
maximumPoolSize: 65
ds0_slave0:
url: jdbc:mysql://192.168.199.37:3306/ylf
username: root
password: XXXXXX
autoCommit: true
connectionTimeout: 30000
idleTimeout: 60000
maxLifetime: 1800000
maximumPoolSize: 65
ds0_slave1:
url: jdbc:mysql://192.168.199.38:3306/ylf
username: root
password: XXXXXX
autoCommit: true
connectionTimeout: 30000
idleTimeout: 60000
maxLifetime: 1800000
maximumPoolSize: 65
ds1:
url: jdbc:mysql://192.168.199.51:3306/ylf
username: root
password: XXXXXX
autoCommit: true
connectionTimeout: 30000
idleTimeout: 60000
maxLifetime: 1800000
maximumPoolSize: 65
ds1_slave0:
url: jdbc:mysql://192.168.199.52:3306/ylf
username: root
password: XXXXXX
autoCommit: true
connectionTimeout: 30000
idleTimeout: 60000
maxLifetime: 1800000
maximumPoolSize: 65
ds1_slave1:
url: jdbc:mysql://192.168.199.53:3306/ylf
username: root
password: XXXXXX
autoCommit: true
connectionTimeout: 30000
idleTimeout: 60000
maxLifetime: 1800000
maximumPoolSize: 65
ds2:
url: jdbc:mysql://192.168.199.54:3306/ylf
username: root
password: XXXXXX
autoCommit: true
connectionTimeout: 30000
idleTimeout: 60000
maxLifetime: 1800000
maximumPoolSize: 65
ds2_slave0:
url: jdbc:mysql://192.168.199.55:3306/ylf
username: root
password: XXXXXX
autoCommit: true
connectionTimeout: 30000
idleTimeout: 60000
maxLifetime: 1800000
maximumPoolSize: 65
ds2_slave1:
url: jdbc:mysql://192.168.199.56:3306/ylf
username: root
password: XXXXXX
autoCommit: true
connectionTimeout: 30000
idleTimeout: 60000
maxLifetime: 1800000
maximumPoolSize: 65
shardingRule:
tables:
tb_order:
actualDataNodes: ms_ds${0..2}.tb_order${0..2}
tableStrategy:
inline:
shardingColumn: order_id
algorithmExpression: tb_order${order_id % 3}
keyGeneratorColumnName: order_id
bindingTables:
- tb_order
defaultDatabaseStrategy:
inline:
shardingColumn: user_id
algorithmExpression: ms_ds${user_id % 3}
defaultTableStrategy:
none:
defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator
masterSlaveRules:
ms_ds0:
masterDataSourceName: ds0
slaveDataSourceNames:
- ds0_slave0
- ds0_slave1
loadBalanceAlgorithmType: ROUND_ROBIN
ms_ds1:
masterDataSourceName: ds1
slaveDataSourceNames:
- ds1_slave0
- ds1_slave1
loadBalanceAlgorithmType: ROUND_ROBIN
ms_ds2:
masterDataSourceName: ds2
slaveDataSourceNames:
- ds2_slave0
- ds2_slave1
loadBalanceAlgorithmType: ROUND_ROBIN

this is my command record:
[root@WorkStation ~]# mysql -u root -h 192.168.199.57 -P 3307 -p
Enter password:
Welcome to the MySQL monitor. Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.6.0-Sharding-Proxy 3.0.0

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>minsert into tb_order (order_id,payment,payment_type,shipping_way,post_fee,status,user_id,create_time,update_time) values (78,'67.98',1,1,'19.00',2,38,NOW(),NOW());
ERROR 1046 (3D000): No database selected
mysql> use ylf;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> insert into tb_order (order_id,payment,payment_type,shipping_way,post_fee,status,user_id,create_time,update_time) values (78,'67.98',1,1,'19.00',2,38,NOW(),NOW());
Query OK, 1 row affected (0.15 sec)

mysql> select * from tb_order;
Empty set (0.22 sec)

mysql>

**Comment by tuohai666** [comment]
Does the data sync works well without sharding-proxy?

**Comment by tuohai666** [comment]
sharding-proxy will not do that. You need to enable MySQL's master-slave feature first.
