### ISSUE TITLE
java.sql.SQLSyntaxErrorException: Table 'ds1.t_order_order_items' doesn't exist

### ISSUE THREAD

**Issue by LX1993728** [sharding-sphere/sharding-sphere#1649]
`
sharding.jdbc.datasource.names=ds0,ds1,ds2
sharding.jdbc.datasource.ds0.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.ds0.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds0.url=jdbc:mysql://localhost:3306/ds0?serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds0.username=root
sharding.jdbc.datasource.ds0.password=root

sharding.jdbc.datasource.ds1.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.ds1.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds1.url=jdbc:mysql://localhost:3306/ds1?serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds1.username=root
sharding.jdbc.datasource.ds1.password=root

sharding.jdbc.datasource.ds2.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.ds2.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds2.url=jdbc:mysql://localhost:3306/ds2?serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds2.username=root
sharding.jdbc.datasource.ds2.password=root

sharding.jdbc.config.sharding.default-data-source-name=ds2
sharding.jdbc.config.sharding.default-database-strategy.inline.sharding-column=user_id
sharding.jdbc.config.sharding.default-database-strategy.inline.algorithm-expression=ds$->{user_id % 3}
sharding.jdbc.config.sharding.default-key-generator-class-name=liuxun.jpa.shard.config.SnowFlakeGenerator

sharding.jdbc.config.sharding.tables.t_order.actual-data-nodes=ds$->{0..2}.t_order$->{0..1}
sharding.jdbc.config.sharding.tables.t_order.table-strategy.inline.sharding-column=order_id
sharding.jdbc.config.sharding.tables.t_order.table-strategy.inline.algorithm-expression=t_order$->{order_id % 2}
sharding.jdbc.config.sharding.tables.t_order.key-generator-column-name=order_id
sharding.jdbc.config.sharding.tables.t_order_item.actual-data-nodes=ds$->{0..2}.t_order_item$->{0..1}
sharding.jdbc.config.sharding.tables.t_order_item.table-strategy.inline.sharding-column=order_id
sharding.jdbc.config.sharding.tables.t_order_item.table-strategy.inline.algorithm-expression=t_order_item$->{order_id % 2}
sharding.jdbc.config.sharding.tables.t_order_item.key-generator-column-name=order_item_id
sharding.jdbc.config.sharding.binding-tables=t_order,t_order_item

sharding.jdbc.config.sharding.tables.t_user.actual-data-nodes=ds$->{0..2}.t_user$->{0..1}
sharding.jdbc.config.sharding.tables.t_user.table-strategy.inline.sharding-column=user_id
sharding.jdbc.config.sharding.tables.t_user.table-strategy.inline.algorithm-expression=t_user$->{user_id % 2}
sharding.jdbc.config.sharding.tables.t_user.key-generator-column-name=user_id

sharding.jdbc.config.sharding.tables.t_product.actual-data-nodes=ds$->{0..2}.t_product$->{0..1}
sharding.jdbc.config.sharding.tables.t_product.database-strategy.inline.sharding-column=product_id
sharding.jdbc.config.sharding.tables.t_product.database-strategy.inline.algorithm-expression=ds$->{product_id % 2}
sharding.jdbc.config.sharding.tables.t_product.table-strategy.inline.sharding-column=product_id
sharding.jdbc.config.sharding.tables.t_product.table-strategy.inline.algorithm-expression=t_product$->{product_id % 2}
sharding.jdbc.config.sharding.tables.t_product.key-generator-column-name=product_id

sharding.jdbc.config.sharding.props.sql.show=true
`
我配置的三个库，每一种表都在每个库有两张表 包括t_order , t_order_item, t_user 和t_product 默认数据源是ds0 但是我根据金额范围查询订单时 出现了错误

`java.sql.SQLSyntaxErrorException: Table 'ds1.t_order_order_items' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.13.jar:8.0.13]
 `
该如何解决？这张表是shading自动生成的，并且在默认的数据源ds2中，.t_order_order_items

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
