### ISSUE TITLE
高并发情况下  偶现查询查询非常慢的情况

### ISSUE THREAD

**Issue by caixinning** [sharding-sphere/sharding-sphere#1656]
版本：
#Generated by Apache Maven
#Tue Oct 23 18:26:28 CST 2018
version=3.0.0
groupId=io.shardingsphere
artifactId=sharding-core

现象：
springmvc + mybatis + hikari + mysql，单表（该表有三个字段：自增id、varchar(512)、timestamp，未分库分表）insert操作，一般情况下，mapper.insert(Object)执行耗时为20ms，但在请求压力增大（平均每秒50次调用）后，偶尔会批量出现执行耗时5~7s的现象，异常通常在几秒内就会恢复。检查数据库日志，未发现slow query。
之前未使用sharding-jdbc时，从未出现过该现象。

配置：
centos 4核8G
sql.show=false
hikaricp.data={"db1":["hikaricp.data.write","hikaricp.data.read"]}

hikaricp.data.write.poolName=write
hikaricp.data.write.driverClassName=org.mariadb.jdbc.Driver
hikaricp.data.write.jdbcUrl=jdbc:mysql://xxx?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
hikaricp.data.write.readOnly=false
hikaricp.data.write.connectionTimeout=300000
hikaricp.data.write.idleTimeout=600000
hikaricp.data.write.maxLifetime=10800
hikaricp.data.write.maximumPoolSize=50
hikaricp.data.write.minimumIdle=5

hikaricp.data.read.poolName=read
hikaricp.data.read.driverClassName=org.mariadb.jdbc.Driver
hikaricp.data.read.jdbcUrl=jdbc:mysql://xxx?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
hikaricp.data.read.readOnly=true
hikaricp.data.read.connectionTimeout=300000
hikaricp.data.read.idleTimeout=600000
hikaricp.data.read.maxLifetime=10800
hikaricp.data.read.maximumPoolSize=20
hikaricp.data.read.minimumIdle=1

其它：
起初怀疑是slow query导致，检查数据库日志后未发现该表有slowquery；而后怀疑是连接池不足，将maximumPoolSize 由20调整为50，无效果。
个人猜测是否和sharding-jdbc executeEngine的执行策略有关？比如同时多个sql执行  是否会存在插队的现象？
谢谢！

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
