### ISSUE TITLE
In the case of high concurrency, the query is very slow.

### ISSUE THREAD

**Issue by caixinning** [sharding-sphere/sharding-sphere#1657]
Version：
#Generated by Apache Maven
#Tue Oct 23 18:26:28 CST 2018
version=3.0.0
groupId=io.shardingsphere
artifactId=sharding-core

Phenomenon：
Single table (the table has three fields: self-increment id, varchar (512), timestamp, undivided library sub-table) insert operation, in general, mapper.insert(Object) execution time is 20ms, but as request pressure increasese (average 50~200 calls per second), executions take 5-7 seconds occasionally , and usually recovers within a few seconds. Check the database log and no slow query was found.
This phenomenon has never been seen before sharding-jdbc was used.

Config：
centos 4core 8G
sql.show=false
hikaricp.data={"db1":["hikaricp.data.write","hikaricp.data.read"]}

hikaricp.data.write.poolName=write
hikaricp.data.write.driverClassName=org.mariadb.jdbc.Driver
hikaricp.data.write.jdbcUrl=jdbc:mysql://xxx?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
hikaricp.data.write.readOnly=false
hikaricp.data.write.connectionTimeout=300000
hikaricp.data.write.idleTimeout=600000
hikaricp.data.write.maxLifetime=10800
hikaricp.data.write.maximumPoolSize=50
hikaricp.data.write.minimumIdle=5

hikaricp.data.read.poolName=read
hikaricp.data.read.driverClassName=org.mariadb.jdbc.Driver
hikaricp.data.read.jdbcUrl=jdbc:mysql://xxx?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
hikaricp.data.read.readOnly=true
hikaricp.data.read.connectionTimeout=300000
hikaricp.data.read.idleTimeout=600000
hikaricp.data.read.maxLifetime=10800
hikaricp.data.read.maximumPoolSize=20
hikaricp.data.read.minimumIdle=1

Note：
Initially suspected to be caused by slow query, after checking the database log, the table was not found to have slowquery; then it was suspected that the connection pool was insufficient, and the maximumPoolSize was adjusted from 20 to 50, which had no effect.
Is personal guessing related to the execution strategy of sharding-jdbc executeEngine? For example, if there are multiple sql executions at the same time, will there be a queue or cut-line?
Could you please give me some advice? Thanks a lot!

**Comment by cherrylzhao** [comment]
it seems that we have fixed this issue in 3.1.0.m1，please do the test tomorrow when we published.

**Comment by cherrylzhao** [comment]
and please show the insert sql and sharding rule

**Comment by cherrylzhao** [comment]
and please show the insert sql and sharding rule

**Comment by cherrylzhao** [comment]
and please show the insert sql and sharding rule

**Comment by caixinning** [comment]
It was a single table. We introduced the sharding-jdbc framework and have not started sharding yet.
Sql: 
	<insert id="insert" parameterType="java.util.Map"  keyProperty="id" useGeneratedKeys="true">
		insert into record (id, date, memo)
		values (#{id,jdbcType=BIGINT}, #{date,jdbcType=TIMESTAMP}, #{description,jdbcType=VARCHAR})
	</insert>
Only used this above method.
The database supports tens of thousands threads concurrently, and I don't think it will become a bottleneck.

**Comment by cherrylzhao** [comment]
would you please upload your demo project to Github, let me have a try.
or modify your demo as we have done in [sharding-sphere-example](https://github.com/sharding-sphere/sharding-sphere-example.git)

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
