### ISSUE TITLE
Route to single data node

### ISSUE THREAD

**Issue by 799983050** [sharding-sphere/sharding-sphere#1659]
Route to single data node
    100% compatible（MySQL only, other database dialect is doing).

So that's the documentation，I can understand that，Single library multiple table strategy SQL  is 100% compatible.

**Comment by terrymanu** [comment]
What's mean `Single library multiple table strategy`?

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
