### ISSUE TITLE
Support to add new schemas and delete existed schema for orchestration

### ISSUE THREAD

**Issue by tristaZero** [sharding-sphere/sharding-sphere#1664]
Considering the suggestions from ShardingSphere community, I plan to add a new feather for Sharding-orchestration, which basically includes
1. User can add or delete scheme configurations in registry, e.g. zookeeper or etcd.
2. Registry pushes those changed events to all of applications online.
3. Applications online refresh their schema configurations to make those changes effective

**Comment by windyii** [comment]
It seems not to work in 3.1.0. We tested with a 2 instances cluster and Zookeeper for orchestration.  
Steps:
1.  Run 2 instances with same config
2.  Add a new schema in first sharding proxy and restart. New shema could be seen on zookeeper soon.
3.  Connect to second proxy, run 'show databases', but no new schema. 
Any bug?
