### ISSUE TITLE
it's too bad to update all table when sharding conditions is empty. 

### ISSUE THREAD

**Issue by frodoking** [sharding-sphere/sharding-sphere#1667]
when i use shardingsphere to update data without sharding condition column,  shardingsphere will add all table to routed data nodes, i think the impact of this is not acceptable.

the code as follow:
```
class StandardRoutingEngine {
    @Override
    public RoutingResult route() {
         // 57 line
          if (shardingConditions.getShardingConditions().isEmpty()) {
                routedDataNodes.addAll(route(tableRule, Collections.<ShardingValue>emptyList(), Collections.<ShardingValue>emptyList()));
            }
         // 79 line
    }
}
```
I hope author to upgrade this part of the code to minimize the impact.

**Comment by terrymanu** [comment]
I don't think so.
It is correct logic when if no sharding condition route all data nodes.
The logic is just like update sql without where condition.
I don't think there is anther logic should do.
How do you think and what is your expected?

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
