### ISSUE TITLE
 What logic is 3.1.0.M1 transaction?

### ISSUE THREAD

**Issue by jie04baichi** [sharding-sphere/sharding-sphere#1682]
## Question

What logic is 3.1.0.M1 transaction? If xa dependencies are configured,

		<dependency>
		    <groupId>io.shardingsphere</groupId>
		    <artifactId>sharding-transaction-2pc-xa</artifactId>
		    <version>${sharding-sphere.version}</version>
		</dependency>
Is xa open for all transactions? How do I know what type of transaction is currently?

**Comment by terrymanu** [comment]
Do you have a look at the example?

**Comment by terrymanu** [comment]
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
