### ISSUE TITLE
CommandExecutor.writeMoreResults问题

### ISSUE THREAD

**Issue by FloodDragon** [sharding-sphere/sharding-sphere#1698]
### Which version of ShardingSphere did you use?
master

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy

### Expected behavior
使用proxy代理2个数据库的数据读取

### Actual behavior
问题: writeMoreResults()问题,由于实际mysql存储单条数据比较大超过netty的
ChannelOutboundBuffer水位槽,导致frontendHandler锁住等待,channelWritabilityChanged高低水位变化未触发释放锁 。
原因: proxyFrontendFlushThreshold 如果count未达到这个阈值时 ChannelOutboundBuffer的64k已经被填满 但是由于不够flush条件 会出现死锁。
### Reason analyze (If you can)
问题: writeMoreResults()问题,由于实际mysql存储单条数据比较大超过netty的
ChannelOutboundBuffer水位槽,导致frontendHandler锁住等待,channelWritabilityChanged高低水位变化未触发释放锁 。
原因: proxyFrontendFlushThreshold 如果count未达到这个阈值时 ChannelOutboundBuffer的64k已经被填满 但是由于不够flush条件 会出现死锁。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by tuohai666** [comment]
很遗憾，你的表达存在矛盾。
如果单条超过水位，那么就需要调整水位，单条数据多大？据我所知，现在水位线是64兆。
又说没达到flush阈值，这跟水位没什么关系，没达到flush阈值，可以调小，比如1。
