### ISSUE TITLE
Initialization of TableMetaData takes too much time

### ISSUE THREAD

**Issue by gxgmy521** [sharding-sphere/sharding-sphere#1710]
I use Sharding-JDBC 3.0.0.M3 version。I find that the construction of ShardingDataSource costs  it costs 23 seconds to initialize an object of ShardingDataSource when the count of tables in default datasource is 167.

The key code is as follows:
```java
io.shardingsphere.core.metadata.table.executor.TableMetaDataInitializer
public Map<String, TableMetaData> load(final ShardingRule shardingRule) {
        Map<String, TableMetaData> result = new HashMap<>();
        try {
            result.putAll(loadShardingTables(shardingRule));
            result.putAll(loadDefaultTables(shardingRule)); // the entry 
        } catch (final SQLException ex) {
            throw new ShardingException(ex);
        }
        return result;
    }
```
```java
io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader
The method isTableExist() costs one database access
The method getColumnMetaDataList() costs two database access. One is getPrimaryKeys and the other is getColumns.
private Collection<TableMetaData> load(final String dataSourceName, final String catalog, final Collection<DataNode> dataNodes) throws SQLException {
        Collection<TableMetaData> result = new LinkedList<>();
        try (Connection connection = connectionManager.getConnection(dataSourceName)) {
            for (DataNode each : dataNodes) {
                result.add(new TableMetaData(
                        isTableExist(connection, catalog, each.getTableName()) ? getColumnMetaDataList(connection, catalog, each.getTableName()) : Collections.<ColumnMetaData>emptyList()));
            }
        }
        return result;
    }
```
I don't know why sharding-jdbc need load all the table's TableMetaData of default datasource? Is it necessary？why not just load the tablemetadata of the sharding tables. Looking forward for your reply. Thanks a lot!

**Comment by tuohai666** [comment]
In 3.1.0 which will release soon, ShardingSphere will not load all the table's TableMetaData by default.

**Comment by hl1221hl** [comment]
> In 3.1.0 which will be released soon, ShardingSphere will not load all the table's TableMetaData by default.

**3.1.0 release** is still very slow. there are 2000 tables in my database, it takes 3 minutes to initialize

**Comment by terrymanu** [comment]
you can switch off metadata check via configuration

**Comment by songxu** [comment]
> you can switch off metadata check via configuration

How to switch off metadata check?

**Comment by DaC1989** [comment]
<prop key="check.table.metadata.enabled">false</prop>
请问是这么配置的吗？
但是没作用。

**Comment by tuohai666** [comment]
This property is false by default.
How do you judge it not work?
