### ISSUE TITLE
How to fix "Initialized data sources can not be master-slave data sources"

### ISSUE THREAD

**Issue by cheerlxd** [sharding-sphere/sharding-sphere#1714]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

VERSION: 3.0.0

I learn to use "Sharding + Read-write splitting"(http://shardingsphere.io/document/current/en/manual/sharding-jdbc/configuration/config-spring-namespace/)  recently

when using official demo config, get an error on init,

`
<pre>
Caused by: java.lang.IllegalArgumentException: Initialized data sources can not be master-slave data sources.
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at io.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.checkDataSourceType(ShardingDataSource.java:77)
    at io.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.<init>(ShardingDataSource.java:59)
    at io.shardingsphere.shardingjdbc.spring.datasource.SpringShardingDataSource.<init>(SpringShardingDataSource.java:39)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
    ... 66 more
</pre>
`

**### my config xml like this**
`
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:sharding="http://shardingsphere.io/schema/shardingsphere/sharding"
       xmlns:master-slave="http://shardingsphere.io/schema/shardingsphere/masterslave"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
                        http://www.springframework.org/schema/beans/spring-beans.xsd 
                        http://www.springframework.org/schema/tx 
                        http://www.springframework.org/schema/tx/spring-tx.xsd
                        http://www.springframework.org/schema/context 
                        http://www.springframework.org/schema/context/spring-context.xsd
                        http://shardingsphere.io/schema/shardingsphere/sharding 
                        http://shardingsphere.io/schema/shardingsphere/sharding/sharding.xsd
                        http://shardingsphere.io/schema/shardingsphere/masterslave
                        http://shardingsphere.io/schema/shardingsphere/masterslave/master-slave.xsd">

    <context:component-scan base-package="io.shardingsphere.example" />

    
    
    <bean id="demo_master_ds" class="com.alibaba.druid.pool.DruidDataSource" destroy-method="close">
        <property name="url" value="jdbc:mysql://127.0.0.1:3306/demo_master?useUnicode=true&amp;characterEncoding=utf-8"/>
        <property name="username" value="root"/>
        <property name="password" value="123456"/>
        <property name="initialSize" value="10" />
        <property name="maxActive" value="20" />
        <property name="minIdle" value="0" />
        <property name="maxWait" value="60000"/>

        <property name="testOnBorrow" value="false"/>
        <property name="testOnReturn" value="false"/>
        <property name="testWhileIdle" value="true"/>

        <property name="timeBetweenEvictionRunsMillis" value="60000"/>
        <property name="minEvictableIdleTimeMillis" value="30000"/>
        <property name="validationQuery" value="select 1"/>
    </bean>

    <bean id="demo_ds_0" class="com.alibaba.druid.pool.DruidDataSource" destroy-method="close">
        <property name="url" value="jdbc:mysql://127.0.0.1:3306/demo_slave0?useUnicode=true&amp;characterEncoding=utf-8"/>
        <property name="username" value="root"/>
        <property name="password" value="123456"/>
        <property name="initialSize" value="10" />
        <property name="maxActive" value="20" />
        <property name="minIdle" value="0" />
        <property name="maxWait" value="60000"/>

        <property name="testOnBorrow" value="false"/>
        <property name="testOnReturn" value="false"/>
        <property name="testWhileIdle" value="true"/>

        <property name="timeBetweenEvictionRunsMillis" value="60000"/>
        <property name="minEvictableIdleTimeMillis" value="30000"/>
        <property name="validationQuery" value="select 1"/>
    </bean>

    <bean id="demo_ds_1" class="com.alibaba.druid.pool.DruidDataSource" destroy-method="close">
        <property name="url" value="jdbc:mysql://127.0.0.1:3306/demo_slave1?useUnicode=true&amp;characterEncoding=utf-8"/>
        <property name="username" value="root"/>
        <property name="password" value="123456"/>
        <property name="initialSize" value="10" />
        <property name="maxActive" value="20" />
        <property name="minIdle" value="0" />
        <property name="maxWait" value="60000"/>

        <property name="testOnBorrow" value="false"/>
        <property name="testOnReturn" value="false"/>
        <property name="testWhileIdle" value="true"/>

        <property name="timeBetweenEvictionRunsMillis" value="60000"/>
        <property name="minEvictableIdleTimeMillis" value="30000"/>
        <property name="validationQuery" value="select 1"/>
    </bean>

    <sharding:none-strategy id="noSharding" />

    <bean id="randomStrategy" class="io.shardingsphere.api.algorithm.masterslave.RandomMasterSlaveLoadBalanceAlgorithm" />

    <master-slave:data-source id="ds_master" master-data-source-name="demo_master_ds"
                              slave-data-source-names="demo_ds_0,demo_ds_1" strategy-ref="randomStrategy"/>

    <sharding:data-source id="shardingDataSource">
        <sharding:sharding-rule data-source-names="ds_master">
            <sharding:table-rules>
                <sharding:table-rule logic-table="order"
                                     actual-data-nodes="ds_master.order"
                                     table-strategy-ref="noSharding"
                                     database-strategy-ref="noSharding"/>
            </sharding:table-rules>
        </sharding:sharding-rule>
        <sharding:props>
            <prop key="sql.show">false</prop>
        </sharding:props>
    </sharding:data-source>
    

    <bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
        <property name="dataSource" ref="shardingDataSource" />
    </bean>
    <tx:annotation-driven />
    
    <bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
        <property name="dataSource" ref="shardingDataSource"/>
        <property name="mapperLocations" value="classpath*:META-INF/sqlmap.xml"/>
    </bean>
    
    <bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="basePackage" value="io.shardingsphere.example"/>
        <property name="sqlSessionFactoryBeanName" value="sqlSessionFactory"/>
    </bean>
</beans>

`

I hope can get someone reply, thanks

**Comment by cheerlxd** [comment]
> Hello @cheerlxd.
> I'm so sorry for this problem.
> The API for **Spring namespace xsd for Sharding and Master-slave** has changed in 3.0.0. You can check in release lists or [ISSUE #1203](https://github.com/sharding-sphere/sharding-sphere/issues/1203). And the document has not been updated in time.
> 
> If you want to use the master-slave related function, you can download the master branch of [sharding-sphere-example](https://github.com/sharding-sphere/sharding-sphere-example) repo and run first.
> 
> The master-slave example is in
> 
> ```
> sharding-jdbc-example
>     |- spring-namespace-nodep-example
>        |- spring-namespace-nodep-mybatis-example
> ```

thank you, I try it

**Comment by cheerlxd** [comment]
I get right result by using "the master branch of sharding-sphere-example" demo config, 

like this (version should >= 3.0.0M3 )

`    <bean id="demo_ds_master_0" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
        <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://localhost:3306/demo_ds_master"/>
        <property name="username" value="root"/>
        <property name="password" value="123456"/>
    </bean>
    
    <bean id="demo_ds_master_0_slave_0" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
        <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://localhost:3306/demo_ds_slave_0"/>
        <property name="username" value="root"/>
        <property name="password" value="123456"/>
    </bean>
    
    <bean id="demo_ds_master_0_slave_1" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
        <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://localhost:3306/demo_ds_slave_1"/>
        <property name="username" value="root"/>
        <property name="password" value="123456"/>
    </bean>

    <bean id="randomStrategy" class="io.shardingsphere.api.algorithm.masterslave.RandomMasterSlaveLoadBalanceAlgorithm" />
    <sharding:none-strategy id="noSharding"/>
    
    <sharding:data-source id="shardingDataSource">
        <sharding:sharding-rule data-source-names="demo_ds_master_0,demo_ds_master_0_slave_0,demo_ds_master_0_slave_1">

            
            <sharding:master-slave-rules>
                <sharding:master-slave-rule id="demo_ds_ms_0" master-data-source-name="demo_ds_master_0"
                                            slave-data-source-names="demo_ds_master_0_slave_0, demo_ds_master_0_slave_1"
                                            strategy-ref="randomStrategy"/>
            </sharding:master-slave-rules>

            
            <sharding:table-rules>
                <sharding:table-rule logic-table="t_order" actual-data-nodes="demo_ds_ms_0.t_order_${0..1}"
                                     database-strategy-ref="noSharding" table-strategy-ref="orderTableStrategy"/>
            </sharding:table-rules>
        </sharding:sharding-rule>
    </sharding:data-source>`

**Comment by KomachiSion** [comment]
Great! Thanks for your feedback.
If there are no other problems, we will update the documents as soon as possible and close this issue.
