### ISSUE TITLE
hint strategy sometimes cannot hit expected table

### ISSUE THREAD

**Issue by stoneSpoon** [sharding-sphere/sharding-sphere#1716]
[hint code.zip](https://github.com/sharding-sphere/sharding-sphere/files/2729287/hint.code.zip)
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
 3.1.0.M1  and 3.1.0 
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
hint strategy will work ok  for every table in my project.
table:order_item  selcect、update operate  can hit expect table 

### Actual behavior
table:order_item_goods_out  insert\update can hit expect table but .select operate cannot hit expect table. 
### Reason analyze (If you can)
I don't understand this, the hint strategy is used in the same way in different tables but in fact the execution is different in different tables

**Comment by tristaZero** [comment]
Hi, thanks  for your issue. This error occurs because column `row` of order_item_goods_out is a keyword for antlr parsing of MySQL. We will fix this bug in next version, if you want to avoid this situation, please change the column name of `row`.

@codefairy08 , please keep you updated here.
