### ISSUE TITLE
sharding-proxy no record “Error Code: 3054. Unknown exception: Index: 0, Size: 0”

### ISSUE THREAD

**Issue by tonnixu** [sharding-sphere/sharding-sphere#1718]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy 3.1.0
### Actual behavior
09:47:14	select distinct merc_no from t_order where tx_dt in ('20180103', '20190106') LIMIT 0, 100	Error Code: 3054. Unknown exception: Index: 0, Size: 0	0.066 sec

**Comment by terrymanu** [comment]
Can you provide all log of this exception, sharding rule configuration and table structure?

**Comment by tonnixu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    




    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 01/6/2019 11:03，张亮<notifications@github.com> wrote： 


Can you provide all log of this exception, sharding rule configuration and table structure?

**Comment by tonnixu** [comment]
######################################################################################################
# 
# Here you can configure the rules for the proxy.
# This example is configuration of sharding rule.
#   
# If you want to use sharding, please refer to this file; 
# if you want to use master-slave, please refer to the config-master_slave.yaml.
# 
######################################################################################################

schemaName: db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3307/db0?serverTimezone=UTC&useSSL=false
    username: root
    password: root@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://127.0.0.1:3307/db1?serverTimezone=UTC&useSSL=false
    username: root
    password: root@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50 
  ds_2:
    url: jdbc:mysql://127.0.0.1:3308/db2?serverTimezone=UTC&useSSL=false
    username: root
    password: root@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50 
  ds_3:
    url: jdbc:mysql://127.0.0.1:3308/db3?serverTimezone=UTC&useSSL=false
    username: root
    password: root@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50 

shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_0.t_order_${0..1}, ds_1.t_order_${2..3}, ds_2.t_order_${4..5},ds_3.t_order_${6..7}
      databaseStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: ds_${order_id.toInteger() % 8 / 2}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_${order_id.toInteger() % 8}
      keyGeneratorColumnName: order_id
  bindingTables:
    - t_order
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator

**Comment by terrymanu** [comment]
Can you provide all log of this exception and table structure?

**Comment by tonnixu** [comment]
[INFO ] 07:50:17.268 [ShardingSphere-Command-13] i.s.s.backend.AbstractBackendHandler - java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:608)
        at io.shardingsphere.core.merger.dql.DQLMergeEngine.<init>(DQLMergeEngine.java:65)
        at io.shardingsphere.core.merger.MergeEngineFactory.newInstance(MergeEngineFactory.java:57)
        at io.shardingsphere.shardingproxy.backend.jdbc.JDBCBackendHandler.merge(JDBCBackendHandler.java:110)
        at io.shardingsphere.shardingproxy.backend.jdbc.JDBCBackendHandler.execute(JDBCBackendHandler.java:98)
        at io.shardingsphere.shardingproxy.backend.jdbc.JDBCBackendHandler.execute0(JDBCBackendHandler.java:82)
        at io.shardingsphere.shardingproxy.backend.AbstractBackendHandler.execute(AbstractBackendHandler.java:52)
        at io.shardingsphere.shardingproxy.transport.mysql.packet.command.query.text.query.ComQueryPacket.execute(ComQueryPacket.java:82)
        at io.shardingsphere.shardingproxy.frontend.mysql.CommandExecutor.run(CommandExecutor.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by terrymanu** [comment]
Hi, can you provide table structure?

**Comment by tonnixu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
 drop table if exists t_order ;create table t_order(ID bigint auto_increment not null,order_id varchar(35) not null,merc_no varchar(16) not null,tx_dt varchar(8) not null,tx_amt decimal(18,2) not null,primary key(id));



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 01/7/2019 11:47，张亮<notifications@github.com> wrote： 


Hi, can you provide table structure?
