### ISSUE TITLE
show partitions from t_order

### ISSUE THREAD

**Issue by tonnixu** [sharding-sphere/sharding-sphere#1719]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
3.1.0
### Describe the feature you would like.
support "show partitions from t_order;"

**Comment by tonnixu** [comment]
how to support this command. "show partitions from t_order;"

**Comment by terrymanu** [comment]
Hi, I don't think `show partitions` is a correct SQL.
So I just set this issue as invalid
