### ISSUE TITLE
当sql列的别名有的as 有的没用的时候，就会出现路由错误

### ISSUE THREAD

**Issue by jichaof1** [sharding-sphere/sharding-sphere#1723]
例如select
		  id,
		  order_id "orderId",
		  vendor_id as "vendorId",
		  vendor_warehouse_id "vendorWarehouseId",
		  vendor_type "vendorType",
		  area_type "areaType",
		  creator ,
		  create_date "createDate",
		  version
		from
			t_order_choose_warehouse
		where
			order_id = #{orderId}
其中vendorId这列用as指定别名的时候，就会出现路由错误~

**Comment by jichaof1** [comment]
更新到3.1.0改问题已解决

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
