### ISSUE TITLE
About OpenTracing can not worked question

### ISSUE THREAD

**Issue by yuxiao97** [sharding-sphere/sharding-sphere#1734]
## Question
When I use OpenTracing collect infomention to Sky-walking，the config like this:-Dio.shardingsphere.opentracing.tracer.class=org.apache.skywalking.apm.toolkit.opentracing.SkywalkingTracer and in Application starter, i write ShardingTracer.init(), can not worked, found java.lang.NullPointerException: null in skywakling-collector log.
or i use ShardingTracer.init(new SkywalkingTracer()) only can not worked yet, 

sharding-jdbc version 3.1.0, sky-walking 5.0GA

![image](https://user-images.githubusercontent.com/27430795/51017780-3c345200-15b0-11e9-8e45-a7ae072629f8.png)

**Comment by tuohai666** [comment]
**Method 1: Inject the Tracer implementation class provided by APM system through reading system parameters.**

1. This is to say copy SkywalkingTracer's jar to your lib directory.
2. Modify SkyWalking's component-libraries.yml, add:
Sharding-Sphere:
  id: 44
  languages: Java

**Comment by tuohai666** [comment]
The jar is actually apm-toolkit-opentracing-5.0.0-GA.jar

**Comment by tuohai666** [comment]
You may also try:

Sharding-Sphere:
id: 34
languages: Java

**Comment by yuxiao97** [comment]
It worked, all config is :
1:In jvm opts -Dio.shardingsphere.opentracing.tracer.class=org.apache.skywalking.apm.toolkit.opentracing.SkywalkingTracer
2:In main function write ShardingTracer.init();
 public static void main(String[] args) {
        SpringApplication application = new SpringApplication(UCServerApplication.class);
        application.run(args);
        ShardingTracer.init();
    }
3:add Sky-walking config : config/component-libraries.yml
Sharding-Sphere:
id: 34
languages: Java

others add maven dependency:
<dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-opentracing</artifactId>
            <version>5.0.0-GA</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-opentracing</artifactId>
            <version>3.1.0</version>
        </dependency>

**Comment by tuohai666** [comment]
Great!

**Comment by yuxiao97** [comment]
Another question,when pression application,query is very low,why?
![image](https://user-images.githubusercontent.com/27430795/51032303-76b2e480-15da-11e9-80b7-f565d8ff4854.png)

**Comment by tuohai666** [comment]
ShardingSphere has switched to ANTLR parser which a little slower than before since 3.1.0.
But consuming 3s in parsing is unexpected. If you have doubt, please open another issue to discuss it.
BTW, there's cache mechanism, if you use prepared statement, the parsing time of next query will be 0.

**Comment by yuxiao97** [comment]
>           ShardingSphere has switched to ANTLR parser which a little slower than before since 3.1.0.
> But consuming 3s in parsing is unexpected. If you have doubt, please open another issue to discuss it.
> BTW, there's cache mechanism, if you use prepared statement, the parsing time of next query will be 0.

OK, I open another issue:[#1738](https://github.com/sharding-sphere/sharding-sphere/issues/1738)
