### ISSUE TITLE
Sharding JDBC does not keep alive minIdle db pools

### ISSUE THREAD

**Issue by TreeZhiyuan** [sharding-sphere/sharding-sphere#1737]
Here is my configure properties:
#database
sharding.jdbc.datasource.names=user-center
sharding.jdbc.datasource.initialSize=5
sharding.jdbc.datasource.minIdle=5
sharding.jdbc.datasource.maxActive=10
sharding.jdbc.datasource.maxWait=60000
sharding.jdbc.datasource.validationQuery=SELECT 'x'
sharding.jdbc.datasource.timeBetweenEvictionRunsMillis=60000
sharding.jdbc.datasource.minEvictableIdleTimeMillis=300000
sharding.jdbc.datasource.testWhileIdle=true
sharding.jdbc.datasource.testOnBorrow=false
sharding.jdbc.datasource.testOnReturn=false
sharding.jdbc.datasource.poolPreparedStatements=true
sharding.jdbc.datasource.maxPoolPreparedStatementPerConnectionSize=10

### Expected behavior
When my spring boot project is starting there are 5 db connections, but several minutes later without any operations all 5 db connections is discarded
there should be at least 5 db connections always alive 

### Actual behavior
at least 5 db connections always alive 

Ps,
the version of Sharding-JDBC in my project is 3.1.0
the database type is com.alibaba.druid.pool.DruidDataSource

Any suggestion that which part of my configuration got wrong?

**Comment by yuxiao97** [comment]
go home!

**Comment by tuohai666** [comment]
Please set keepAlive=true, otherwise, connections will be closed after minEvictableIdleTimeMillis.

**Comment by TreeZhiyuan** [comment]
thanks for your reply
Adding keepAlive=true doesn't work, the issue is still there

**Comment by TreeZhiyuan** [comment]
> Please set keepAlive=true, otherwise, connections will be closed after minEvictableIdleTimeMillis.

thanks for your reply
Adding keepAlive=true doesn't work, the issue is still there

**Comment by tuohai666** [comment]
Please your druid version.

**Comment by TreeZhiyuan** [comment]
druid version is 1.1.9

**Comment by tuohai666** [comment]
keepAlive parameter is introduced 1.0.28 and expected to be work.
I suggest you check the properties **very carefully** and try again.
If the keepAlive still can't work, you should test druid standalone to find out whether ShardingSphere caused this problem.
