### ISSUE TITLE
When performance testing,query is very low,MySQL

### ISSUE THREAD

**Issue by yuxiao97** [sharding-sphere/sharding-sphere#1738]
When performance testing,query is very low,MySQL

![image](https://user-images.githubusercontent.com/27430795/51033901-da8bdc00-15df-11e9-8e45-806ab224c08c.png)

**Comment by tuohai666** [comment]
Provide your environment like cpu, memory etc.
Your config, sql etc.


And **DO** fill in the pattern:

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by tuohai666** [comment]
ShardingSphere has switched to ANTLR parser which a little slower than before since 3.1.0. But consuming 3s in parsing is unexpected. 
BTW, there's cache mechanism, if you use prepared statement, the parsing time of next query will be 0.

**Comment by yuxiao97** [comment]
>           ShardingSphere has switched to ANTLR parser which a little slower than before since 3.1.0. But consuming 3s in parsing is unexpected.
> BTW, there's cache mechanism, if you use prepared statement, the parsing time of next query will be 0.
Yes,use Druid, version is 1.1.9,my config like this:
```
sharding.jdbc.datasource.names=my-demo
sharding.jdbc.datasource.my-demo.initialSize=5
sharding.jdbc.datasource.my-demo.minIdle=5
sharding.jdbc.datasource.my-demo.maxActive=50
sharding.jdbc.datasource.my-demo.maxWait=60000
sharding.jdbc.datasource.my-demo.validationQuery=SELECT 1 FROM DUAL
sharding.jdbc.datasource.my-demo.timeBetweenEvictionRunsMillis=30000
sharding.jdbc.datasource.my-demo.minEvictableIdleTimeMillis=300000
sharding.jdbc.datasource.my-demo.testWhileIdle=true
sharding.jdbc.datasource.my-demo.testOnBorrow=false
sharding.jdbc.datasource.my-demo.testOnReturn=false
sharding.jdbc.datasource.my-demo.poolPreparedStatements=true
sharding.jdbc.datasource.my-demo.maxPoolPreparedStatementPerConnectionSize=50
sharding.jdbc.datasource.my-demo.keepAlive=true
```
SQL is easy, use param(not sharding-key) query object, like select _column_ from user where mobile = ?

**Comment by yuxiao97** [comment]
> Provide your environment like cpu, memory etc.
2U 4G
> Your config, sql etc.
select * from user_1..32 where mobile = ?
> ## Bug Report
> **For English only**, other languages will not accept.
> 
> Before report a bug, make sure you have:
> 
> * Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
> * Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).
> 
> Please pay attention on issues you submitted, because we maybe need more details.
> If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
> 
> Please answer these questions before submitting your issue. Thanks!
> 
> ### Which version of ShardingSphere did you use?  ----> 3.1.0
> ### Which project did you use? Sharding-JDBC or Sharding-Proxy?  ---->  Sharding-JDBC 3.1.0
> ### Expected behavior
400 threads test 300 seconds, 95% in 1000ms.
> ### Actual behavior
400 thread test 300 seconds, 95% 2000±200ms.
> ### Reason analyze (If you can)
In every threads request, first operate db is very slowly, other db operation fast, so why?

**Comment by tuohai666** [comment]
Your machine can't afford 400 threads, i don't think your expectation is right.
And the machine is not suitable for a performance test.

**Comment by yuxiao97** [comment]
> Your machine can't afford 400 threads, i don't think your expectation is right.
> And the machine is not suitable for a performance test.

I use arthas trace then found this data

![image](https://user-images.githubusercontent.com/27430795/51082164-df19d700-173c-11e9-8e28-e35aa0437d28.png)

**Comment by tuohai666** [comment]
What does this mean? Did you see my message above and what do you say? 

> Your machine can't afford 400 threads, i don't think your expectation is right.
> And the machine is not suitable for a performance test.

If you insist that your expectation is right, you should share more reasonable infomation. For example, without Sharding-JDBC and with the same threads count, you got the respond time 95% in 1000ms.

**Comment by yuxiao97** [comment]
> What does this mean? Did you see my message above and what do you say?
> 
> > Your machine can't afford 400 threads, i don't think your expectation is right.
> > And the machine is not suitable for a performance test.
> 
> If you insist that your expectation is right, you should share more reasonable infomation. For example, without Sharding-JDBC and with the same threads count, you got the respond time 95% in 1000ms.

I change my device config and fix application logic then ok.
