### ISSUE TITLE
强制路由不能和自动分表配置共用

### ISSUE THREAD

**Issue by cnderrick** [sharding-sphere/sharding-sphere#251]
在某些分库分表业务场景下，分库的字段只需要在数据库上标注，做到水平拆分；根据另外的一些字段再做分表。

目前sharding-jdbc在配置了根据where后面的Columns分库分表后，每张子表中必须冗余分库的字段。想通过强制路由的方式将分库的字段set进去这样每张表就不需要冗余字段，后面的分表依然按照自动分表的规则。

但是我测试后的结果发现在使用强制路由后默认自动根据Columns分表的规则就失效了，在强制路由时调用设置分表字段和内容后，就可以正常走分表的代码。这里是否可以做的更智能一些，两者兼容。

我使用的是的1.4.1版本的包

**Comment by terrymanu** [comment]
是个好建议，未来可以考虑。
不过分片db需要带sharding-key也基本是业界共识，因此加上sharding-key也是不错的选择。

**Comment by cnderrick** [comment]
@terrymanu  db的分片在where语句中加上sharding-key是没错的，因为不想每张表都中加上这个sharding-key做冗余字段，就只能用强制路由，但其实我想用的是自动分表功能。所以最后改为用spring的动态数据源来控制分库，sharding-jdbc作自动分表用。

**Comment by terrymanu** [comment]
merge this issue to #1289
