### ISSUE TITLE
配置化同库多表采用多连接多线程（提升性能）还是单连接单线程（保持acid）

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#422]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?

2.0.0.M1

### Expected behavior

由于Druid连接池不支持多线程访问，因此对于同一库上的多个分表，采用的是单线程访问。
未来会做提升，增加配置项，让使用方决定是否开启多线程。
未来修改方案：
配置是否同一库的多表采用不同的连接。true，则开启多线程，缺点是同库的多表无法保持在一个acid事务中；false则同库的多表采用一个连接，串行执行（即目前的方式）。

**Comment by githublaohu** [comment]
还是多线程吧，保证流程的简单性。
一库多表，在性能上没有什么优势。只是一种过渡阶段。没必要为一个过渡阶段。多实现一个流程。

**Comment by wgou** [comment]
未来这个方案相当相当值得期待，希望尽快能出来就完美了。

**Comment by wujun8** [comment]
@terrymanu 目前版本实现是多线程处理，前面说的配置开启是不是没有提供？
