### ISSUE TITLE
柔性事务无法保证最终一致性的问题

### ISSUE THREAD

**Issue by aftersss** [sharding-sphere/sharding-sphere#578]
经过查看源码后，我觉得柔性事务的实现存在较大问题，无法保证最终一致性。
比如我需要往A、B两个库分别插入一条数据，sharding-jdbc柔性事务的实现方式为：
1. 执行A库插入sql前先往一个独立的数据源C写入redo log
2. 执行A库插入sql。
3. 删除第一步刚刚插入的redolog
4. 执行B库插入sql前先往一个独立的数据源C写入redo log
5. 执行B库插入sql。
6. 删除第四步刚刚插入的redolog

这里假设执行到第三步时机器宕机，则后续的操作不会再执行，造成了不一致。
如果需要保证最终一致性，我认为应当调整顺序，先往数据源C中写入本次事务所有的redo log，然后逐条回放redo log并删除。
顺序应修改为：

1. 执行A库插入sql前先往一个独立的数据源C写入redo log（标记为`等待执行`状态）
2. 执行B库插入sql前先往一个独立的数据源C写入redo log（标记为`等待执行`状态）
2. 当调用事务管理器的end方法时，首先把本事务相关的所有redo log原子更新为`可执行`状态
3. 按顺序逐条执行redo log（出错可以同步重试几次），每执行完一条删除一条。
4. 待到所有redo log回放完毕（或者超过同步重试次数上限时），返回事务成功。（如果有出错，让后续的异步任务来保证最终一致性）。

上述步骤中的`等待执行`和`可执行`的状态变迁是必要的，考虑某次事务需要执行三条sql（对应三条redo log），写完两条redo log后机器宕机，由于redo log的状态仍为`等待执行`状态，异步任务不应该执行此log，而且在判断到此状态的log在创建之后超过一定时间后应该删除。

**Comment by terrymanu** [comment]
感谢提供建议。这个建议很有价值。我们对柔性事务提升时会参考这个建议去做。
目前柔性事务暂时无更新计划，可能要等几个迭代后再说。因此如果您感兴趣，可以提供相关的pr，谢谢

**Comment by terrymanu** [comment]
BASE transaction will re-design at 3.1.0, so this issue is expired
