### ISSUE TITLE
建议/讨论 LOGIC_SCHEMA_NAME 是否应该放在 sharding-jdbc-server 外面

### ISSUE THREAD

**Issue by limingwei** [sharding-sphere/sharding-sphere#620]
0. 前置问题，当前的 DataSourceManager 硬性依赖了sharding-config.yaml
  是不是可以改为，sharding-jdbc-server只是依赖一个DataSource，而不一定要求是ShardingDataSource

1. sharding-jdbc-server中不指定LOGIC_SCHEMA_NAME，通过SHOW DATABASES或DbMeta之类的方式，从底下的DataSource中取；把LOGIC_SCHEMA_NAME放在底下的ShardingDataSource中

1.1. 如果是的话，ComInitDbPacket中的 if not LOGIC_SCHEMA_NAME, return Unknown database，是否也可以不再检查

**Comment by terrymanu** [comment]
未来打算支持多logic schema支持的，目前暂时先把server跑稳定了，下个版本会对这里进行升级

**Comment by limingwei** [comment]
![qq 20180228142847](https://user-images.githubusercontent.com/1704535/36773382-572a7f3c-1c94-11e8-913d-89d80d6308b9.png)
![qq 20180228143246](https://user-images.githubusercontent.com/1704535/36773383-57938892-1c94-11e8-8b25-e2e312188a9e.png)

**Comment by limingwei** [comment]
在本地尝试的时候，大概改到了这两个地方

**Comment by terrymanu** [comment]
代码片段看不出全貌，如果有需要讨论的，请提供多一点信息吧

**Comment by beckhampu** [comment]
Please refer to #1046  for the solution
