### ISSUE TITLE
关于事务隔离级别

### ISSUE THREAD

**Issue by ztgoto** [sharding-sphere/sharding-sphere#629]
version: 2.0.3
发现在sharding-jdbc拿到的连接 取到的事务隔离级别都是 1
但我们的mysql的事务隔离级别是4（REPEATABLE_READ）
那这种情况在与spring集成时是否得明确指定事务隔离级别，否则是没办法取到mysql设置的隔离级别的？

**Comment by terrymanu** [comment]
通过jdbc可以获取事务隔离级别么，如果可以，可以试试sharding jdbc能否取到？

**Comment by ztgoto** [comment]
druid数据源和jdbc都是可以的，我们尝试修改了数据库的全局事务隔离级别，在druid或jdbc上都能正确反映出来。
而sharding-jdbc不行，主要原因来至于sharding-jdbc中AbstractConnectionAdapter transactionIsolation使用的是TRANSACTION_READ_UNCOMMITTED，在并未手动设置sharding-jdbc连接时的事务隔离级别情况下 取到的就是TRANSACTION_READ_UNCOMMITTED 这个默认值，并非为数据库中设置的事务隔离级别
