### ISSUE TITLE
Add sharding-metrics module

### ISSUE THREAD

**Issue by CharlesMaster** [sharding-sphere/sharding-sphere#651]
Sharding-metrics implementation is in sharding-jdbc-metrics module.

Sharding-core is going to be independent in the future.

On the architecture, core support plugin for metrics, sharding-jdbc and sharding-proxy is the combination  of core, metrics, transaction.

On demand, sharding-jdbc metrics should be divided into two layers, unified global data and data on each sharding piece. The metrics of statistics can refer to druid and hikariCP.

We prioritize sharding-metrics,we can also count other database metrics.And we need to completely separate from JDBC, because sharding proxy is still used.

**Comment by terrymanu** [comment]
expired for now, just close it
