### ISSUE TITLE
AbstractConnectionAdapter.cachedConnections  多线程情况下commit 是不是乱了？

### ISSUE THREAD

**Issue by chenliuyang1989** [sharding-sphere/sharding-sphere#724]
1. cachedConnections 两个线程去获取connection，都会放在同一个cachedConnections 列表，其中一个发起commit，会不会把另外一个线程获取到的connection也commit了。
2. cacheConnections 应该放在线程变量里才对吧

**Comment by terrymanu** [comment]
请问实际测试出问题了么

**Comment by terrymanu** [comment]
No response for too long time, and we cannot reproduce it. Let me close it
