### ISSUE TITLE
在Mybatis中使用RoundRobinMasterSlaveLoadBalanceAlgorithm算法路由存在问题

### ISSUE THREAD

**Issue by shulyLi** [sharding-sphere/sharding-sphere#735]
**org.apache.ibatis.executor.statement.PreparedStatementHandler**.query
![image](https://user-images.githubusercontent.com/11692089/38844890-e7d54fa4-4227-11e8-9bcf-80c79dacc87e.png)

ps.execute(); 会调用一次 MasterSlaveLoadBalanceAlgorithm.getDataSource

这是函数调用栈
![image](https://user-images.githubusercontent.com/11692089/38844947-293b8d28-4228-11e8-93ba-6ab3e8819197.png)
----------
return resultSetHandler.<E> handleResultSets(ps);  也会调用 MasterSlaveLoadBalanceAlgorithm.getDataSource
这是函数调用栈

![image](https://user-images.githubusercontent.com/11692089/38845240-4e1d8726-4229-11e8-97b0-9b9bfa273177.png)
-----
就是 一次 数据操作 会让 RoundBin 的  计数 增加2 
一般都是 用   id  & ((1<< x) - 1)    就会 ～～

这问题 怕是修复不了吧～

**Comment by terrymanu** [comment]
Please provide version

**Comment by ypg521** [comment]
我也发现有同样的问题，我的版本号是 sharding-jdbc-spring-boot-starter 2.0.0.M3

**Comment by haocao** [comment]
Could you please provide the problem sample code which based on https://github.com/shardingjdbc/sharding-jdbc-example and put it on github?
Just put your complete project codes inside of sharding-jdbc-spring-boot-example/sharding-jdbc-spring-boot-data-mybatis-example, and we can run it to reproduce the problem. Thanks for your helps.
@shulyLi @ypg521

**Comment by ypg521** [comment]
OK，At Weekend. I must BanZhuan today

**Comment by haocao** [comment]
@ypg521 Thanks, just remind that don't push any sensitive data or codes into github.

**Comment by shulyLi** [comment]
我不认为 这算一个bug， 只不过在一次的操作内进行了多次 getDataSource,
     roundbin ： atomic.increase 次数多。且影响 轮训的效果 cas 毕竟是一个 内核支持的原子操作。
     random   ：  new Random().nextInt(slaveDataSourceNames.size()) 要的 System.nanoTime()
    都不是 频繁友好的操作。

**Comment by shulyLi** [comment]
Forgive me for not using English

**Comment by ypg521** [comment]
But The result is always hit a same DB 。

**Comment by shulyLi** [comment]
@ypg521   The amount of concurrency is too low

**Comment by ypg521** [comment]
mybatis在第二次获取connection的时候，使用的是Statement.getConnection()； 我理解的是Statement在第二次获取connection的时候，是不需要getDataSource的； 抱歉我英语不好。

**Comment by shulyLi** [comment]
@ypg521 说的也对，尽管 不能说是bug 但是在一次 原子查询里就要进行多次的 get  也不太合理

**Comment by ypg521** [comment]
@terrymanu https://github.com/ypg521/sharding-jdbc-demo .

**Comment by terrymanu** [comment]
master slave module is couple with JDBC, we plan to split it from JDBC layer, and will fix this issue at that time.

**Comment by haocao** [comment]
Fixed in 3.0.0
