### ISSUE TITLE
分库分表KEY为NOW()时无法正确路由到目标数据库

### ISSUE THREAD

**Issue by Anricx** [sharding-sphere/sharding-sphere#757]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
2.0.3

### Expected behavior （您预期的结果是）
自动填充当前数据库NOW()对应到时间作为shardingValues实现doSharding。

### Actual behavior （实际运行的结果是）
1. 当选择StandardShardingStrategyConfiguration若判断到NOW()函数是直接将VALUE替换为了空值，并且PreciseShardingAlgorithm不会被调用执行；
2. 当设置ComplexShardingStrategyConfiguration时NOW()函数是直接将VALUE替换为了空值。

**Comment by terrymanu** [comment]
I transfer this issue to #1497. For English only in future, other languages will not accept.

**Comment by Anricx** [comment]
ok english is good
