### ISSUE TITLE
读写分离时，for update和之后的读操作落在从库而不是主库

### ISSUE THREAD

**Issue by pnfee** [sharding-sphere/sharding-sphere#767]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
2.0.0
### Expected behavior （您预期的结果是）
我在使用读写分离的时候，我希望在我使用for update语句和之后的语句都是操作写库。
### Actual behavior （实际运行的结果是）
但现在我在一个事务中for update后的读取依然是操作的读库。
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
（代码请基于 https://github.com/shardingjdbc/sharding-jdbc-example）

**Comment by ma-xiao-guang-64** [comment]
you can use hint to avoid it

**Comment by itbright-cn** [comment]
@pnfee 请问您的问题解决了么？我现在遇到的问题和你的有点儿像，但是还不完全相同。
我的场景如下：一主一从，代码在循环（循环继续的条件与从数据库中插入的数据是否有效有关）里面往主库插入数据，还会从从库里面去查询，这时，因为主从延迟问题，会导致我的插入数据会是多条。之前没有分主从的时候是没有问题的，我想知道大家是否有到同样的问题，看看是否有解决思路。感谢！

**Comment by afredlyj** [comment]
@itbright-cn 强制走主库，能满足你的业务场景吗？如果要强制走主库，可以使用`HintManger`。

**Comment by terrymanu** [comment]
I create a new issue #1496 to transfer this issue. For English only in future, other languages will not accept.
