### ISSUE TITLE
多数据源和分表配置支持

### ISSUE THREAD

**Issue by liuhuawu** [sharding-sphere/sharding-sphere#804]
现在有个需求，要求：
1. 配置多数据源，每个数据源里表是不相同的，如客户中心和订单中心
2. 每个数据源里的表需要分表，如订单中心的表order_0,order_1
请问各位，使用Sharding-jdbc，且事务可以正常使用，该如何配置，谢谢！！
看了下官方用例好像没有这个方面的示例。

<bean id="demo_ds" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
        <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://localhost:3306/demo_ds"/>
        <property name="username" value="root"/>
        <property name="password" value="root"/>
    </bean>
    
     <bean id="demo_ds_1" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
        <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://localhost:3306/demo_ds1"/>
        <property name="username" value="root"/>
        <property name="password" value="root"/>
    </bean>
    
    <sharding:standard-strategy id="orderTableShardingStrategy" sharding-column="order_id" precise-algorithm-class="io.shardingjdbc.example.spring.namespace.mybatis.algorithm.PreciseModuloTableShardingAlgorithm"/>
    <sharding:standard-strategy id="orderItemTableShardingStrategy" sharding-column="order_id" precise-algorithm-class="io.shardingjdbc.example.spring.namespace.mybatis.algorithm.PreciseModuloTableShardingAlgorithm"/>
    
    <sharding:data-source id="shardingDataSource">
        <sharding:sharding-rule data-source-names="demo_ds,demo_ds_1" >
            <sharding:table-rules>
                <sharding:table-rule logic-table="t_order" actual-data-nodes="demo_ds.t_order_${0..1}" table-strategy-ref="orderTableShardingStrategy" generate-key-column="order_id" />
                <sharding:table-rule logic-table="t_order_item" actual-data-nodes="demo_ds_1.t_order_item_${0..1}" table-strategy-ref="orderItemTableShardingStrategy" generate-key-column="order_item_id" />
            </sharding:table-rules>
        </sharding:sharding-rule>
    </sharding:data-source>
    
    <bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
        <property name="dataSource" ref="shardingDataSource" />
    </bean>
    <tx:annotation-driven transaction-manager="transactionManager" />
目前是这样配置的，不知道有没有问题 @chncho

**Comment by chncho** [comment]
每个数据源内可以保证事务，多个数据源目前就是柔性事务了
其它的就是分表的策略配置了

**Comment by chncho** [comment]
事务相关：http://shardingjdbc.io/docs_cn/02-guide/transaction/

**Comment by terrymanu** [comment]
yes, use base transaction for distribute db is better
