### ISSUE TITLE
关于exists的子查询不支持么？

### ISSUE THREAD

**Issue by Janyd** [sharding-sphere/sharding-sphere#809]
### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
sharding-jdbc-core-spring-boot-starter:2.0.3

### Expected behavior （您预期的结果是）
select * from a where exists (select 1 from b where b.a_id = a.id)
这种子查询是不是不支持呢？

**Comment by Janyd** [comment]
文档上明确表示不支持

**Comment by limingwei** [comment]
使劲向开发组证明这个需求的正当性必要性，也许就提前排期实现

**Comment by terrymanu** [comment]
glad to see you can find answer from document
