### ISSUE TITLE
关于 如何快速切换 主备的疑问

### ISSUE THREAD

**Issue by zhao41654828** [sharding-sphere/sharding-sphere#814]
当生产环境，master 出现故障的时候，如何快速切换master-slave配置？

可能解决方案：
* 通过dns的方式，修改dns的配置；
* 将数据源放置在zk上，当监控到master故障的时候，手动更改下发 数据源配置；

官方推荐的方式是什么呢？
能否做到识别故障，自动切换？

**Comment by terrymanu** [comment]
Maybe it is better to use double master, switch between master and slave cannot guarantee data integrity。

**Comment by zhao41654828** [comment]
双主，应该也存在配置的问题吧
出现故障的时候，怎么快速切换到另外一台master呢

**Comment by zhao41654828** [comment]
恩，双主 自动切换，可能是最终的解决方案
目前，这里 另外一台master 只是作为 一台灾备，当master出故障的时候，手动切换一下，这样可能稳定以及可靠一些

另外：官方群，还有名额吗，这里咨询问题，稍微有些慢~

**Comment by terrymanu** [comment]
I think he topic has already finished. Let me close it.
