### ISSUE TITLE
Change copyright from dangdang.com to shardingsphere.io

### ISSUE THREAD

**Issue by chidaodezhongsheng** [sharding-sphere/sharding-sphere#816]
Sharding-Sphere was incubated in dangdang, current copyright belongs to dangdang.com.

For better growth development of Sharding-Sphere, Dangdang decided to donate it to sharding sphere community. The PMC(http://shardingsphere.io/community/en/organization/) governs the project. New package name will base on PMC vote, io.shardingsphere may a good choice.

Hope more companies and organizations join Sharding-Sphere community.

**Comment by oracle219** [comment]
Dangdang has go on to contribute for Sharding-Sphere.

**Comment by yue530tom** [comment]
Dangdang use Sharding-JDBC on production environment now, hope Sharding-Sphere be better

**Comment by terrymanu** [comment]
hope Sharding-Sphere be better on comninity

**Comment by haocao** [comment]
Sharding-Sphere has been known as a famous database middleware solution, and lots of companies used it in the production environment, hope Sharding-Spherebe better on community.
