### ISSUE TITLE
分片建in查询，死循环

### ISSUE THREAD

**Issue by liuqianzhong** [sharding-sphere/sharding-sphere#827]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题
sj死循环，导致内存溢出
### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
2.1版本
### Expected behavior （您预期的结果是）
虽然sql不对，但是sj不能死循环，导致内存溢出，影响其他业务，sql报错就行
### Actual behavior （实际运行的结果是）
死循环
### Steps to reproduce the behavior （可重现问题的操作步骤）
select * from table where id in ();
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

![image](https://user-images.githubusercontent.com/30542968/39973315-f4e50642-5750-11e8-8523-73d4feedbd22.png)
Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by terrymanu** [comment]
fixed at #825

**Comment by terrymanu** [comment]
fixed at 3.0.0.M1
