### ISSUE TITLE
[Vote] Welcome new PMC member Haifeng Shi joining Sharding-Sphere

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#831]
Sharding-Sphere, originally named Sharding-JDBC, was initially created by the architecture department of DangDang company. Today, we will invite Haifeng Shi(@PegasusS) who is an ex-director of the architecture department in DangDang company to join into Sharding-Sphere PMC. 

Haifeng Shi is one of the original leaders of Sharding-JDBC and now is the senior director of the technical innovation department in ele.me company. He has a rich industry experience and advanced ideas, and i believe that his joining will make  Sharding-Sphere better and better.

All PMC members, please vote for this decision:

@haocao 
@wu-sheng 
@hanahmily 

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

中文翻译：

[投票] 欢迎新成员 史海峰 加入Sharding-Sphere PMC

Sharding-Sphere的前身Sharding-JDBC最初孵化于当当架构部。现投票邀请原当当架构部总监，现任饿了么高级总监史海峰加入Sharding-Sphere PMC，共同参与和决策Sharding-Sphere的开发和运营相关事宜。

史海峰是Sharding-JDBC的最初决策者之一，饿了么技术创新部产品研发团队。
曾在神州数码、亚信联创长期从事电信行业业务支撑系统集成工作，参与中国移动、中国联通多个项目，具有丰富的大型业务系统研发实施经验。
曾在当当负责总体架构规划、技术规范制定和技术预研推广，善于把握复杂业务需求，提出创新性解决方案，参与多个重点项 目的方案设计，在项目中对系统架构进行持续改造优化。负责技术委员会组织管理工作，发掘最佳实践、推动技术革新，组织内外部技术交流。
现负责北京研发中心产品研发创新团队。
曾参加多次业界技术大会，包括ArchSummit、QCon、SACC、TOP100、SDCC、GITC、MPD等，任讲师及出品人，不定期更新自媒体微信公众号“IT民工闲话”。

请现任全体PMC成员投票。

**Comment by terrymanu** [comment]
+1

**Comment by hanahmily** [comment]
+1 Welcome my former boss

**Comment by haocao** [comment]
+1

**Comment by wu-sheng** [comment]
My +1 binding.

**Comment by tristaZero** [comment]
+1

**Comment by terrymanu** [comment]
Thanks for everybody, vote is finish. Welcome haifeng to join us.
