### ISSUE TITLE
Maven无法正确获取jar包，404 Not Found？

### ISSUE THREAD

**Issue by LaiHuanMin** [sharding-sphere/sharding-sphere#832]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Expected behavior （您预期的结果是）
公共Maven库可以访问，哪怕是给予一个jar包也好，方便开发者使用

### Actual behavior （实际运行的结果是）
Maven查找不到该坐标
<dependency>
    <groupId>io.shardingsphere</groupId>
    <artifactId>sharding-jdbc</artifactId>
    <version>${latest.release.version}</version>
</dependency>

### Steps to reproduce the behavior （可重现问题的操作步骤）
pom.xml

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
写入以下代码到pom.xml，因为这只是配置，无法重现，
<dependency>
    <groupId>io.shardingsphere</groupId>
    <artifactId>sharding-jdbc</artifactId>
    <version>${latest.release.version}</version>
</dependency>

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by terrymanu** [comment]
please replace ${latest.release.version} to the version you wanted

**Comment by LaiHuanMin** [comment]
I'm confused because the latest.release.version, I was think it's a variable. And where's the version list can I choose? I can not found version in maven public repo and the document also doesn't offer a link to development.

**Comment by LaiHuanMin** [comment]
@terrymanu Is the sharding-jdbc in maven public repo()?  
I add the dependency to xml file, but the ide notice me the dependency isn't exist.Where's the code wrong?please
```
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc</artifactId>
            <version>3.0</version>
        </dependency>
```

**Comment by terrymanu** [comment]
http://mvnrepository.com/artifact/io.shardingjdbc
