### ISSUE TITLE
Spring cloud 健康检查显示Mysql状态为down

### ISSUE THREAD

**Issue by Pramy** [sharding-sphere/sharding-sphere#837]
## 环境：
spring boot ：1.5.9.RELEASE
spring cloud：Edgware.SR3
sharding-jdbc：2.0.3
## 问题：
当开启spring cloud 的健康检查的是时候，心跳线程会向mysql 发送一条sql语句
```sql
select 1
```
以此来确认数据库的健康情况
在线上环境中出现了一下情况（访问/health接口）
```json
{
    "status": "DOWN",
    "database": "MySQL",
    "error": "org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 11"
}
```

但是由于我分了11个库，然后这条语句返回了11个结果，导致健康检查不通过

**Comment by terrymanu** [comment]
fixed at 3.0.0.M1

**Comment by KinCao** [comment]
现在有3.0.0.M1版本吗？我现在这么写报错
<dependency>
            <groupId>io.shardingjdbc</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>3.0.0.M1</version>
</dependency>
