### ISSUE TITLE
sharding-proxy 会把mysql的连接全部用完

### ISSUE THREAD

**Issue by jensolzhu** [sharding-sphere/sharding-sphere#838]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
sharding-proxy-3.0.0.M1-SNAPSHOT
### Steps to reproduce the behavior （可重现问题的操作步骤）
mysql5.5，配置完后，启动sharding-proxy
用mysql客户端连接被分库分表的数据库（3306），“show processlist;”命令查看连接全部用完；关闭sharding-proxy恢复正常。
mysql客户端连接3307，出错：ERROR 2013 (HY000): Lost connection to MySQL server at 'waiting for initial communication packet', system error: 0

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by tuohai666** [comment]
Hi jensolzhu, could you show me the mysql result of: 
show variables like '%max_connections%';
Any way I will check out this issue later.

**Comment by jensolzhu** [comment]
thanks all
