### ISSUE TITLE
clean some unnecessary code 

### ISSUE THREAD

**Issue by hqq2023623** [sharding-sphere/sharding-sphere#840]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
2.0.3 , branch : master
### 1、Useless object created
ShardingRule#createTableRuleWithDefaultDataSource， line 126
a new instance config is created but no where else in this method use the result
<img width="919" alt="image1" src="https://user-images.githubusercontent.com/6971152/40152567-3faac748-59b8-11e8-8e8c-d5dfba8101d5.png">

### 2、instanceof will always return true 
WhereClauseParser#getColumnWithOwner ， line 232
propertyExpression.getOwner() will return an instance of SQLIdentifierExpression,so it's no need to do the instanceof check
<img width="1106" alt="image2" src="https://user-images.githubusercontent.com/6971152/40152589-6370fcce-59b8-11e8-8434-ad74aaf41034.png">

### 3、double assignment
 DefaultKeyGenerator#generateKey， line 104
the assignment  of sequence++   is useless because of the final value of sequence is (sequence + 1) & SEQUENCE_MASK , sequence + 1 could be better
<img width="639" alt="image3" src="https://user-images.githubusercontent.com/6971152/40152677-c03b4d74-59b8-11e8-9dd1-38ad65adb9e8.png">

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by terrymanu** [comment]
Thank you for the advice. You have already familiar the source code, could you submit a pull request to fix them?
