### ISSUE TITLE
最新代码编译出错（3.0.0.M1）

### ISSUE THREAD

**Issue by jensolzhu** [sharding-sphere/sharding-sphere#841]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
3.0.0.M1
### Steps to reproduce the behavior （可重现问题的操作步骤）
按照FAQ，先到子工程“sharding-jdbc-orchestration”执行：mvn install，成功。
再回到上级目录执行：mvn -Dmaven.test.skip=true clean install，出现如下错误：
sharding-sphere 3.0.0.M1 ........................... SUCCESS [  1.676 s]
[INFO] sharding-sql-test .................................. SUCCESS [  3.576 s]
[INFO] sharding-core ...................................... SUCCESS [ 24.729 s]
[INFO] sharding-jdbc ...................................... SUCCESS [  7.537 s]
[INFO] sharding-jdbc-spring ............................... SUCCESS [  0.352 s]
[INFO] sharding-jdbc-spring-namespace ..................... SUCCESS [  3.308 s]
[INFO] sharding-jdbc-spring-boot-starter .................. SUCCESS [  3.280 s]
[INFO] sharding-jdbc-transaction-parent ................... SUCCESS [  0.092 s]
[INFO] sharding-jdbc-transaction-storage .................. SUCCESS [  2.798 s]
[INFO] sharding-jdbc-transaction .......................... SUCCESS [  2.799 s]
[INFO] sharding-jdbc-transaction-async-job ................ SUCCESS [  3.865 s]
[INFO] sharding-jdbc-orchestration ........................ SUCCESS [ 29.166 s]
[INFO] sharding-jdbc-orchestration-spring ................. SUCCESS [  0.115 s]
[INFO] sharding-jdbc-orchestration-spring-namespace ....... FAILURE [  1.097 s]
[INFO] sharding-jdbc-orchestration-spring-boot-starter .... SKIPPED
[INFO] sharding-opentracing ............................... SKIPPED
[INFO] sharding-proxy 3.0.0.M1 ............................ SKIPPED

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project sharding-jdbc-orchestration-spring-namespace: Compilation failure
[ERROR] /C:/OpenSource/sharding-sphere/sharding-sphere/sharding-jdbc-orchestration-spring/sharding-jdbc-orchestration-spring-namespace/src/main/java/io/shardingsphere/jdbc/orchestration/spring/namespace/handler/OrchestrationMasterSlaveNamespaceHandler.java:[21,68] 找不到符号
[ERROR]   符号:   类 OrchestrationMasterSlaveDataSourceBeanDefinitionParser
[ERROR]   位置: 程序包 io.shardingsphere.jdbc.orchestration.spring.namespace.parser

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by haocao** [comment]
Please check if your codes are newest and trying to recompile again.

**Comment by terrymanu** [comment]
you should mvn install them from root pom

**Comment by jensolzhu** [comment]
后来检查发现是OrchestrationMasterSlaveDataSourceBeanDefinitionParser.java文件名太长，windows上拉取不下来

**Comment by unimme** [comment]
window磁盘文件路径有最大长度限制，win10默认260个字符。
OrchestrationMasterSlaveDataSourceBeanDefinitionParser.java 的文件路径很有可能超过该限制。
有两个解决方案：
1、把项目更新到根目录下。
2、修改win10的文件路径长度限制。
https://jingyan.baidu.com/article/4d58d5417727e19dd4e9c0dd.html，修改注册表可以解除限制
3、git：git config --global core.longpaths true
4、mvn install -Dmaven.test.skip=true
