### ISSUE TITLE
typo in doc

### ISSUE THREAD

**Issue by hqq2023623** [sharding-sphere/sharding-sphere#846]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
http://shardingsphere.io/document/cn/features/sharding/concept/process/
### Expected behavior （您预期的结果是）
3.1.1 核心概念 -> 流程
启示 应改为 起始
### Actual behavior （实际运行的结果是）
![image](https://user-images.githubusercontent.com/6971152/40212670-b2370f6c-5a83-11e8-9559-c82972d47b05.png)

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by haocao** [comment]
Fixed, thanks for your correction.
