### ISSUE TITLE
压测过程中发现AbstractExecutionEvent初始化占用cpu比例很大，有什么优化建议吗？

### ISSUE THREAD

**Issue by 7shitang0841** [sharding-sphere/sharding-sphere#850]
### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
版本为2.0.3
### Expected behavior （您预期的结果是）
AbstractExecutionEvent的cpu占有比例不应该大于数据库执行的cpu时间
### Actual behavior （实际运行的结果是）
cpu占有率过高

![image](https://user-images.githubusercontent.com/19660668/40220900-49885c08-5aad-11e8-8cbc-31c39b144f41.png)

**Comment by terrymanu** [comment]
close without any reason, so I just put this issue as `invalid`
