### ISSUE TITLE
考虑支持多数据源的 Replica 嘛？

### ISSUE THREAD

**Issue by shenvx** [sharding-sphere/sharding-sphere#853]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）

Sharding-JDBC 2.0.3

### Expected behavior （您预期的结果是）

Sharding Sphere 考虑支持多数据源的 Replica 嘛

**Comment by terrymanu** [comment]
No, the scope of data replica is feature of database, but we focused on middleware.
