### ISSUE TITLE
2.0.3版本支持 spring yaml文件配置或者xml进行配置么？

### ISSUE THREAD

**Issue by qchen006** [sharding-sphere/sharding-sphere#855]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
2.0.3
### Expected behavior （您预期的结果是）
能够识别xml标签
### Actual behavior （实际运行的结果是）
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'sharding:standard-strategy'.
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by tuohai666** [comment]
Yes, please refer to http://shardingjdbc.io/document/legacy/2.x/cn/02-guide/configuration/
