### ISSUE TITLE
sharding-proxy测试问题（中文乱码，应用死锁等）

### ISSUE THREAD

**Issue by jensolzhu** [sharding-sphere/sharding-sphere#858]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
windows 10
mysql5.5
sharding-proxy-3.0.0.M1
### Expected behavior （您预期的结果是）
1、中文正常
2、能马上返回错误
3、shardingColumn大小写忽略
### Actual behavior （实际运行的结果是）
1、中文乱码
2、应用死锁
3、shardingColumn需大小写一致
### Steps to reproduce the behavior （可重现问题的操作步骤）
1、springboot配置了sharding-proxy的数据源，如下：
spring.datasource.slave2.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.slave2.url=jdbc:mysql://127.0.0.1:3307/sharding_db?characterEncoding=utf8
spring.datasource.slave2.username=root
spring.datasource.slave2.password=sa
在insert时，中文为乱码。（不用sharding-proxy正常） 不知道还需要在哪里配置？

2、insert插入时shardingColumn在config.yaml中无法获取到dataSources，应用死锁。

3、shardingColumn需要严格大小写一致，实际上有些数据库是不区分大小写。

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by tuohai666** [comment]
Hi, jensolzhu, would you like join the WeChat group so that we can communicate more effectively?
Please refer to https://mp.weixin.qq.com/s/aXgWJyT1pskzyfr-AkEQtQ

**Comment by tuohai666** [comment]
For issue 1: Can you show me the 'show create table' of your actual tables? And the result of 'show variables like 'character_set_database';' of your databases;
For issue 2: Let me see the config.yaml completely;
For issue 3: It's a new feature, we will discuss whether to implement it in M2.

**Comment by jensolzhu** [comment]
**For issue 1:** 
**'show create table':**
CREATE TABLE `sys_logon_log` (
  `GROUP_ID` bigint(20) DEFAULT NULL COMMENT '组织ID（如果组织为空，代码表为全局的）',
  `LOG_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  `USER_NO` varchar(32) NOT NULL COMMENT '用户编号',
  `USER_NAME` varchar(64) NOT NULL COMMENT '用户名称',
  `PASSWORD` varchar(64) NOT NULL COMMENT '密码',
  `IP` varchar(64) NOT NULL COMMENT 'IP地址',
  `LOGON_TIME` datetime NOT NULL COMMENT '登录时间',
  `LOGOFF_TIME` datetime DEFAULT NULL COMMENT '下线时间',
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='登录日志'

**show variables like 'character_set_database';**
utf8

**For issue 2:**
dataSources:
  ds_1:
    url: jdbc:mysql://10.12.102.140:3306/ccuap1
    username: root
    password: root
  ds_2:
    url: jdbc:mysql://10.12.102.140:3306/ccuap2
    username: root
    password: root

shardingRule:
  tables:
    sys_logon_log:
      actualDataNodes: ds_${1..2}.sys_logon_log
      tableStrategy:
        inline:
          shardingColumn: group_id
          algorithmExpression: sys_logon_log
      keyGeneratorColumnName: group_id
  bindingTables:
    - sys_logon_log
  defaultDatabaseStrategy:
    inline:
      shardingColumn: group_id
      algorithmExpression: ds_${group_id}
  defaultTableStrategy:
    none:
  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator

  props:
    sql.show: true
**注：**当我在insert中group_id=3时，无法按照shardingRule获取到datasouce程序就一直等待在那里，建议timeout后抛异常

**Comment by tuohai666** [comment]
@jensolzhu I can't reproduce the issue, some information must be lost. Would you mind join the WeChat group or QQ group? We alse can communicate on gitter: https://gitter.im/shardingsphere

**Comment by tuohai666** [comment]
I doubt there's wrong config for your console, please show me the result of: show variables like '%char%'; in **actual** db and **proxy**.
