### ISSUE TITLE
找不到shrding schema

### ISSUE THREAD

**Issue by xiaoluozai** [sharding-sphere/sharding-sphere#859]
![image](https://user-images.githubusercontent.com/24823537/40408814-5f23904a-5e9b-11e8-9700-465122ec2730.png)

使用Sharding-Sphere版本：3.0.0.M1

Spring配置方式sharding tag无法应用

**Comment by terrymanu** [comment]
please read document carefully or take a look at example

**Comment by xiaoluozai** [comment]
I didn't find that example,hahaha~
I get it,hahaha~
https://github.com/sharding-sphere/sharding-sphere-example

Just thanks~
