### ISSUE TITLE
about data orchestration in cloud side

### ISSUE THREAD

**Issue by cherrylzhao** [sharding-sphere/sharding-sphere#862]
sharding-sphere provide cloud side data orchestration.
sharding datasource and rule configuration should be loaded into zookeeper or etcd first.
then, `OrchestrationDataSourceFactory` would create the sharding or master-slave datasourde based on the registry center.
this feature will simplify configuration work in many of distribution client access , for client side，you just need to configuration the address of the registry center. if database cluster will add/remove machines, you only need to modify the datasource info in the registry center,
application layer code would be updated smothly. 
this feature will be integraed with spring-namespace, besides raw jdbc and yaml also be supported.

**Comment by terrymanu** [comment]
finished at 3.0.0.M2
