### ISSUE TITLE
3.0.0.M1分库算法抛出异常不能处理

### ISSUE THREAD

**Issue by zy425407824** [sharding-sphere/sharding-sphere#872]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
3.0.0.M1
### Expected behavior （您预期的结果是）
前端捕获特定异常
### Actual behavior （实际运行的结果是）
前端获取到了数据库异常
### Steps to reproduce the behavior （可重现问题的操作步骤）
系统采用特定值分库时，如果sql里面传入的值出现问题，不能得到特定异常
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
public class DataSourceShardingAlgorithm implements PreciseShardingAlgorithm<Long> {

    @Override
    public String doSharding(Collection<String> collection, PreciseShardingValue<Long> preciseShardingValue) {
        for(String str:collection){
            if(str.equals("fin_"+preciseShardingValue.getValue())){
                return str;
            }
        }
        throw new BiException("01","该项目未开通系统功能,请联系管理员!");
    }

}

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by terrymanu** [comment]
you can use getCause to get original exception

**Comment by tristaZero** [comment]
Hi, @zy425407824, I write doSharding and throw self-defined exception using 3.0.0.M1, but i can not get SQLException, can you give me more detail about your issue? What's more, when try it using 3.0.0.M2, i can get my defined exception.

**Comment by tristaZero** [comment]
Hi, @zy425407824 Some tests have been given, if you have any problems, please contact me, Thanks.
