### ISSUE TITLE
这种场景下配置的数据库连接池问题

### ISSUE THREAD

**Issue by zhao41654828** [sharding-sphere/sharding-sphere#874]
[https://www.processon.com/embed/5b06dd08e4b0595cc8a61c76](https://www.processon.com/embed/5b06dd08e4b0595cc8a61c76)

如上图的架构，svr机房也部署在城市A和城市B。
A1作为唯一写点，A2为A城市的机器 读点，B2为B城市的读点（考虑到跨城访问对db的压力，读多写少场景）。

A城市的主备：A1，A2
B城市的主备：A1, B2

问题1：
这样，在配置连接池的时候，应该是建立了4个连接池吧，A1是否建立了2个连接池（假设是单库）？期待的是建立3个。

如果我还多建几组主备（比如，B1/A2，B1/B2），那这样连接池也对应增加呗？
能否连接池和db数据源对应，而不是随着主备增加而增加，这些主备组合也只是使用了一组数据源进行组合而已。

求各位大佬指点。 连接池 中也用了线程池来管理，这样线程数也会飙升，导致性能下降。

将配置中心配置在zk的方式，暂时没考虑呢，运维不太成熟，可能有较多坑。

**Comment by terrymanu** [comment]
I don't think you need
configuration different even using 
 multiple region, please try to understand the example and try to configure them first

**Comment by zhao41654828** [comment]
这里希望使用 sharding jdbc的分库算法，当正常 主备 出现故障的时候，希望能够切换到 其他的 备用 库。

这是目前，比较快且稳定的方案了。

所以会有配置多个主备的情况

**Comment by terrymanu** [comment]
sharding sphere cannot do failover now
