### ISSUE TITLE
关键字表名的处理bug问题

### ISSUE THREAD

**Issue by visoeclipse** [sharding-sphere/sharding-sphere#880]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

因为历史原因表名使用的是关键字“group”， 当使用sharding-jdbc之后， 在解析表名的时候会去掉转义字符`

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
sharding-jdbc 1.5

### Expected behavior （您预期的结果是）
正常应该是： FROM `group`

### Actual behavior （实际运行的结果是）
实际被selectStatement.getTables().add(new Table(SQLUtil.getExactlyValue(literals), sqlParser.parseAlias())); 去掉了``， 变为了 FROM group

### Steps to reproduce the behavior （可重现问题的操作步骤）
关键字表名应该都可以重现。

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by terrymanu** [comment]
close by yourself without any reason, we just mark this issue as invalid
