### ISSUE TITLE
Support keyword table names

### ISSUE THREAD

**Issue by visoeclipse** [sharding-sphere/sharding-sphere#887]
When use keyword as a table name, SS will burst Exception.

**Comment by inotgaoshou** [comment]
看着官方的mybatis分表主从例子，好像只符合一主一从，如果配置的是一主多次，发现会同时从配置的几个从库查询一遍。实际期望是从多个从库中的一个从库查询一次就可以。目前只能暂时配置指定一个从库，
这个demo：https://github.com/sharding-sphere/sharding-sphere-example/blob/dev/sharding-jdbc-example/spring-namespace-example/spring-namespace-mybatis-example/src/main/resources/META-INF/nodep/shardingMasterSlave.xml

**Comment by tuohai666** [comment]
Record the difference of delimiters of H2/MySQL/Oracle/SQLServer/PostgreSQL.

H2: "
There is a list of keywords that can't be used as identifiers (table names, column
names and so on), unless they are quoted (surrounded with **double quotes**). The
list is currently:
ALL, CHECK, CONSTRAINT, CROSS, CURRENT_DATE, CURRENT_TIME,
CURRENT_TIMESTAMP, DISTINCT, EXCEPT, EXISTS, FALSE, FETCH, FOR,
FOREIGN, FROM, FULL, GROUP, HAVING, INNER, INTERSECT, IS, JOIN, LIKE,
LIMIT, MINUS, NATURAL, NOT, NULL, OFFSET, ON, ORDER, PRIMARY, ROWNUM,
SELECT, SYSDATE, SYSTIME, SYSTIMESTAMP, TODAY, TRUE, UNION, UNIQUE,
WHERE, WITH

**Comment by tuohai666** [comment]
MySQL: `
The identifier quote character is the backtick (`).

**Comment by tuohai666** [comment]
PostgreSQL: "
There is a second kind of identifier: the delimited identifier or quoted identifier. It is formed by enclosing
an arbitrary sequence of characters in **double-quotes** ("). A delimited identifier is always an identifier,
never a key word. So "select" could be used to refer to a column or table named “select”, whereas an
unquoted select would be taken as a key word and would therefore provoke a parse error when used
where a table or column name is expected. The example can be written with quoted identifiers like this:
UPDATE "my_table" SET "a" = 5;

**Comment by tuohai666** [comment]
SQLServer: [ ]

You can create tables with the same name as keywords. If you "quote" the table name it should work. The default quotes in SQL server are **square brackets**: [ ]

**Comment by tuohai666** [comment]
Oracle: "

Same with H2 and PostgreSQL, the answer is **double quotes**.
