### ISSUE TITLE
是否使用批量insert必须升级到3.0版本， 3.0版本maven仓库在哪里？

### ISSUE THREAD

**Issue by qchen006** [sharding-sphere/sharding-sphere#890]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
2.0.3
### Expected behavior （您预期的结果是）
使用批量insert
### Actual behavior （实际运行的结果是）
2.0.3批量insert报错
尝试升级到3.0版本，发现中央maven仓库没有对应版本
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by limingwei** [comment]
是
中央仓库（坐标变了，http://search.maven.org/#artifactdetails%7Cio.shardingsphere%7Csharding-jdbc%7C3.0.0.M1%7Cjar）

**Comment by terrymanu** [comment]
http://mvnrepository.com/artifact/io.shardingsphere
