### ISSUE TITLE
使用 sharding jdbc 关于设置了defaultDataSourceName,未分片表多表关联查询报错

### ISSUE THREAD

**Issue by zhangfeibiao** [sharding-sphere/sharding-sphere#892]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
      1. com.dangdang sharding-jdbc-core 1.5.3
      2  com.dangdang  sharding-jdbc-config-common  1.5.3
### Expected behavior （您预期的结果是）
设置了默认数据源后，未分片的单表查询正常执行，未分片的表多表关联正常执行
### Actual behavior （实际运行的结果是）
未分片的单表查询正常运行，未分片的表多表关联不能正常运行，报错Cannot find table rule and default data source with logic tables
### Steps to reproduce the behavior （可重现问题的操作步骤）
看过源码，有默认数据源，没有配置tableRules的单表查询具体执行过程
1.
![image](https://user-images.githubusercontent.com/34374831/40760991-03ee5d40-64cc-11e8-9d54-4a50655777bd.png)
2
![image](https://user-images.githubusercontent.com/34374831/40760961-d50edcb6-64cb-11e8-8a3d-2a935d43711b.png)
3.
![image](https://user-images.githubusercontent.com/34374831/40761077-80f8fa98-64cc-11e8-8ca5-8a6c09d3aa82.png)
执行正常
有默认数据源，没有配置tableRules的多表Left join关联 查询执行过程
1.
![image](https://user-images.githubusercontent.com/34374831/40761036-3dd70e44-64cc-11e8-87a9-eb34da1296d8.png)
2.
![image](https://user-images.githubusercontent.com/34374831/40761065-6b11840c-64cc-11e8-9007-4341d16f5ca1.png)
3.
![image](https://user-images.githubusercontent.com/34374831/40761100-972b2cf0-64cc-11e8-9036-d2b4bcd87882.png)
执行报错

项目中正好遇到需要分表的场景，看了三天sharding sphere相关的产品，也看了很多官方手册和源码、博客，包括Issues列表中相关的问题，就是没有找到答案，Issues中有看到说1.5.3版本支持了，可是不行，恳请大牛帮忙指点下。
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
 SQL: SELECT sm.id, sm.scrm_brand_id, sm.scrm_card_id, ucm.unique_user_id   FROM scrm_member AS sm  LEFT JOIN ems_user_channel_mapping AS ucm  ON sm.id = ucm.usr_id                AND sm.mobile = ?
### Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Cannot find table rule and default data source with logic tables: '[ems_user_channel_mapping, scrm_member]'
Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by zhangfeibiao** [comment]
我使用的是当当网的maven中央仓库，这个应该没有影响吧

**Comment by zhangfeibiao** [comment]
我现在是对会员数据分表，不分库。根据会员表中有手机号进行hash取摸分30张表，根据有账号进行hash去模分20张表，分片策略如下，
![image](https://user-images.githubusercontent.com/34374831/40762826-d8628a08-64d4-11e8-8541-a3c0ebf3df66.png)

**Comment by tristaZero** [comment]
@zhangfeibiao hi, now i focus on this issuse. Did you join in your Wechat group? Please contact with trista on Wechat group, so we can talk more, thanks a lot.

**Comment by zhangfeibiao** [comment]
@tristaZero First of all, thank you very much for your concern. However, I did not join WeChat group. Could you please tell me your WeChat ID?

**Comment by tristaZero** [comment]
@zhangfeibiao 840462575, My WeChat ID.

**Comment by tristaZero** [comment]
@zhangfeibiao Hi, can we talk more about this issue? I did not receive your friend request.

**Comment by tristaZero** [comment]
Hi, @zhangfeibiao So far, I haven't received your friend request yet, so i can not get detail about your issue. But, i tried to reappear your problem. 

That is, there are two tables t1 and t2, without sharding rule but existed in the same default datasource, and i use the SQL of select * from t1 left join t2 on t1.order_id = t2.order_id to do query. The result is the expected one.

The difference between yours and mine is the vesion of Sharding-JDBC. Also i read the related code of the Version 1.5.3, if my case is same with yours, i think Sharding-JDBC of Ver.1.5.3 will cause this problem, but Ver 3.0.0.M1 will not.

So i suggest you to use Sharding-JDBC with latest version. Thanks a lot, if any problem, please let me know.

**Comment by xsong123** [comment]
我用的当当1.3.4版本可以，但是换成1.5.4会出现同样的错误
