### ISSUE TITLE
只做master-slave读写分离配置如何使用sql.show打印调试信息

### ISSUE THREAD

**Issue by happyjey** [sharding-sphere/sharding-sphere#899]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
2.0.3

### Expected behavior （您预期的结果是）
<master-slave:data-source id="masterSlaveDataSource" master-data-source-name="ds_master" slave-data-source-names="ds_slave_0" />
只做读写分离配置时希望可以使用sql.show或是其他方法能知道使用的是哪个库

**Comment by xiaoniao** [comment]
+1 需要显示日志。 

另外只做 master-slave 读写，不配置分库分表时，表名不能识别出大写字母，会提示表不存在。

Springl Boot 1.5.1.RELEASE
Sharding Jdbc 3.0.0.M1

@terrymanu

**Comment by tristaZero** [comment]
Please refer to #1004, Thanks a lot.
