### ISSUE TITLE
使用sharding:inline-strategy报错:通配符的匹配很全面, 但无法找到元素 'sharding:inline-strategy' 的声明。

### ISSUE THREAD

**Issue by MartinDai** [sharding-sphere/sharding-sphere#901]
Sharding-Sphere 版本：3.0.0.M1

 IDEA会提示：This custom Spring bean has not yet been parsed

看起来是sharding.xsd并没有生效

官网给的demo是：http://shardingjdbc.io/schema/shardingjdbc/sharding
但是sharding.xsd里面却不是这个地址，按照文件里面的配置修改成了http://shardingsphere.io/schema/shardingsphere/sharding
然后就报这个错误了

**Comment by terrymanu** [comment]
Have you ref example already?

**Comment by MartinDai** [comment]
Here is the document. http://shardingsphere.io/document/current/cn/manual/sharding-jdbc/configuration/config-spring-namespace/

**Comment by terrymanu** [comment]
Thank you, we will fix official website soon

**Comment by tristaZero** [comment]
All done.

**Comment by Dizent** [comment]
这个链接现在访问还是404，怎么解决的这个问题呢？
