### ISSUE TITLE
Can Support The Operation

### ISSUE THREAD

**Issue by shulyLi** [sharding-sphere/sharding-sphere#907]
Can I  specify a dataSource  In a few operation? 
In a short word , I hope do a few operation in a dataSource, because of  the Separation of reading and writing

**Comment by terrymanu** [comment]
Do you mean master-slave?

**Comment by shulyLi** [comment]
@terrymanu   yes !  Update  then Select , but I don't hope  that the operation will  has two connection ,

**Comment by shulyLi** [comment]
but I don't want to use Transactional.  Hope U response  and I will close it .

**Comment by terrymanu** [comment]
maybe you can take a look at: http://shardingsphere.io/document/current/en/features/read-write-split/

**Comment by shulyLi** [comment]
@terrymanu  thank U  !   想做到自如做到控制， 我会仔细阅读文档的，打扰！
