### ISSUE TITLE
SQL not supports "Calculate Expression, eg: SUM(pv) / COUNT(uv)" meaning?

### ISSUE THREAD

**Issue by wujun8** [sharding-sphere/sharding-sphere#914]
### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
3.0.0.M1
### Q
In https://github.com/sharding-sphere/sharding-sphere/blob/3.0.0.M1/ROADMAP.md 
> ## Kernel
> ### SQL
> - [ ] Calculate Expression, eg: SUM(pv) / COUNT(uv)

Because some features, like "INSERT INTO VALUES (xxx), (xxx)" are already supported, but not selected, so I'm not sure if "SUM(pv) / COUNT(uv)" is supported.
Can I get some examples of SUM(pv) / COUNT(uv) ？

**Comment by terrymanu** [comment]
Thank you to remind us, will update road immediately.

`SUM(pv) / COUNT(uv)` is not supported now.

**Comment by terrymanu** [comment]
done

**Comment by wujun8** [comment]
@terrymanu 
OK. But that's not my point.
I know that ```SUM(pv) / COUNT(uv)``` is not supported. I just don't understand what does it mean.
If there're some examples about that, it will be better.

**Comment by terrymanu** [comment]
just like avg need rewrite to sum and count, and for every data node, accumulate  sum and count, finally divide together.
So if SQL include `SUM(pv) / COUNT(uv)`, SQL should rewrite to `SUM(pv) , COUNT(uv)`, and divide in merge module

**Comment by wujun8** [comment]
Like this, right?
```sql
SELECT SUM(user_id) ... GROUP BY user_id
SELECT COUNT(DISTINCT status) ...
```
