### ISSUE TITLE
Groovy 解析 inline表达式导致OOM的问题

### ISSUE THREAD

**Issue by Pramy** [sharding-sphere/sharding-sphere#919]
## 版本号为 3.0.0.M1
环境是jdk1.8，spring boot 1.5.9，只使用的分库分表
## 问题
线上跑了一段时间后，发现class对象原来远多，晚上看了一下只有20w个class，但是到了早上就到了40w个，并且老年代持续升高并且gc回收的空间很少，最后直接oom了，通过dump分析，发现groovy加载了大量的classInfo，并且我的项目里只有SS依赖了groovy

## 复现代码
```java
    //-Xmx200m -Xms200m
    public static void main(String[] args) {
        for (int i = 0; i < 100000; i++) {
            new InlineExpressionParser("\"${0..9}-${0..9}\"").evaluate();
        }
    }
```

**Comment by xmh51** [comment]
粗暴的方案  添加 cache ` private static Map<String,List<String>> cacheEvaluateMap=new HashMap<>();

    /**
     * Split and evaluate inline expression.
     *
     * @return result list
     */
    public List<String> evaluate() {
        if (null == inlineExpression) {
            return Collections.emptyList();
        }
        List<String> cacheEvaluate=cacheEvaluateMap.get(inlineExpression);
        if(cacheEvaluate!=null){
            return cacheEvaluate;
        }
        cacheEvaluate= flatten(evaluate(split()));
        cacheEvaluateMap.put(inlineExpression,cacheEvaluate);
        return cacheEvaluate;
    }`

**Comment by terrymanu** [comment]
fixed at 3.0.0.M2
