### ISSUE TITLE
多线程数据merge会串，有时候不正确

### ISSUE THREAD

**Issue by nicholas879110** [sharding-sphere/sharding-sphere#931]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（
   eg：（1）pageSize =2
          pageNum = 1
          response::{"total":6,"pageNum":1,"pageSize":2,"pages":3,"size":4} 按理应该返回size的数据记录为2
       （2）pageSize =2
          pageNum = 1
          response::{"total":6,"pageNum":1,"pageSize":2,"pages":3,"size":2} 按理应该返回size的数据记录为2
           pageSize =10
          pageNum = 1
          response::{"total":6,"pageNum":1,"pageSize":10,"pages":1,"size":2} 按理应该返回size的数据记录为6
）
please fix this bug，its very important！
Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by terrymanu** [comment]
Pretty long time no response, and we cannot reproduce it, just close.
