### ISSUE TITLE
golang连接sharding-proxy时，插入string类型值时，报Cannot find value '-2' in column type

### ISSUE THREAD

**Issue by cairewen** [sharding-sphere/sharding-sphere#937]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
启动版本：sharding-proxy-3.0.0.M1
获取：https://github.com/sharding-sphere/sharding-sphere-doc/raw/master/dist/sharding-proxy-3.0.0.M1.tar.gz
### Expected behavior （您预期的结果是）
支持golang中string类型数据的存储
例如UserName string
type User struct {
	ID       uint64 `gorm:"primary_key;AUTO_INCREMENT"`
	UserId   uint64 `gorm:"column:user_id"`
	UserName string `gorm:"column:user_name"`
}

当把string类型的字段去掉时，可以插入成功，加上string类型字段，就报错了

### Actual behavior （实际运行的结果是）
[WARN ] 16:33:46.082 [nioEventLoopGroup-5-16] i.n.u.c.AbstractEventExecutor - A task raised an exception. Task: io.shardingsphere.proxy.frontend.mysql.MySQLFrontendHandler$1@5924c088
java.lang.IllegalArgumentException: Cannot find value '-2' in column type
	at io.shardingsphere.proxy.transport.mysql.constant.ColumnType.valueOf(ColumnType.java:136) ~[sharding-proxy-3.0.0.M1.jar:na]
	at io.shardingsphere.proxy.transport.mysql.packet.command.statement.execute.ComStmtExecutePacket.setParameterHeader(ComStmtExecutePacket.java:103) ~[sharding-proxy-3.0.0.M1.jar:na]
	at io.shardingsphere.proxy.transport.mysql.packet.command.statement.execute.ComStmtExecutePacket.setParameterList(ComStmtExecutePacket.java:89) ~[sharding-proxy-3.0.0.M1.jar:na]
	at io.shardingsphere.proxy.transport.mysql.packet.command.statement.execute.ComStmtExecutePacket.<init>(ComStmtExecutePacket.java:83) ~[sharding-proxy-3.0.0.M1.jar:na]
	at io.shardingsphere.proxy.transport.mysql.packet.command.CommandPacketFactory.getCommandPacket(CommandPacketFactory.java:59) ~[sharding-proxy-3.0.0.M1.jar:na]
	at io.shardingsphere.proxy.frontend.mysql.MySQLFrontendHandler$1.run(MySQLFrontendHandler.java:75) ~[sharding-proxy-3.0.0.M1.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-all-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
golang代码如下：
import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

func main() {
	db, err := gorm.Open("mysql", "root:5860730@tcp(127.0.0.1:3307)/ds")
	if err != nil {
		panic("failed to connect database")
	}
	defer db.Close()

	// Create
	user := User{UserId: 4, UserName:"test"}
	db.Create(&user)
}

config.ymal的配置如下：
dataSources:
  ds_0:
    url: jdbc:mysql://localhost:3306/ds_0
    username: root
    password: 
  ds_1:
    url: jdbc:mysql://localhost:3306/ds_1
    username: root
    password:

shardingRule:
  tables:
    t_user:
      actualDataNodes: ds_${0..1}.t_user_${0..3}
      tableStrategy:
        inline:
          shardingColumn: user_id
          algorithmExpression: t_user_${user_id % 4}
      keyGeneratorColumnName: user_id

  bindingTables:
    - t_user

  defaultDatabaseStrategy:
    inline:
      shardingColumn: user_id
      algorithmExpression: ds_${user_id % 2}

  defaultTableStrategy:
    none:
  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator

  props:
    proxy.mode: CONNECTION_STRICTLY
    sql.show: false

DB创建的表：
//创建database ds_0和ds_1
create database ds_0;
create database ds_1;
//创建ds_0的表
use ds_0;
-- auto-generated definition
 create table t_user_0
(
  id          bigint auto_increment
    primary key,
  user_id     bigint      not null,
  user_name   varchar(50) null,
  creator_id  bigint      null,
  create_time datetime    null,
  update_time datetime    null,
  constraint t_user_user_id_uindex
  unique (user_id)
);
  create table t_user_1
(
  id          bigint auto_increment
    primary key,
  user_id     bigint      not null,
  user_name   varchar(50) null,
  creator_id  bigint      null,
  create_time datetime    null,
  update_time datetime    null,
  constraint t_user_user_id_uindex
  unique (user_id)
);
  create table t_user_2
(
  id          bigint auto_increment
    primary key,
  user_id     bigint      not null,
  user_name   varchar(50) null,
  creator_id  bigint      null,
  create_time datetime    null,
  update_time datetime    null,
  constraint t_user_user_id_uindex
  unique (user_id)
);
  create table t_user_3
(
  id          bigint auto_increment
    primary key,
  user_id     bigint      not null,
  user_name   varchar(50) null,
  creator_id  bigint      null,
  create_time datetime    null,
  update_time datetime    null,
  constraint t_user_user_id_uindex
  unique (user_id)
);

//创建ds_1的表
use ds_1;
 create table t_user_0
(
  id          bigint auto_increment
    primary key,
  user_id     bigint      not null,
  user_name   varchar(50) null,
  creator_id  bigint      null,
  create_time datetime    null,
  update_time datetime    null,
  constraint t_user_user_id_uindex
  unique (user_id)
);
  create table t_user_1
(
  id          bigint auto_increment
    primary key,
  user_id     bigint      not null,
  user_name   varchar(50) null,
  creator_id  bigint      null,
  create_time datetime    null,
  update_time datetime    null,
  constraint t_user_user_id_uindex
  unique (user_id)
);
  create table t_user_2
(
  id          bigint auto_increment
    primary key,
  user_id     bigint      not null,
  user_name   varchar(50) null,
  creator_id  bigint      null,
  create_time datetime    null,
  update_time datetime    null,
  constraint t_user_user_id_uindex
  unique (user_id)
);
  create table t_user_3
(
  id          bigint auto_increment
    primary key,
  user_id     bigint      not null,
  user_name   varchar(50) null,
  creator_id  bigint      null,
  create_time datetime    null,
  update_time datetime    null,
  constraint t_user_user_id_uindex
  unique (user_id)
);

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by tuohai666** [comment]
Cairewen, Thank you. We have already fixed this bug. You may wait for 3.0.0.m2, or have a try on dev branch.

**Comment by tuohai666** [comment]
see #865
