### ISSUE TITLE
InlineShardingStrategy  使用 GroovyShell 导致 memory leak

### ISSUE THREAD

**Issue by xmh51** [sharding-sphere/sharding-sphere#945]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
3.0.0.M1  jdk 1.7

### Expected behavior （您预期的结果是）
正常运行

### Actual behavior （实际运行的结果是）
org.codehaus.groovy.reflection.ClassInfo 严重占用内存，导致内存溢出

### Steps to reproduce the behavior （可重现问题的操作步骤）
使用 InlineShardingStrategy 不断调用即可观察到栈内存的增长

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
https://github.com/sharding-sphere/sharding-sphere-example   InlineShardingStrategy  demo 不断调用即可
Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by terrymanu** [comment]
duplicate with #919

**Comment by xmh51** [comment]
解决方案 添加 cache  ` private static Map<String,List<String>> cacheEvaluateMap=new HashMap<>();

    /**
     * Split and evaluate inline expression.
     *
     * @return result list
     */
    public List<String> evaluate() {
        if (null == inlineExpression) {
            return Collections.emptyList();
        }
        List<String> cacheEvaluate=cacheEvaluateMap.get(inlineExpression);
        if(cacheEvaluate!=null){
            return cacheEvaluate;
        }
        cacheEvaluate= flatten(evaluate(split()));
        cacheEvaluateMap.put(inlineExpression,cacheEvaluate);
        return cacheEvaluate;
    }`
