### ISSUE TITLE
关于在使用读写分离时，使用insert into或者merge into中含有子查询抛“ORA-16000: 打开数据库以进行只读访问”的问题

### ISSUE THREAD

**Issue by 52liangbo** [sharding-sphere/sharding-sphere#966]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
3.0.0.M1
### Expected behavior （您预期的结果是）
merge into或者insert into或者update带有子查询可以正常运行
### Actual behavior （实际运行的结果是）
merge into或者insert into或者update带有子查询时抛出异常“ORA-16000: 打开数据库以进行只读访问”
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

`2018-06-25 21:36:16 198-[http-nio2-8080-exec-174]-[ERROR]-[ControllerExceptionHandler.handler(ControllerExceptionHandler.java:34)]-class ControllerExceptionHandler,message: PreparedStatementCallback; uncategorized SQLException for SQL [MERGE INTO TF_WX_KCARD_FAMILY_NUMBER t1 USING (SELECT ? AS phone, ? AS family_number , ? AS status FROM dual) t2 ON (t1.PHONE = t2.phone AND t1.FAMILY_NUMBER = t2.family_number)  WHEN MATCHED THEN UPDATE SET t1.STATUS = t2.status  WHEN NOT MATCHED THEN INSERT (phone, family_number, status, UPDATE_TIME) VALUES (t2.phone, t2.family_number, t2.status, sysdate)]; SQL state [72000]; error code [16000]; ORA-16000: 打开数据库以进行只读访问
; nested exception is java.sql.SQLException: ORA-16000: 打开数据库以进行只读访问`

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by terrymanu** [comment]
dup with #965
