### ISSUE TITLE
想请教一下，在配置了读写分离后，因为有业务逻辑的需求，需要再配多一个主从。但是这个主从是与第一个的完全不一样的，用分配规则好像不太恰当，请问要怎么实现呢

### ISSUE THREAD

**Issue by Edisonboy** [sharding-sphere/sharding-sphere#969]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by terrymanu** [comment]
I cannot get your point, could you provide more details?

**Comment by Edisonboy** [comment]
![image](https://user-images.githubusercontent.com/19949495/42017501-e779495a-7ae1-11e8-8b35-0e80ff2db428.png)
如截图所示，配置两个读写分离，但是有一些业务需要直接查询第二个数据源cdt数据中的数据，要怎样才可以直接指定数据源呢

**Comment by tcwloy** [comment]
我也想知道，有同样的诉求

**Comment by terrymanu** [comment]
Hello, we prefer use english to discuss issue.

In this case, I suggest use sharding + master-slave. please have a look at example: 
https://github.com/sharding-sphere/sharding-sphere-example/blob/dev/sharding-jdbc-example/raw-jdbc-example/src/main/java/io/shardingsphere/example/jdbc/main/nodep/yaml/ShardingAndMasterSlaveTogether.java

**Comment by Edisonboy** [comment]
Thank you for your answer. Forgive my bad expression in english.
But I still not understand exactly how to switch the datasource by myself.
Could you have more specific examples or have a comments about the yaml.
Thank you so much!

**Comment by terrymanu** [comment]
Hello, we prefer use english to discuss issue.
For bug report, we can keep it, but for question, we will close directly.
