### ISSUE TITLE
执行hibernate实体对象update时遍历所有表

### ISSUE THREAD

**Issue by Hyzhangjun** [sharding-sphere/sharding-sphere#970]
版本：sharding-jdbc_2.0.2
执行Hibernate实体对象保存时，分表字段为shop_id，在执行getHibernateTemplate().update(Object entity)对象保存时，hibernate输出的sql为：update t_member_card set shop_id=?, name=?, mobile=?, sex=?, password=?, send_sms=? where ID=?

而sharding-jdbc实际执行了所有拆分表，不是定位到具体的表执行更新，此处不能像save对象一样，根据参数中的分表健（shop_id）进行定位具体的表吗？还是update必须改成Hql在Where后面增加shop_id值？

**Comment by Hyzhangjun** [comment]
https://github.com/sharding-sphere/sharding-sphere/issues/469
问题跟这个是一样的，有没有什么好解决方案，

**Comment by Hyzhangjun** [comment]
我使用了官网的JPA示例进行了修改，发现问题同样存在，使用JPA更新对象时，能否像insert一样，参数中包含了分表字段即可定位到具体的表，而不是遍历所有表。

代码如下：
`
@Repository
@Transactional
public class OrderItemRepositoryImpl implements OrderItemRepository {
    
    @PersistenceContext
    private EntityManager entityManager;
    
    @Override
    public Long insert(final OrderItem orderItem) {
        entityManager.persist(orderItem);
        return orderItem.getOrderItemId();
    }
    
    @Override
    public void delete(final Long orderItemId) {
        Query query = entityManager.createQuery("DELETE FROM OrderItem i WHERE i.orderItemId = ?1 AND i.userId = 51");
        query.setParameter(1, orderItemId);
        query.executeUpdate();
    }
    
    @SuppressWarnings("unchecked")
    @Override
    public List<OrderItem> selectAll() {
        return (List<OrderItem>) entityManager.createQuery("SELECT i FROM Order o, OrderItem i WHERE o.orderId = i.orderId").getResultList();
    }

    @Override
    public void update(OrderItem orderItem) {
        //使用对象更新操作，会遍历所有表，而不是像insert一样，根据参数中包含的分表字段进行定位具体的表
        orderItem.setUserId(12);
        entityManager.merge(orderItem);
    }

    @Override
    public OrderItem get(Long orderItemId) {
        return null;  //To change body of implemented methods use File | Settings | File Templates.
    }
}`
配置如下：
`<bean id="preciseModuloTableShardingAlgorithm" class="io.shardingsphere.example.spring.namespace.jpa.fixture.algorithm.PreciseModuloTableShardingAlgorithm" />
    
    <sharding:standard-strategy id="tableShardingStrategy" sharding-column="order_id" precise-algorithm-ref="preciseModuloTableShardingAlgorithm" />
    
    <sharding:data-source id="shardingDataSource">
        <sharding:sharding-rule data-source-names="demo_ds">
            <sharding:table-rules>
                <sharding:table-rule logic-table="t_order" actual-data-nodes="demo_ds.t_order_${0..1}" table-strategy-ref="tableShardingStrategy" generate-key-column-name="order_id" />
                <sharding:table-rule logic-table="t_order_item" actual-data-nodes="demo_ds.t_order_item_${0..1}" table-strategy-ref="tableShardingStrategy" generate-key-column-name="order_item_id" />
            </sharding:table-rules>
        </sharding:sharding-rule>
        <sharding:props>
            <prop key="sql.show">true</prop>
        </sharding:props>
    </sharding:data-source>`

日志信息：
`2.Delete--------------
Hibernate: select orderitem0_.order_item_id as order_it1_1_0_, orderitem0_.order_id as order_id2_1_0_, orderitem0_.user_id as user_id3_1_0_ from t_order_item orderitem0_ where orderitem0_.order_item_id=?
[INFO ] 2018-06-27 20:36:18,977 --main-- [Sharding-Sphere-SQL] Logic SQL: select orderitem0_.order_item_id as order_it1_1_0_, orderitem0_.order_id as order_id2_1_0_, orderitem0_.user_id as user_id3_1_0_ from t_order_item orderitem0_ where orderitem0_.order_item_id=? 
[INFO ] 2018-06-27 20:36:18,977 --main-- [Sharding-Sphere-SQL] SQLStatement: SelectStatement(super=DQLStatement(super=AbstractSQLStatement(type=DQL, tables=Tables(tables=[Table(name=t_order_item, alias=Optional.of(orderitem0_))]), conditions=Conditions(orCondition=OrCondition(andConditions=[])), sqlTokens=[TableToken(beginPosition=134, skippedSchemaNameLength=0, originalLiterals=t_order_item)], parametersIndex=1)), containStar=false, selectListLastPosition=129, groupByLastPosition=0, items=[CommonSelectItem(expression=orderitem0_.order_id, alias=Optional.of(order_id2_1_0_)), CommonSelectItem(expression=orderitem0_.user_id, alias=Optional.of(user_id3_1_0_)), CommonSelectItem(expression=orderitem0_.order_item_id, alias=Optional.of(order_it1_1_0_))], groupByItems=[], orderByItems=[], limit=null, subQueryStatement=null) 
[INFO ] 2018-06-27 20:36:18,977 --main-- [Sharding-Sphere-SQL] Actual SQL: demo_ds ::: select orderitem0_.order_item_id as order_it1_1_0_, orderitem0_.order_id as order_id2_1_0_, orderitem0_.user_id as user_id3_1_0_ from t_order_item_0 orderitem0_ where orderitem0_.order_item_id=? ::: [[218831007296520192]] 
[INFO ] 2018-06-27 20:36:18,977 --main-- [Sharding-Sphere-SQL] Actual SQL: demo_ds ::: select orderitem0_.order_item_id as order_it1_1_0_, orderitem0_.order_id as order_id2_1_0_, orderitem0_.user_id as user_id3_1_0_ from t_order_item_1 orderitem0_ where orderitem0_.order_item_id=? ::: [[218831007296520192]] 
Hibernate: update t_order_item set order_id=?, user_id=? where order_item_id=?
[INFO ] 2018-06-27 20:36:19,013 --main-- [Sharding-Sphere-SQL] Logic SQL: update t_order_item set order_id=?, user_id=? where order_item_id=? 
[INFO ] 2018-06-27 20:36:19,013 --main-- [Sharding-Sphere-SQL] SQLStatement: DMLStatement(super=AbstractSQLStatement(type=DML, tables=Tables(tables=[Table(name=t_order_item, alias=Optional.absent())]), conditions=Conditions(orCondition=OrCondition(andConditions=[])), sqlTokens=[TableToken(beginPosition=7, skippedSchemaNameLength=0, originalLiterals=t_order_item)], parametersIndex=3)) 
[INFO ] 2018-06-27 20:36:19,013 --main-- [Sharding-Sphere-SQL] Actual SQL: demo_ds ::: update t_order_item_0 set order_id=?, user_id=? where order_item_id=? ::: [[218831006944198656, 12, 218831007296520192]] 
[INFO ] 2018-06-27 20:36:19,013 --main-- [Sharding-Sphere-SQL] Actual SQL: demo_ds ::: update t_order_item_1 set order_id=?, user_id=? where order_item_id=? ::: [[218831006944198656, 12, 218831007296520192]] 
[INFO ] 2018-06-27 20:36:19,078 --main-- [org.springframework.context.support.ClassPathXmlApplicationContext] Closing org.springframework.context.support.ClassPathXmlApplicationContext@131bf42: startup date [Wed Jun 27 20:36:14 CST 2018]; root of context hierarchy 
[INFO ] 2018-06-27 20:36:19,078 --main-- [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean] Closing JPA EntityManagerFactory for persistence unit 'default' 
`

[新建文本文档 (2).txt](https://github.com/sharding-sphere/sharding-sphere/files/2141259/2.txt)

**Comment by terrymanu** [comment]
If SQL don't include sharding-key, they just route to all data nodes. Any question here?

**Comment by Hyzhangjun** [comment]
使用sharding以后，分片字段肯定不能被更新，更新也会是脏数据，所以hibernate对象保存自动生成的sql使用主键做where条件，但实际的参数中是包含分片字段，所以个人建议update更新时，参数包含分片字段，可以考虑使用参数中的分片字段定位具体的表，不用执行所有表更新，这点应该跟insert是一样的。

**Comment by terrymanu** [comment]
hello, we prefer use english to discuss issue.
we don't care the SQL that hibernate auto generated. We just care about if SQL include sharding-key, then route to correct data nodes; if SQL exclude sharding-key, then route to all data nodes.

So what I want to know is any question here?

**Comment by terrymanu** [comment]
Very long time no response, and this question seems already have an answer. I just close it.

**Comment by yage-czy** [comment]
> hello, we prefer use english to discuss issue. we don't care the SQL that hibernate auto generated. We just care about if SQL include sharding-key, then route to correct data nodes; if SQL exclude sharding-key, then route to all data nodes.
> 
> So what I want to know is that any question here?

问题在于：第一，sharding的官网明确说明了【适用于任何基于 JDBC 的 ORM 框架，如：JPA, Hibernate, Mybatis, Spring JDBC Template 或直接使用 JDBC。】其中jpa排在首位，而jpa的save方法是使用率极高的。所以此处你说“we don't care the SQL that hibernate auto generated”我认为有些不妥。
第二，sharding的目的在于实现分库分表，使项目在大数据场景下效率更好，而此处调用save方法却会遍历所有的库进行操作，对于性能肯定是有影响的。
第三，遍历所有的库进行save操作，难道不会产生脏数据吗？
