### ISSUE TITLE
sharding-proxy 连接数太大了 怎么调

### ISSUE THREAD

**Issue by wanghaoyuissun** [sharding-sphere/sharding-sphere#971]
官网文档 有这些参数：
  ds_2:

```
    url: jdbc:mysql://192.168.2.186:3306/****?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: ****
    password: ****
    autoCommit: true
   connectionTimeout: 30000
   idleTimeout: 60000
   maxLifetime: 1800000
   maximumPoolSize: 10
```
当是源码里我看了 没有这些参数  了：

```
package io.shardingsphere.core.yaml.sharding;

public final class DataSourceParameter
{
  private String url;
  private String username;
  private String password;
  
  .....................
}

```
请问具体的怎么调小点连接数，我看了有100多个连接 ，太多了

**Comment by terrymanu** [comment]
just have a look at http://shardingsphere.io/document/current/en/manual/sharding-proxy/configuration/, search `proxy.mode`

**Comment by terrymanu** [comment]
@wanghaoyuissun if you close the issue by yourself, please explain your reason, thank you.

**Comment by wanghaoyuissun** [comment]
@terrymanu `  props:
    # MEMORY_STRICTLY: Proxy holds as many connections as the count of actual tables routed in a database.
    #                  The benefit of this approach is saving memory for Proxy by Stream ResultSet.
    # CONNECTION_STRICTLY: Proxy will release connections after get the overall rows from the ResultSet.
    #                      Meanwhile, the cost of the memory will be increased.
    proxy.mode: `
  I want to control the number of initial connections ,Now the initial is the maximum number of connections ,proxy.mode  What do you do

**Comment by wanghaoyuissun** [comment]
What I downloaded is  https://github.com/sharding-sphere/sharding-sphere-doc/raw/master/dist/sharding-proxy-3.0.0.M1.tar.gz , github is 3.0.0.M2-SNAPSHOT version ,
Do you have a package？

**Comment by terrymanu** [comment]
not release yet, will release soon.
