### ISSUE TITLE
主从模式，从库按权重路由实现了吗？

### ISSUE THREAD

**Issue by iTriumph** [sharding-sphere/sharding-sphere#981]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
3.0.0.M1

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

主从模式，从库按权重路由实现了吗？

我查了下源码，好像没发现，但在官方文档中找到了，能否告知源码位置或类名，谢谢！

**Comment by terrymanu** [comment]
Hello, we prefer use english to discuss issue.
For bug report, we can keep it, but for question, we will close directly.
