### ISSUE TITLE
请问如何获取插入数据ID

### ISSUE THREAD

**Issue by zhengjieyuan** [sharding-sphere/sharding-sphere#988]
### Which version of Sharding-Sphere do you using?
使用Sharding-Sphere 3.0.0.M2-SNAPSHOT
spring mvc 
mybatis
### Expected behavior
数据插入后返回Sharding-Sphere 自动生成的ID
### Actual behavior
是否需要通过defaultKeyGenerator.generateKey()方式获取ID后插入数据库？

**Comment by terrymanu** [comment]
Hello, we prefer use english to discuss issue.
For bug report, we can keep it, but for question, we will close directly.
