### ISSUE TITLE
fail to parsing postgresql due to the quotation 

### ISSUE THREAD

**Issue by finger92** [sharding-sphere/sharding-sphere#993]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
3.0.0.M1
### Expected behavior
correctly parsing sql (select * from "t_user")
### Actual behavior
sql after parsing was "select * from "tt_user"

**Comment by tuohai666** [comment]
Suspending. 
To fix this bug we need to change the structure of SS Parser, it is not worth it.
Fortunately, a new SS Parser will coming later, and let's come back to this issue that time.

**Comment by tuohai666** [comment]
Need to discuss with Liang.

**Comment by tuohai666** [comment]
Surprise! 
Fixed.
